var searchData=
[
  ['q_5fdisable_5fcopy_0',['Q_DISABLE_COPY',['../class_j_k_q_t_p_synchronized_1_1_read_locker.html#ad17137f12a62cad39b262655d77a84c7',1,'JKQTPSynchronized::ReadLocker::Q_DISABLE_COPY()'],['../class_j_k_q_t_p_synchronized_1_1_write_locker.html#af46ab2c3ea0b67575d42b64ac56ba08a',1,'JKQTPSynchronized::WriteLocker::Q_DISABLE_COPY()']]],
  ['qactions_20from_20a_20jkqtplotter_1',['QActions from a JKQTPlotter',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_ACTIONS',1,'']]],
  ['qcolorwithalpha_2',['QColorWithAlpha',['../group__jkqtpplotter__styling__classes.html#ga21fc7530be2b55534a14c60cf0a6da9e',1,'jkqtptools.h']]],
  ['qcolorwithalphaf_3',['QColorWithAlphaF',['../group__jkqtpplotter__styling__classes.html#ga4840ec94f56ddc9df4bf5d2c3d0c15ae',1,'jkqtptools.h']]],
  ['qhash_4',['qHash',['../group__jkqtpplottersupprt.html#gaf7f4d2cbc77fa6bb5446221d595c2183',1,'qHash(const JKQTBasePlotter::textSizeKey &amp;data, size_t):&#160;jkqtpbaseplotter.h'],['../group__jkqtpplottersupprt.html#ga9eb69bab982df82a87cb360af0254c80',1,'qHash(const QPair&lt; Qt::MouseButton, Qt::KeyboardModifiers &gt; &amp;key, size_t):&#160;jkqtplotter.h'],['../group__jkqtpplottersupprt.html#ga3a969e549641069030f33c0fcc70b0df',1,'qHash(const Qt::MouseButton &amp;key, size_t):&#160;jkqtplotter.h'],['../group__jkqtpplottersupprt.html#ga0434e31a1b052389e981dc8fedc06765',1,'qHash(const Qt::KeyboardModifiers &amp;key, size_t):&#160;jkqtplotter.h']]],
  ['qicon_20generation_5',['Special QIcon generation',['../group__jkqtptools__icons.html',1,'']]],
  ['qimage_20as_20a_20graph_6',['Example (JKQTPlotter): QImage as a Graph',['../_j_k_q_t_plotter_image_plot_q_image_r_g_b.html',1,'exampleTutorialProjects']]],
  ['qlabel_20class_20jkqtmathtextlabel_7',['Usage within a QLabel class JKQTMathTextLabel',['../class_j_k_q_t_math_text.html#JKQTMathTextUsageQLabel',1,'']]],
  ['qmake_8',['DEPRECATED: Build using QMake',['../page_buildinstructions__q_m_a_k_e.html',1,'page_buildinstructions']]],
  ['qmake_20dynamic_20library_9',['DEPRECATED: QMake Dynamic Library',['../page_buildinstructions__q_m_a_k_e.html#page_buildinstructions_QMAKEDYNAMIC',1,'']]],
  ['qmake_20in_20qtcreator_10',['DEPRECATED: QMake in QTCreator',['../page_buildinstructions__q_m_a_k_e.html#page_buildinstructions_QMAKEQTCREATOR',1,'']]],
  ['qmake_20include_20project_11',['DEPRECATED: QMake Include Project',['../page_buildinstructions__q_m_a_k_e.html#page_buildinstructions_QMAKEINCLUDE',1,'']]],
  ['qmake_20static_20library_12',['DEPRECATED: QMake Static Library',['../page_buildinstructions__q_m_a_k_e.html#page_buildinstructions_QMAKESTATIC',1,'']]],
  ['qscrollbar_20together_20with_20jkqtplotter_13',['Example (JKQTPlotter): Using a QScrollbar together with JKQtPlotter',['../_j_k_q_t_plotter_u_i_scrollbar.html',1,'exampleTutorialProjects']]],
  ['qt_14',['JKQTMathText LaTeX-Renderer for Qt',['../group__jkqtmathtext.html',1,'']]],
  ['qt_20based_20scientific_20plotter_20class_15',['JKQTPlotter: Qt based Scientific Plotter Class',['../group__jkqtplotter.html',1,'']]],
  ['qt_20data_20models_20to_20access_20graphs_20in_20a_20jkqtbaseplotter_20jkqtplotter_16',['Qt Data Models to Access Graphs in a JKQTBasePlotter/JKQTPlotter',['../group__jkqtpgraphsmodel.html',1,'']]],
  ['qt_20form_20designer_17',['Qt Form Designer',['../group__jkqtplotter__general__usage__qtcreator.html',1,'How to use JKQTPlotter in the Qt Form Designer'],['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USEQTCREATOR',1,'How to use JKQTPlotter in the Qt Form Designer'],['../_j_k_q_t_plotter_qt_creator.html#autotoc_md91',1,'Instructions on how to use JKQTPlotter in the Qt Form Designer']]],
  ['qt_20plotting_20library_18',['JKQTPlotter - A Qt Plotting Library',['../index.html',1,'']]],
  ['qt_20s_20clasess_19',['Tools around Qt&apos;s clasess',['../group__jkqtptools__qt.html',1,'']]],
  ['qt_20user_20interface_20designer_20ui_20file_20',['Tutorial (JKQTPlotter): Using a JKQTPlotter inside a Qt User Interface Designer (UI) File',['../_j_k_q_t_plotter_qt_creator.html',1,'exampleTutorialProjects']]],
  ['qt_20widgets_21',['Additional Qt Widgets',['../group__jkqtptools__qtwidgets.html',1,'']]],
  ['qt_20widgets_20tools_20to_20work_20with_20jkqtplotter_22',['Qt Widgets/Tools to work with JKQTPlotter',['../group__jkqtpqtwidgetsttools.html',1,'']]],
  ['qt6_20compatibility_20diverse_20improvements_20bugfixes_23',['V4.0.0: Qt6 compatibility &amp;amp; diverse improvements + bugfixes',['../page_whatsnew.html#page_whatsnew_V4_0_0',1,'']]],
  ['qtcreator_24',['DEPRECATED: QMake in QTCreator',['../page_buildinstructions__q_m_a_k_e.html#page_buildinstructions_QMAKEQTCREATOR',1,'']]],
  ['quantile1_25',['quantile1',['../struct_j_k_q_t_p_stat5_number_statistics.html#a3044c7a4422a2599c3e05a71ba2a92da',1,'JKQTPStat5NumberStatistics']]],
  ['quantile1spec_26',['quantile1Spec',['../struct_j_k_q_t_p_stat5_number_statistics.html#af008b5b9d9bcdadd35c0953e1fbb5163',1,'JKQTPStat5NumberStatistics']]],
  ['quantile2_27',['quantile2',['../struct_j_k_q_t_p_stat5_number_statistics.html#a4a7d9f917d013f8202cb5abc9aca31c8',1,'JKQTPStat5NumberStatistics']]],
  ['quantile2spec_28',['quantile2Spec',['../struct_j_k_q_t_p_stat5_number_statistics.html#ae9eb38c2b3afa108410ba3252ec033e2',1,'JKQTPStat5NumberStatistics']]],
  ['quickfit3_20compatible_20version_29',['v2018.08: Minor Modifications (Final QuickFit3-compatible Version)',['../page_whatsnew.html#page_whatsnew_V2018_08',1,'']]]
];
