var searchData=
[
  ['charts_0',['Impulse-Charts',['../group__jkqtplotter__sticks.html',1,'']]],
  ['charts_20parametrized_20scatter_20graphs_1',['Bubble Charts / Parametrized Scatter Graphs',['../group__jkqtplotter__linesymbolgraphs__param.html',1,'']]],
  ['cimg_20interfaceing_20tools_2',['CImg Interfaceing Tools',['../group__jkqtpinterfacecimg.html',1,'']]],
  ['clasess_3',['Tools around Qt&apos;s clasess',['../group__jkqtptools__qt.html',1,'']]],
  ['class_4',['class',['../group__jkqtfastplotter.html',1,'DEPRECATED: JKQTFastPlotter: Speed-Optimized Plotter class'],['../group__jkqtplotter.html',1,'JKQTPlotter: Qt based Scientific Plotter Class'],['../group__jkqtplotter__general__usage__jkqtbaseplotter.html',1,'Usage of JKQTBasePlotter Non-Visible Class']]],
  ['class_20function_20documentation_5',['Type/Class/Function Documentation',['../group__jkqtplotter__classdoc.html',1,'']]],
  ['class_20jkqtmathtext_6',['Math Renderer Class (JKQTMathText)',['../group__jkqtmathtext__render.html',1,'']]],
  ['class_20plotter_20widget_7',['Plotter Class &amp; Plotter Widget',['../group__jkqtpplotterclasses.html',1,'']]],
  ['classes_8',['classes',['../group__jkqtplotter__concretegraphs.html',1,'Concrete Graph Classes'],['../group__jkqtpdatastorage__classes.html',1,'Data Storage Classes'],['../group__jkqtmathtext__parser.html',1,'Math Markup Parser Classes'],['../group__jkqtplotter__elements.html',1,'Plot Element Classes'],['../group__jkqtpplotter__styling__classes.html',1,'Styling System Classes']]],
  ['classes_20and_20functions_9',['Support Classes and Functions',['../group__jkqtpplottersupprt.html',1,'']]],
  ['classes_20for_20concurrency_10',['Tools, Templates and Classes for Concurrency',['../group__jkqtptools__concurrency.html',1,'']]],
  ['classes_20for_20error_20indicators_11',['Mix-In Classes for Error Indicators',['../group__jkqtplotter__basegraphserrors.html',1,'']]],
  ['classes_20for_20graphs_12',['Mix-in classes for Graphs',['../group__jkqtplotter__mixins.html',1,'']]],
  ['classes_20for_20image_20drawing_13',['Tool Functions &amp; Classes for Image Drawing',['../group__jkqtplotter__imagelots__tools.html',1,'']]],
  ['classes_20for_20jkqtfastplotter_14',['Tool DEPRECATED: Functions, Enums, Classes for JKQTFastPlotter',['../group__jkqtfastplotter__tools.html',1,'']]],
  ['classes_20for_20styling_20general_20graphs_15',['Mix-In Classes for Styling General Graphs',['../group__jkqtplotter__basegraphs__stylemixins.html',1,'']]],
  ['classes_20for_20styling_20specialized_20graphs_20boxplots_20etz_16',['Mix-In Classes for Styling Specialized Graphs (Boxplots etz.)',['../group__jkqtplotter__specialgraphs__stylemixins.html',1,'']]],
  ['code_20structuring_20tools_17',['Code Structuring Tools',['../group__jkqtptools__codestructuring.html',1,'']]],
  ['comboboxes_20for_20properties_20of_20jkqtbaseplotter_20jkqtplotter_18',['Comboboxes for Properties of JKQTBasePlotter/JKQTPlotter',['../group__jkqtpcomboboxes.html',1,'']]],
  ['computations_19',['Statistical Computations',['../group__jkqtptools__math__statistics.html',1,'']]],
  ['concrete_20graph_20classes_20',['Concrete Graph Classes',['../group__jkqtplotter__concretegraphs.html',1,'']]],
  ['concurrency_21',['Tools, Templates and Classes for Concurrency',['../group__jkqtptools__concurrency.html',1,'']]],
  ['considerations_20when_20setting_20up_20plots_22',['Performance Considerations when Setting up Plots',['../group__jkqtplotter__general__usage__speedplotsetup.html',1,'']]],
  ['construction_23',['Conventions: Naming and Plot Construction',['../group__jkqtplotter__naming.html',1,'']]],
  ['contour_20graphs_20based_20on_20image_20data_24',['Contour Graphs (based on Image Data)',['../group__jkqtplotter__imagelots__contour.html',1,'']]],
  ['conventions_3a_20naming_20and_20plot_20construction_25',['Conventions: Naming and Plot Construction',['../group__jkqtplotter__naming.html',1,'']]],
  ['conversion_20functions_26',['String(-Conversion) Functions',['../group__jkqtptools__string.html',1,'']]],
  ['coordinate_20axes_27',['Coordinate Axes',['../group__jkqtplotter__general__basicplotelements__coordinateaxes.html',1,'']]],
  ['css_20parsing_20tools_28',['CSS Parsing Tools',['../group__jkqtptools__css.html',1,'']]]
];
