var searchData=
[
  ['charts_0',['Impulse-Charts',['../group__jkqtplotter__sticks.html',1,'']]],
  ['charts_20parametrized_20scatter_20graphs_1',['Bubble Charts / Parametrized Scatter Graphs',['../group__jkqtplotter__linesymbolgraphs__param.html',1,'']]],
  ['cimg_20interfaceing_20tools_2',['CImg Interfaceing Tools',['../group__jkqtpinterfacecimg.html',1,'']]],
  ['clasess_3',['Tools around Qt&apos;s clasess',['../group__jkqtptools__qt.html',1,'']]],
  ['class_4',['Class',['../group__jkqtplotter.html',1,'JKQTPlotter: Qt based Scientific Plotter Class'],['../group__jkqtplotter__general__usage__jkqtbaseplotter.html',1,'Usage of JKQTBasePlotter Non-Visible Class']]],
  ['class_5',['DEPRECATED: JKQTFastPlotter: Speed-Optimized Plotter class',['../group__jkqtfastplotter.html',1,'']]],
  ['class_20function_20documentation_6',['Type/Class/Function Documentation',['../group__jkqtplotter__classdoc.html',1,'']]],
  ['class_20jkqtmathtext_7',['Math Renderer Class (JKQTMathText)',['../group__jkqtmathtext__render.html',1,'']]],
  ['class_20plotter_20widget_8',['Plotter Class &amp;amp; Plotter Widget',['../group__jkqtpplotterclasses.html',1,'']]],
  ['classes_9',['Classes',['../group__jkqtplotter__concretegraphs.html',1,'Concrete Graph Classes'],['../group__jkqtpdatastorage__classes.html',1,'Data Storage Classes'],['../group__jkqtmathtext__parser.html',1,'Math Markup Parser Classes'],['../group__jkqtplotter__elements.html',1,'Plot Element Classes'],['../group__jkqtpplotter__styling__classes.html',1,'Styling System Classes']]],
  ['classes_20and_20functions_10',['Support Classes and Functions',['../group__jkqtpplottersupprt.html',1,'']]],
  ['classes_20for_20concurrency_11',['Tools, Templates and Classes for Concurrency',['../group__jkqtptools__concurrency.html',1,'']]],
  ['classes_20for_20error_20indicators_12',['Mix-In Classes for Error Indicators',['../group__jkqtplotter__basegraphserrors.html',1,'']]],
  ['classes_20for_20graphs_13',['Mix-in classes for Graphs',['../group__jkqtplotter__mixins.html',1,'']]],
  ['classes_20for_20image_20drawing_14',['Tool Functions &amp;amp; Classes for Image Drawing',['../group__jkqtplotter__imagelots__tools.html',1,'']]],
  ['classes_20for_20jkqtfastplotter_15',['Tool DEPRECATED: Functions, Enums, Classes for JKQTFastPlotter',['../group__jkqtfastplotter__tools.html',1,'']]],
  ['classes_20for_20styling_20general_20graphs_16',['Mix-In Classes for Styling General Graphs',['../group__jkqtplotter__basegraphs__stylemixins.html',1,'']]],
  ['classes_20for_20styling_20specialized_20graphs_20boxplots_20etz_17',['Mix-In Classes for Styling Specialized Graphs (Boxplots etz.)',['../group__jkqtplotter__specialgraphs__stylemixins.html',1,'']]],
  ['code_20structuring_20tools_18',['Code Structuring Tools',['../group__jkqtptools__codestructuring.html',1,'']]],
  ['comboboxes_20for_20properties_20of_20jkqtbaseplotter_20jkqtplotter_19',['Comboboxes for Properties of JKQTBasePlotter/JKQTPlotter',['../group__jkqtpcomboboxes.html',1,'']]],
  ['computations_20',['Statistical Computations',['../group__jkqtptools__math__statistics.html',1,'']]],
  ['concrete_20graph_20classes_21',['Concrete Graph Classes',['../group__jkqtplotter__concretegraphs.html',1,'']]],
  ['concurrency_22',['Tools, Templates and Classes for Concurrency',['../group__jkqtptools__concurrency.html',1,'']]],
  ['considerations_20when_20setting_20up_20plots_23',['Performance Considerations when Setting up Plots',['../group__jkqtplotter__general__usage__speedplotsetup.html',1,'']]],
  ['construction_24',['Conventions: Naming and Plot Construction',['../group__jkqtplotter__naming.html',1,'']]],
  ['contour_20graphs_20based_20on_20image_20data_25',['Contour Graphs (based on Image Data)',['../group__jkqtplotter__imagelots__contour.html',1,'']]],
  ['conventions_3a_20naming_20and_20plot_20construction_26',['Conventions: Naming and Plot Construction',['../group__jkqtplotter__naming.html',1,'']]],
  ['conversion_20functions_27',['String(-Conversion) Functions',['../group__jkqtptools__string.html',1,'']]],
  ['coordinate_20axes_28',['Coordinate Axes',['../group__jkqtplotter__general__basicplotelements__coordinateaxes.html',1,'']]],
  ['css_20parsing_20tools_29',['CSS Parsing Tools',['../group__jkqtptools__css.html',1,'']]]
];
