var searchData=
[
  ['s_20clasess_0',['Tools around Qt&apos;s clasess',['../group__jkqtptools__qt.html',1,'']]],
  ['scatter_20graphs_1',['Scatter Graphs',['../group__jkqtplotter__linesymbolgraphs__param.html',1,'Bubble Charts / Parametrized Scatter Graphs'],['../group__jkqtplotter__linesymbolgraphs__scatter.html',1,'Scatter Graphs']]],
  ['scientific_20plotter_20class_2',['JKQTPlotter: Qt based Scientific Plotter Class',['../group__jkqtplotter.html',1,'']]],
  ['setting_20up_20plots_3',['Performance Considerations when Setting up Plots',['../group__jkqtplotter__general__usage__speedplotsetup.html',1,'']]],
  ['sorting_4',['General Algorithms (Sorting ...)',['../group__jkqtptools__algorithms.html',1,'']]],
  ['special_20math_20and_20statistics_20utilities_5',['JKQTMath: Special Math and Statistics Utilities',['../group__jkqtmath.html',1,'']]],
  ['special_20qicon_20generation_6',['Special QIcon generation',['../group__jkqtptools__icons.html',1,'']]],
  ['specialized_20graphs_20boxplots_20etz_7',['Mix-In Classes for Styling Specialized Graphs (Boxplots etz.)',['../group__jkqtplotter__specialgraphs__stylemixins.html',1,'']]],
  ['speed_20optimized_20plotter_20class_8',['DEPRECATED: JKQTFastPlotter: Speed-Optimized Plotter class',['../group__jkqtfastplotter.html',1,'']]],
  ['statistical_20computations_9',['Statistical Computations',['../group__jkqtptools__math__statistics.html',1,'']]],
  ['statistical_20graphs_20e_20g_20boxplots_10',['Statistical Graphs (e.g. Boxplots ...)',['../group__jkqtplotter__statgraphs.html',1,'']]],
  ['statistics_11',['statistics',['../group__jkqtptools__math__statistics__basic.html',1,'Basic statistics'],['../group__jkqtptools__math__statistics__grouped.html',1,'Grouped statistics']]],
  ['statistics_20to_20plot_20adaptors_12',['Statistics To Plot Adaptors',['../group__jkqtptools__math__statistics__adaptors.html',1,'']]],
  ['statistics_20utilities_13',['JKQTMath: Special Math and Statistics Utilities',['../group__jkqtmath.html',1,'']]],
  ['storage_14',['Data Management and -storage',['../group__jkqtpdatastorage.html',1,'']]],
  ['storage_20classes_15',['Data Storage Classes',['../group__jkqtpdatastorage__classes.html',1,'']]],
  ['string_20conversion_20functions_16',['String(-Conversion) Functions',['../group__jkqtptools__string.html',1,'']]],
  ['structuring_20tools_17',['Code Structuring Tools',['../group__jkqtptools__codestructuring.html',1,'']]],
  ['styling_20general_20graphs_18',['Mix-In Classes for Styling General Graphs',['../group__jkqtplotter__basegraphs__stylemixins.html',1,'']]],
  ['styling_20specialized_20graphs_20boxplots_20etz_19',['Mix-In Classes for Styling Specialized Graphs (Boxplots etz.)',['../group__jkqtplotter__specialgraphs__stylemixins.html',1,'']]],
  ['styling_20system_20',['Styling System',['../group__jkqtpplotter__styling.html',1,'']]],
  ['styling_20system_20classes_21',['Styling System Classes',['../group__jkqtpplotter__styling__classes.html',1,'']]],
  ['subset_22',['Supported LaTeX-Subset',['../group__jkqtmathtext__supportedlatex.html',1,'']]],
  ['support_20classes_20and_20functions_23',['Support Classes and Functions',['../group__jkqtpplottersupprt.html',1,'']]],
  ['supported_20latex_20subset_24',['Supported LaTeX-Subset',['../group__jkqtmathtext__supportedlatex.html',1,'']]],
  ['supported_20latex_20symbols_25',['Supported LaTeX-Symbols',['../group__jkqtmathtext__supportedlatexsymbols.html',1,'']]],
  ['supported_20markup_20languages_26',['Supported Markup Languages',['../group__jkqtmathtext__general__languages.html',1,'']]],
  ['symbol_20graphs_27',['Line/Symbol Graphs',['../group__jkqtplotter__linesymbolgraphs.html',1,'']]],
  ['symbols_28',['Supported LaTeX-Symbols',['../group__jkqtmathtext__supportedlatexsymbols.html',1,'']]],
  ['system_29',['Styling System',['../group__jkqtpplotter__styling.html',1,'']]],
  ['system_20classes_30',['Styling System Classes',['../group__jkqtpplotter__styling__classes.html',1,'']]]
];
