var searchData=
[
  ['main_20features_0',['Main Features',['../index.html#jkqtp_main_features',1,'']]],
  ['main_20program_20of_20the_20example_20gui_1',['Main Program of the Example (GUI)',['../_j_k_q_t_plotter_image_plot_user_palette.html#autotoc_md82',1,'']]],
  ['major_20coordinate_20axes_2',['Major Coordinate Axes',['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_grids_baseplotter_majoraxes',1,'']]],
  ['major_20rework_20of_20the_20library_3',['v2019.11: Major rework of the library',['../page_whatsnew.html#page_whatsnew_V2019_11',1,'']]],
  ['management_4',['Management',['../class_j_k_q_t_p_datastore.html#jkqtpdatastore_column_management',1,'Column Management'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md23',1,'JKQTPDatastore-internal Data Management']]],
  ['management_20statistics_5',['Examples for Data Management &amp;amp; Statistics',['../example_tutorial_projects.html#jkqtp_extut_datamanagement',1,'']]],
  ['mandelbrot_20set_20explorer_6',['Example (JKQTPlotter): Mandelbrot Set Explorer',['../_j_k_q_t_plotter_mandelbrot.html',1,'exampleTutorialProjects']]],
  ['map_20into_20a_20jkqtpdatastore_7',['Copy Data from a Map into a JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md19',1,'']]],
  ['marginal_20statistics_8',['Marginal Statistics',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html#autotoc_md58',1,'']]],
  ['master_9',['trunk/master',['../page_whatsnew.html#page_whatsnew_TRUNK',1,'']]],
  ['math_20and_20text_20mode_10',['Switch between Math- and Text-Mode',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXMathTextMode',1,'']]],
  ['math_20fonts_20for_20jkqtmathtext_11',['Fira Math Fonts for JKQTMathText',['../licensepage.html#extlicense_firamath',1,'']]],
  ['math_20image_20plot_12',['Example (JKQTPlotter): Simple math image plot',['../_j_k_q_t_plotter_image_plot.html',1,'exampleTutorialProjects']]],
  ['math_20image_20plot_20showin_20a_201_20channel_20cimg_20image_13',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel CImg image',['../_j_k_q_t_plotter_image_plot_c_img.html',1,'exampleTutorialProjects']]],
  ['math_20image_20plot_20showin_20a_201_20channel_20opencv_20cv_3a_3amat_14',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_open_c_v.html',1,'exampleTutorialProjects']]],
  ['math_20image_20plot_20showing_20a_203_20channel_20cimg_20image_15',['Example (JKQTPlotter): Simple math image plot, showing a 3-channel CImg image',['../_j_k_q_t_plotter_image_plot_r_g_b_c_img.html',1,'exampleTutorialProjects']]],
  ['math_20image_20plot_20with_20modifier_20datat_16',['Example (JKQTPlotter): Simple math image plot with modifier datat',['../_j_k_q_t_plotter_image_plot_modifier.html',1,'exampleTutorialProjects']]],
  ['math_20image_20plot_20without_20use_20of_20central_20jkqtdatastore_17',['Example (JKQTPlotter): Simple math image plot without use of central JKQTdatastore',['../_j_k_q_t_plotter_image_plot_no_datastore.html',1,'exampleTutorialProjects']]],
  ['math_20operators_18',['Big Math Operators',['../group__jkqtmathtext__supportedlatexsymbols.html#jkqtmathtext_supportedlatexsymbols_bigmathop',1,'']]],
  ['math_20rgb_20cmy_20image_20plot_19',['Example (JKQTPlotter): Simple Math RGB/CMY Image Plot',['../_j_k_q_t_plotter_r_g_b_image_plot.html',1,'exampleTutorialProjects']]],
  ['math_20special_20functions_20',['Math Special Functions',['../group__jkqtmathtext__supportedlatexsymbols.html#jkqtmathtext_supportedlatexsymbols_mathspecialfunctions',1,'']]],
  ['mathematical_20constructs_21',['Supported Mathematical Constructs',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXMathSupport',1,'']]],
  ['mathematical_20curves_20as_20line_20graphs_22',['Example (JKQTPlotter): Plotting Parametric Mathematical Curves as Line Graphs',['../_j_k_q_t_plotter_eval_curves.html',1,'exampleTutorialProjects']]],
  ['mathematical_20functions_20as_20line_20graphs_23',['Mathematical Functions as Line Graphs',['../_j_k_q_t_plotter_function_plots.html',1,'Example (JKQTPlotter): Plotting Mathematical Functions as Line Graphs'],['../_j_k_q_t_plotter_parsed_function_plot.html',1,'Example (JKQTPlotter): Plotting Parsed Mathematical Functions as Line Graphs']]],
  ['matrix_20array_20type_20instructions_24',['Matrix/Array Type Instructions',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXMatrix',1,'']]],
  ['measurement_20tool_25',['Ruler/Measurement Tool',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md106',1,'']]],
  ['menu_26',['Menu',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md115',1,'Special Context Menu'],['../_j_k_q_t_plotter_user_interaction.html#autotoc_md114',1,'Standard Context Menu'],['../_j_k_q_t_plotter_user_interaction.html#autotoc_md101',1,'Switching Graph Visibility via Context Menu']]],
  ['menu_20of_20jkqtplotter_27',['Menu of JKQTPlotter',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_CONTEXTMENU',1,'Context Menu of JKQTPlotter'],['../class_j_k_q_t_plotter.html#JKQTPLOTTER_SPECIALCONTEXTMENU',1,'Special (User-Defined) Context Menu of JKQTPlotter']]],
  ['menus_28',['Context Menus',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md113',1,'']]],
  ['minor_20modifications_20final_20quickfit3_20compatible_20version_29',['v2018.08: Minor Modifications (Final QuickFit3-compatible Version)',['../page_whatsnew.html#page_whatsnew_V2018_08',1,'']]],
  ['mix_20in_20classes_20for_20graphs_30',['Mix-In Classes for Graphs',['../group__jkqtplotter__graphsgroup__classstructure.html#jkqtplotter_graphsgroup_classstructure_mixins',1,'']]],
  ['mode_31',['Mode',['../_j_k_q_t_plotter_barcharts_functor_filling.html',1,'Example (JKQTPlotter): Barchart With Functor Fill-Mode'],['../_j_k_q_t_plotter_barcharts_two_color_filling.html',1,'Example (JKQTPlotter): Barchart With Two-Color Fill-Mode'],['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXMathTextMode',1,'Switch between Math- and Text-Mode']]],
  ['models_32',['Linearizable Regression Models',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html#autotoc_md45',1,'']]],
  ['modes_33',['Draw Modes',['../class_j_k_q_t_p_geometric_plot_element.html#JKQTPGeometricPlotElement_DrawMode',1,'']]],
  ['modifications_20final_20quickfit3_20compatible_20version_34',['v2018.08: Minor Modifications (Final QuickFit3-compatible Version)',['../page_whatsnew.html#page_whatsnew_V2018_08',1,'']]],
  ['modifier_20datat_35',['Example (JKQTPlotter): Simple math image plot with modifier datat',['../_j_k_q_t_plotter_image_plot_modifier.html',1,'exampleTutorialProjects']]],
  ['modify_20column_20contents_36',['Modify Column Contents',['../class_j_k_q_t_p_datastore.html#jkqtpdatastore_column_management_modify',1,'']]],
  ['more_20complex_20examples_37',['More Complex Examples',['../example_tutorial_projects.html#jkqtp_extut_complexexamples',1,'']]],
  ['mouse_38',['Mouse',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSEDRAG',1,'Actions When Dragging the Mouse'],['../_j_k_q_t_plotter_user_interaction.html#autotoc_md105',1,'Zooming with the Mouse']]],
  ['mouse_20buttons_39',['Actions After (Double-)Clicks on the Mouse Buttons',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSECLICK',1,'']]],
  ['mouse_20interaction_20in_20jkqtplotter_40',['Mouse-Interaction in JKQTPlotter',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION',1,'']]],
  ['mouse_20move_20signaling_20and_20actions_41',['Mouse Move Signaling and Actions',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSEMOVE',1,'']]],
  ['mouse_20position_20display_42',['Mouse Position Display',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md103',1,'']]],
  ['mouse_20wheel_20event_20occurs_43',['Actions When a Mouse Wheel Event Occurs',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSEWHEEL',1,'']]],
  ['move_20signaling_20and_20actions_44',['Mouse Move Signaling and Actions',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSEMOVE',1,'']]],
  ['msvc_45',['Configuring&amp;amp;Building with Visual Studio/MSVC',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_VSTUDIO',1,'']]],
  ['multi_20line_20text_46',['Environments for Multi-line text',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXTextAlignment',1,'']]],
  ['multi_20threaded_20parallel_20plotting_47',['Example (JKQTPlotter): Multi-Threaded (Parallel) Plotting',['../_j_k_q_t_plotter_multi_threaded.html',1,'exampleTutorialProjects']]]
];
