var searchData=
[
  ['_3a_201_20dimensional_20group_20statistics_20with_20jkqtpdatastore_0',['Tutorial (JKQTPDatastore): 1-Dimensional Group Statistics with JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html',1,'exampleTutorialProjects']]],
  ['_3a_20a_20simple_20usage_20example_1',['Example (JKQTMathText): A simple usage example',['../_j_k_q_t_math_text_simple_example.html',1,'exampleTutorialProjects']]],
  ['_3a_20a_20test_20application_2',['Example (JKQTMathText): A test application',['../_j_k_q_t_math_text_test_app.html',1,'exampleTutorialProjects']]],
  ['_3a_20advanced_201_20dimensional_20statistics_20with_20jkqtpdatastore_3',['Tutorial (JKQTPDatastore): Advanced 1-Dimensional Statistics with JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html',1,'exampleTutorialProjects']]],
  ['_3a_20advanced_202_20dimensional_20statistics_20with_20jkqtpdatastore_4',['Tutorial (JKQTPDatastore): Advanced 2-Dimensional Statistics with JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html',1,'exampleTutorialProjects']]],
  ['_3a_20advanced_20line_20and_20fill_20styling_5',['Example (JKQTPlotter): Advanced Line and Fill Styling',['../_j_k_q_t_plotter_advanced_line_and_fill_styling.html',1,'exampleTutorialProjects']]],
  ['_3a_20barchart_20with_20custom_20draw_20functor_6',['Example (JKQTPlotter): Barchart With Custom Draw Functor',['../_j_k_q_t_plotter_barcharts_custom_draw_functor.html',1,'exampleTutorialProjects']]],
  ['_3a_20barchart_20with_20error_20bars_7',['Example (JKQTPlotter): Barchart With Error Bars',['../_j_k_q_t_plotter_barcharts_error_bars.html',1,'exampleTutorialProjects']]],
  ['_3a_20barchart_20with_20functor_20fill_20mode_8',['Example (JKQTPlotter): Barchart With Functor Fill-Mode',['../_j_k_q_t_plotter_barcharts_functor_filling.html',1,'exampleTutorialProjects']]],
  ['_3a_20barchart_20with_20two_20color_20fill_20mode_9',['Example (JKQTPlotter): Barchart With Two-Color Fill-Mode',['../_j_k_q_t_plotter_barcharts_two_color_filling.html',1,'exampleTutorialProjects']]],
  ['_3a_20basic_20usage_20of_20jkqtpdatastore_10',['Tutorial (JKQTPDatastore): Basic Usage of JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html',1,'exampleTutorialProjects']]],
  ['_3a_20boxplots_11',['Example (JKQTPlotter): Boxplots',['../_j_k_q_t_plotter_boxplots_graphs.html',1,'exampleTutorialProjects']]],
  ['_3a_20cmake_20example_12',['Example (JKQTPlotter): CMake Example',['../_j_k_q_t_c_make_link_example.html',1,'exampleTutorialProjects']]],
  ['_3a_20cmake_20fetchcontent_20example_13',['Example (JKQTPlotter): CMake FetchContent Example',['../_j_k_q_t_c_make_fetch_content_example.html',1,'exampleTutorialProjects']]],
  ['_3a_20command_20line_20utility_20jkqtmathtext_5frender_14',['Tool (JKQTMathText): Command-Line Utility jkqtmathtext_render',['../_j_k_q_t_math_text_render_cmd_line_tool.html',1,'exampleTutorialProjects']]],
  ['_3a_20command_20line_20utility_20jkqtplotter_5fdoc_5fimagegenerator_15',['Tool (JKQTMathText): Command-Line Utility jkqtplotter_doc_imagegenerator',['../_j_k_q_t_plotter_doc_image_render_cmd_line_tool.html',1,'exampleTutorialProjects']]],
  ['_3a_20contour_20plots_16',['Example (JKQTPlotter): Contour Plots',['../_j_k_q_t_plotter_contour_plot.html',1,'exampleTutorialProjects']]],
  ['_3a_20date_20time_20axes_17',['Example (JKQTPlotter): Date/Time Axes',['../_j_k_q_t_plotter_date_time_axes.html',1,'exampleTutorialProjects']]],
  ['_3a_20different_20types_20of_20errorindicators_18',['Example (JKQTPlotter): Different Types of Errorindicators',['../_j_k_q_t_plotter_error_bar_styles.html',1,'exampleTutorialProjects']]],
  ['_3a_20draw_20an_20artistic_20image_20with_20a_20parametrized_20scatter_20graph_19',['Example (JKQTPlotter): Draw an Artistic Image with a Parametrized Scatter Graph',['../_j_k_q_t_plotter_param_scatter_image.html',1,'exampleTutorialProjects']]],
  ['_3a_20filled_20curve_20plots_20',['Example (JKQTPlotter): Filled Curve Plots',['../_j_k_q_t_plotter_filled_graphs.html',1,'exampleTutorialProjects']]],
  ['_3a_20filled_20graphs_20with_20error_20indicators_21',['Example (JKQTPlotter): Filled Graphs with Error Indicators',['../_j_k_q_t_plotter_filled_graphs_error_bars.html',1,'exampleTutorialProjects']]],
  ['_3a_20financial_20chart_20candlestick_20ohlc_20example_22',['Example (JKQTPlotter): Financial Chart (Candlestick/OHLC) Example',['../_j_k_q_t_plotter_financial_chart_example.html',1,'exampleTutorialProjects']]],
  ['_3a_20generating_20demo_20plots_20of_20geometric_20objects_20for_20documentation_23',['Example (JKQTPlotter): Generating Demo-Plots of Geometric Objects for Documentation',['../_j_k_q_t_plotter_geometric_graphs_simple.html',1,'exampleTutorialProjects']]],
  ['_3a_20image_20plots_20with_20custom_20palettes_24',['Example (JKQTPlotter): Image Plots with Custom Palettes',['../_j_k_q_t_plotter_image_plot_user_palette.html',1,'exampleTutorialProjects']]],
  ['_3a_20iterator_20based_20usage_20of_20jkqtpdatastore_25',['Tutorial (JKQTPDatastore): Iterator-Based usage of JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html',1,'exampleTutorialProjects']]],
  ['_3a_20laying_20out_20several_20plots_26',['Example (JKQTPlotter): Laying out Several Plots',['../_j_k_q_t_plotter_multi_plot_layout.html',1,'exampleTutorialProjects']]],
  ['_3a_20line_20graph_20with_20different_20symbols_20and_20line_20styles_27',['Example (JKQTPlotter): Line Graph with Different Symbols and Line Styles',['../_j_k_q_t_plotter_symbols_and_styles.html',1,'exampleTutorialProjects']]],
  ['_3a_20line_20graph_20with_20logarithmic_20y_20axis_28',['Example (JKQTPlotter): Line Graph with Logarithmic y-axis',['../_j_k_q_t_plotter_log_axes.html',1,'exampleTutorialProjects']]],
  ['_3a_20mandelbrot_20set_20explorer_29',['Example (JKQTPlotter): Mandelbrot Set Explorer',['../_j_k_q_t_plotter_mandelbrot.html',1,'exampleTutorialProjects']]],
  ['_3a_20multi_20threaded_20parallel_20plotting_30',['Example (JKQTPlotter): Multi-Threaded (Parallel) Plotting',['../_j_k_q_t_plotter_multi_threaded.html',1,'exampleTutorialProjects']]],
  ['_3a_20parametrized_20scatter_20graph_20with_20custom_20symbols_31',['Example (JKQTPlotter): Parametrized Scatter-graph with custom symbols',['../_j_k_q_t_plotterparamscatter_custom_symbol.html',1,'exampleTutorialProjects']]],
  ['_3a_20plot_20with_20axes_20through_20origin_32',['Example (JKQTPlotter): Plot With Axes through Origin',['../_j_k_q_t_plotter_geometric_coordinate_axis0.html',1,'exampleTutorialProjects']]],
  ['_3a_20plotting_20a_20statistical_20distribution_20of_20data_33',['Example (JKQTPlotter): Plotting a Statistical Distribution of Data',['../_j_k_q_t_plotter_distribution_plot.html',1,'exampleTutorialProjects']]],
  ['_3a_20plotting_20arrows_34',['Example (JKQTPlotter): Plotting Arrows',['../_j_k_q_t_plotter_geometric_arrows.html',1,'exampleTutorialProjects']]],
  ['_3a_20plotting_20bezier_20curves_35',['Example (JKQTPlotter): Plotting Bezier Curves',['../_j_k_q_t_plotter_geometric_bezier.html',1,'exampleTutorialProjects']]],
  ['_3a_20plotting_20geometric_20objects_36',['Example (JKQTPlotter): Plotting Geometric Objects',['../_j_k_q_t_plotter_geometric_graphs.html',1,'exampleTutorialProjects']]],
  ['_3a_20plotting_20mathematical_20functions_20as_20line_20graphs_37',['Example (JKQTPlotter): Plotting Mathematical Functions as Line Graphs',['../_j_k_q_t_plotter_function_plots.html',1,'exampleTutorialProjects']]],
  ['_3a_20plotting_20parametric_20curves_38',['Example (JKQTPlotter): Plotting Parametric Curves',['../_j_k_q_t_plotter_parametric_curves.html',1,'exampleTutorialProjects']]],
  ['_3a_20plotting_20parametric_20mathematical_20curves_20as_20line_20graphs_39',['Example (JKQTPlotter): Plotting Parametric Mathematical Curves as Line Graphs',['../_j_k_q_t_plotter_eval_curves.html',1,'exampleTutorialProjects']]],
  ['_3a_20plotting_20parsed_20mathematical_20functions_20as_20line_20graphs_40',['Example (JKQTPlotter): Plotting Parsed Mathematical Functions as Line Graphs',['../_j_k_q_t_plotter_parsed_function_plot.html',1,'exampleTutorialProjects']]],
  ['_3a_20qimage_20as_20a_20graph_41',['Example (JKQTPlotter): QImage as a Graph',['../_j_k_q_t_plotter_image_plot_q_image_r_g_b.html',1,'exampleTutorialProjects']]],
  ['_3a_20regression_20analysis_20with_20the_20statistics_20library_42',['Tutorial (JKQTPDatastore): Regression Analysis (with the Statistics Library)',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html',1,'exampleTutorialProjects']]],
  ['_3a_20scatter_20graph_20with_20custom_20symbols_43',['Example (JKQTPlotter): Scatter-graph with custom symbols',['../_j_k_q_t_plotterscatter_custom_symbol.html',1,'exampleTutorialProjects']]],
  ['_3a_20scatter_20graph_20with_20parametrized_20symbols_20colors_44',['Example (JKQTPlotter): Scatter Graph with Parametrized Symbols/Colors',['../_j_k_q_t_plotter_param_scatter.html',1,'exampleTutorialProjects']]],
  ['_3a_20secondary_20axes_45',['Example (JKQTPlotter): Secondary Axes',['../_j_k_q_t_plotter_secondary_axes.html',1,'exampleTutorialProjects']]],
  ['_3a_20simple_20barchart_46',['Example (JKQTPlotter): Simple barchart',['../_j_k_q_t_plotter_barcharts.html',1,'exampleTutorialProjects']]],
  ['_3a_20simple_20graph_20labels_20example_47',['Example (JKQTPlotter): Simple Graph Labels Example',['../_j_k_q_t_plotter_graph_labels_example.html',1,'exampleTutorialProjects']]],
  ['_3a_20simple_20impulse_20plots_48',['Example (JKQTPlotter): Simple impulse plots',['../_j_k_q_t_plotter_impulse_plots.html',1,'exampleTutorialProjects']]],
  ['_3a_20simple_20line_20graph_20with_20error_20bars_49',['Example (JKQTPlotter): Simple line-graph with error bars',['../_j_k_q_t_plotter_symbols_errors.html',1,'exampleTutorialProjects']]],
  ['_3a_20simple_20line_20graph_20with_20live_20data_20speed_20test_50',['Example (JKQTPlotter): Simple line-graph with live-data (speed test)',['../_j_k_q_t_plotter_speed_test.html',1,'exampleTutorialProjects']]],
  ['_3a_20simple_20math_20image_20plot_51',['Example (JKQTPlotter): Simple math image plot',['../_j_k_q_t_plotter_image_plot.html',1,'exampleTutorialProjects']]],
  ['_3a_20simple_20math_20image_20plot_20showin_20a_201_20channel_20cimg_20image_52',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel CImg image',['../_j_k_q_t_plotter_image_plot_c_img.html',1,'exampleTutorialProjects']]],
  ['_3a_20simple_20math_20image_20plot_20showin_20a_201_20channel_20opencv_20cv_3a_3amat_53',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_open_c_v.html',1,'exampleTutorialProjects']]],
  ['_3a_20simple_20math_20image_20plot_20showing_20a_203_20channel_20cimg_20image_54',['Example (JKQTPlotter): Simple math image plot, showing a 3-channel CImg image',['../_j_k_q_t_plotter_image_plot_r_g_b_c_img.html',1,'exampleTutorialProjects']]],
  ['_3a_20simple_20math_20image_20plot_20with_20modifier_20datat_55',['Example (JKQTPlotter): Simple math image plot with modifier datat',['../_j_k_q_t_plotter_image_plot_modifier.html',1,'exampleTutorialProjects']]],
  ['_3a_20simple_20math_20image_20plot_20without_20use_20of_20central_20jkqtdatastore_56',['Example (JKQTPlotter): Simple math image plot without use of central JKQTdatastore',['../_j_k_q_t_plotter_image_plot_no_datastore.html',1,'exampleTutorialProjects']]],
  ['_3a_20simple_20math_20rgb_20cmy_20image_20plot_57',['Example (JKQTPlotter): Simple Math RGB/CMY Image Plot',['../_j_k_q_t_plotter_r_g_b_image_plot.html',1,'exampleTutorialProjects']]],
  ['_3a_20simple_20rgb_20image_20plot_20showing_20a_203_20channel_20opencv_20cv_3a_3amat_58',['Example (JKQTPlotter): Simple RGB image plot, showing a 3-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_r_g_b_open_c_v.html',1,'exampleTutorialProjects']]],
  ['_3a_20simple_20stacked_20barchart_59',['Example (JKQTPlotter): Simple stacked barchart',['../_j_k_q_t_plotter_stacked_bar_chart.html',1,'exampleTutorialProjects']]],
  ['_3a_20step_20line_20plots_20in_20different_20styles_60',['Example (JKQTPlotter): Step Line Plots in Different Styles',['../_j_k_q_t_plotter_special_step_line_plot.html',1,'exampleTutorialProjects']]],
  ['_3a_20styling_20a_20jkqtplotter_61',['Tutorial (JKQTPlotter): Styling a JKQtPlotter',['../_j_k_q_t_plotter_styling.html',1,'exampleTutorialProjects']]],
  ['_3a_20styling_20different_20aspects_20of_20boxplots_62',['Example (JKQTPlotter): Styling different aspects of boxplots',['../_j_k_q_t_plotter_boxplot_styling.html',1,'exampleTutorialProjects']]],
  ['_3a_20user_20interactions_20in_20jkqtplotter_63',['Tutorial (JKQTPlotter): User-Interactions in JKQtPlotter',['../_j_k_q_t_plotter_user_interaction.html',1,'exampleTutorialProjects']]],
  ['_3a_20using_20a_20jkqtplotter_20inside_20a_20qt_20user_20interface_20designer_20ui_20file_64',['Tutorial (JKQTPlotter): Using a JKQTPlotter inside a Qt User Interface Designer (UI) File',['../_j_k_q_t_plotter_qt_creator.html',1,'exampleTutorialProjects']]],
  ['_3a_20using_20a_20qscrollbar_20together_20with_20jkqtplotter_65',['Example (JKQTPlotter): Using a QScrollbar together with JKQtPlotter',['../_j_k_q_t_plotter_u_i_scrollbar.html',1,'exampleTutorialProjects']]],
  ['_3a_20vector_20field_20plot_20example_66',[': Vector Field Plot Example',['../_j_k_q_t_p_parametrized_vector_field_graph_example.html',1,'Example (JKQTPlotter): Vector Field Plot Example'],['../_j_k_q_t_plotter_vector_field_example.html',1,'Example (JKQTPlotter): Vector Field Plot Example']]],
  ['_3a_20very_20simple_20line_20graph_67',['Example (JKQTPlotter): Very simple line-graph',['../_j_k_q_t_plotter_simple_test.html',1,'exampleTutorialProjects']]],
  ['_3a_20very_20simple_20scatter_20graph_68',['Example (JKQTPlotter): Very simple scatter-graph',['../_j_k_q_t_plotterscatter.html',1,'exampleTutorialProjects']]],
  ['_3a_20violin_20plots_69',['Example (JKQTPlotter): Violin Plots',['../_j_k_q_t_plotter_violinplot_graphs.html',1,'exampleTutorialProjects']]],
  ['_3a_20wiggle_20plots_70',['Example (JKQTPlotter): Wiggle Plots',['../_j_k_q_t_plotter_wiggle_plots.html',1,'exampleTutorialProjects']]]
];
