var searchData=
[
  ['back_20inserter_20for_20columns_0',['Back-Inserter for Columns',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md39',1,'']]],
  ['barchart_1',['Calculating Grouped Statistics for a Barchart',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md32',1,'']]],
  ['barchart_2',['barchart',['../_j_k_q_t_plotter_barcharts.html',1,'Example (JKQTPlotter): Simple barchart'],['../_j_k_q_t_plotter_stacked_bar_chart.html',1,'Example (JKQTPlotter): Simple stacked barchart']]],
  ['barchart_20with_20custom_20draw_20functor_3',['Example (JKQTPlotter): Barchart With Custom Draw Functor',['../_j_k_q_t_plotter_barcharts_custom_draw_functor.html',1,'exampleTutorialProjects']]],
  ['barchart_20with_20error_20bars_4',['Example (JKQTPlotter): Barchart With Error Bars',['../_j_k_q_t_plotter_barcharts_error_bars.html',1,'exampleTutorialProjects']]],
  ['barchart_20with_20functor_20fill_20mode_5',['Example (JKQTPlotter): Barchart With Functor Fill-Mode',['../_j_k_q_t_plotter_barcharts_functor_filling.html',1,'exampleTutorialProjects']]],
  ['barchart_20with_20two_20color_20fill_20mode_6',['Example (JKQTPlotter): Barchart With Two-Color Fill-Mode',['../_j_k_q_t_plotter_barcharts_two_color_filling.html',1,'exampleTutorialProjects']]],
  ['barcharts_7',['Generating a Dataset for Grouped Barcharts',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md31',1,'']]],
  ['barcharts_20boxplots_20from_20categorized_20data_8',['Barcharts &amp;amp; Boxplots from categorized data',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md30',1,'']]],
  ['bargraph_20drawing_9',['Custom Bargraph Drawing',['../class_j_k_q_t_p_bar_graph_base.html#JKQTPBarGraphBaseCustomStyling',1,'']]],
  ['bargraph_20styling_10',['Basic Bargraph Styling',['../class_j_k_q_t_p_bar_graph_base.html#JKQTPBarGraphBaseStyling',1,'']]],
  ['bargraphs_11',['Data-Dependent Styling of Bargraphs',['../class_j_k_q_t_p_bar_graph_base.html#JKQTPBarGraphBaseDataDependentFilling',1,'']]],
  ['bars_12',['Example (JKQTPlotter): Barchart With Error Bars',['../_j_k_q_t_plotter_barcharts_error_bars.html',1,'exampleTutorialProjects']]],
  ['bars_13',['Example (JKQTPlotter): Simple line-graph with error bars',['../_j_k_q_t_plotter_symbols_errors.html',1,'exampleTutorialProjects']]],
  ['based_20column_20data_20access_20to_20existing_20rows_14',['Iterator-based Column Data Access To Existing Rows',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md38',1,'']]],
  ['based_20usage_20of_20jkqtpdatastore_15',['Tutorial (JKQTPDatastore): Iterator-Based usage of JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html',1,'exampleTutorialProjects']]],
  ['basic_20bargraph_20styling_16',['Basic Bargraph Styling',['../class_j_k_q_t_p_bar_graph_base.html#JKQTPBarGraphBaseStyling',1,'']]],
  ['basic_20description_17',['Basic Description',['../_j_k_q_t_plotter_styling.html#autotoc_md93',1,'Basic Description'],['../_j_k_q_t_plotter_user_interaction.html#autotoc_md98',1,'Basic Description']]],
  ['basic_20statistics_18',['Basic Statistics',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md49',1,'']]],
  ['basic_20usage_20of_20jkqtpdatastore_19',['Tutorial (JKQTPDatastore): Basic Usage of JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html',1,'exampleTutorialProjects']]],
  ['basic_20usage_20of_20jkqtplotter_20',['Basic Usage of JKQTPlotter',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_BASICUSAGE',1,'']]],
  ['basics_21',['Basics',['../group__jkqtmathtext__renderingmodel.html#jkqtmathtext_renderingmodel_basics',1,'Basics'],['../_j_k_q_t_plotter_eval_curves.html#autotoc_md64',1,'Basics'],['../_j_k_q_t_plotter_function_plots.html#autotoc_md69',1,'Basics']]],
  ['basis_20for_20jkqtplotter_22',['JKQTBasePlotter as Basis for JKQTPlotter',['../class_j_k_q_t_base_plotter.html#jkqtplotter_usage_baseplotter_in_widget',1,'']]],
  ['between_20math_20and_20text_20mode_23',['Switch between Math- and Text-Mode',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXMathTextMode',1,'']]],
  ['between_20plots_24',['Grid Printing/Declaring Relations between Plots',['../class_j_k_q_t_base_plotter.html#JKQTBASEPLOTTER_SYNCMULTIPLOT_GRIDPRINT',1,'']]],
  ['bezier_20curves_25',['Example (JKQTPlotter): Plotting Bezier Curves',['../_j_k_q_t_plotter_geometric_bezier.html',1,'exampleTutorialProjects']]],
  ['big_20math_20operators_26',['Big Math Operators',['../group__jkqtmathtext__supportedlatexsymbols.html#jkqtmathtext_supportedlatexsymbols_bigmathop',1,'']]],
  ['black_20transparent_20wiggle_20plot_20using_20jkqtpfilledcurveygraph_20in_20a_20seismographic_20style_27',['Plot black/transparent wiggle plot using &lt;span class=&quot;tt&quot;&gt;JKQTPFilledCurveYGraph&lt;/span&gt; in a &quot;seismographic style&quot;',['../_j_k_q_t_plotter_wiggle_plots.html#autotoc_md119',1,'']]],
  ['blocks_28',['Linebreaks and Blocks',['../group__jkqtmathtext__renderingmodel.html#jkqtmathtext_renderingmodel_linebreaks',1,'']]],
  ['blue_20wiggle_20plot_20using_20jkqtpfilledcurvexgraph_29',['Plot red/blue wiggle plot using &lt;span class=&quot;tt&quot;&gt;JKQTPFilledCurveXGraph&lt;/span&gt;',['../_j_k_q_t_plotter_wiggle_plots.html#autotoc_md116',1,'']]],
  ['borders_30',['Plot Sizes &amp;amp; Borders',['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_plotsize',1,'']]],
  ['boxes_31',['Boxes',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXBoxes',1,'']]],
  ['boxplot_32',['Calculating Grouped Statistics for a Boxplot',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md33',1,'']]],
  ['boxplots_33',['Boxplots',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md50',1,'Boxplots'],['../_j_k_q_t_plotter_boxplots_graphs.html',1,'Example (JKQTPlotter): Boxplots'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md51',1,'Standard Boxplots']]],
  ['boxplots_34',['Example (JKQTPlotter): Styling different aspects of boxplots',['../_j_k_q_t_plotter_boxplot_styling.html',1,'exampleTutorialProjects']]],
  ['boxplots_20from_20categorized_20data_35',['Barcharts &amp;amp; Boxplots from categorized data',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md30',1,'']]],
  ['boxplots_20with_20outliers_36',['Boxplots with Outliers',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md52',1,'']]],
  ['braces_20parantheses_37',['Braces/Parantheses ...',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXBraces',1,'']]],
  ['bugfixes_38',['V4.0.0: Qt6 compatibility &amp;amp; diverse improvements + bugfixes',['../page_whatsnew.html#page_whatsnew_V4_0_0',1,'']]],
  ['build_39',['Using a CMake Build',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_USAGE',1,'']]],
  ['build_20instructions_40',['Build Instructions',['../page_buildinstructions.html',1,'']]],
  ['build_20palettes_20programmatically_41',['Build Palettes Programmatically',['../_j_k_q_t_plotter_image_plot_user_palette.html#autotoc_md80',1,'']]],
  ['build_20system_42',['Examples for CMake Build System',['../example_tutorial_projects.html#jkqtp_extut_cmake_build',1,'']]],
  ['build_20using_20cmake_43',['Build using CMake',['../page_buildinstructions__c_m_a_k_e.html',1,'page_buildinstructions']]],
  ['build_20using_20qmake_44',['DEPRECATED: Build using QMake',['../page_buildinstructions__q_m_a_k_e.html',1,'page_buildinstructions']]],
  ['build_20with_20cmake_45',['Build with CMake',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_CONFIG',1,'Configuring a Build with CMake'],['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_RUN',1,'Running a Build with CMake']]],
  ['building_46',['Generic Configuring&amp;amp;Building',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_MAKEFILE',1,'']]],
  ['building_20with_20visual_20studio_20msvc_47',['Configuring&amp;amp;Building with Visual Studio/MSVC',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_VSTUDIO',1,'']]],
  ['buttons_48',['Actions After (Double-)Clicks on the Mouse Buttons',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSECLICK',1,'']]],
  ['by_20side_49',['by side',['../class_j_k_q_t_p_financial_graph.html#JKQTPFinancialGraphSideBySide',1,'Several Financial Graphs side-by-side'],['../class_j_k_q_t_p_bar_graph_base.html#JKQTPBarGraphBase_SideBySide',1,'several JKQTPBarGraphBase side-by-side']]]
];
