var searchData=
[
  ['labels_20example_0',['Example (JKQTPlotter): Simple Graph Labels Example',['../_j_k_q_t_plotter_graph_labels_example.html',1,'exampleTutorialProjects']]],
  ['laying_20out_20several_20plots_1',['Example (JKQTPlotter): Laying out Several Plots',['../_j_k_q_t_plotter_multi_plot_layout.html',1,'exampleTutorialProjects']]],
  ['layout_20styling_2',['Examples for Layout &amp;amp; Styling',['../example_tutorial_projects.html#jkqtp_extut_guitoolslayout',1,'']]],
  ['legend_20styling_3',['Key/Legend Styling',['../class_j_k_q_t_p_base_key.html#JKQTPBaseKey_Styling',1,'']]],
  ['legends_4',['Graph Keys (Legends)',['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_key',1,'']]],
  ['letters_5',['Greek Letters',['../group__jkqtmathtext__supportedlatexsymbols.html#jkqtmathtext_supportedlatexsymbols_greek',1,'']]],
  ['lgpl_202_201_6',['JKQTPlotter/JKQTFastPlotter/JKQTMathText: LGPL &amp;gt;= 2.1',['../licensepage.html#licensesec',1,'']]],
  ['library_7',['Library',['../page_buildinstructions__q_m_a_k_e.html#page_buildinstructions_QMAKEDYNAMIC',1,'DEPRECATED: QMake Dynamic Library'],['../page_buildinstructions__q_m_a_k_e.html#page_buildinstructions_QMAKESTATIC',1,'DEPRECATED: QMake Static Library'],['../index.html',1,'JKQTPlotter - A Qt Plotting Library'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html',1,'Tutorial (JKQTPDatastore): Regression Analysis (with the Statistics Library)']]],
  ['library_8',['v2019.11: Major rework of the library',['../page_whatsnew.html#page_whatsnew_V2019_11',1,'']]],
  ['licenses_20of_203rd_20party_20products_20contained_20in_20jkqtplotter_9',['Licenses of 3rd Party Products Contained in JKQTPlotter',['../licensepage.html#extlicense_sec',1,'']]],
  ['licensing_20terms_20for_20jkqtplotter_10',['Licensing Terms for JKQTPlotter',['../licensepage.html',1,'']]],
  ['line_20and_20fill_20styling_11',['Example (JKQTPlotter): Advanced Line and Fill Styling',['../_j_k_q_t_plotter_advanced_line_and_fill_styling.html',1,'exampleTutorialProjects']]],
  ['line_20end_20decorators_20for_20jkqtpgeobeziercurve_12',['Line-End Decorators for JKQTPGeoBezierCurve',['../class_j_k_q_t_p_geo_bezier_curve.html#JKQTPGeoBezierCurveDecorators',1,'']]],
  ['line_20graph_13',['Example (JKQTPlotter): Very simple line-graph',['../_j_k_q_t_plotter_simple_test.html',1,'exampleTutorialProjects']]],
  ['line_20graph_20with_20different_20symbols_20and_20line_20styles_14',['Example (JKQTPlotter): Line Graph with Different Symbols and Line Styles',['../_j_k_q_t_plotter_symbols_and_styles.html',1,'exampleTutorialProjects']]],
  ['line_20graph_20with_20error_20bars_15',['Example (JKQTPlotter): Simple line-graph with error bars',['../_j_k_q_t_plotter_symbols_errors.html',1,'exampleTutorialProjects']]],
  ['line_20graph_20with_20live_20data_20speed_20test_16',['Example (JKQTPlotter): Simple line-graph with live-data (speed test)',['../_j_k_q_t_plotter_speed_test.html',1,'exampleTutorialProjects']]],
  ['line_20graph_20with_20logarithmic_20y_20axis_17',['Example (JKQTPlotter): Line Graph with Logarithmic y-axis',['../_j_k_q_t_plotter_log_axes.html',1,'exampleTutorialProjects']]],
  ['line_20graphs_18',['Line Graphs',['../_j_k_q_t_plotter_function_plots.html',1,'Example (JKQTPlotter): Plotting Mathematical Functions as Line Graphs'],['../_j_k_q_t_plotter_eval_curves.html',1,'Example (JKQTPlotter): Plotting Parametric Mathematical Curves as Line Graphs'],['../_j_k_q_t_plotter_parsed_function_plot.html',1,'Example (JKQTPlotter): Plotting Parsed Mathematical Functions as Line Graphs']]],
  ['line_20plots_20in_20different_20styles_19',['Example (JKQTPlotter): Step Line Plots in Different Styles',['../_j_k_q_t_plotter_special_step_line_plot.html',1,'exampleTutorialProjects']]],
  ['line_20styles_20',['Example (JKQTPlotter): Line Graph with Different Symbols and Line Styles',['../_j_k_q_t_plotter_symbols_and_styles.html',1,'exampleTutorialProjects']]],
  ['line_20text_21',['Environments for Multi-line text',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXTextAlignment',1,'']]],
  ['line_20utility_20jkqtmathtext_5frender_22',['Tool (JKQTMathText): Command-Line Utility jkqtmathtext_render',['../_j_k_q_t_math_text_render_cmd_line_tool.html',1,'exampleTutorialProjects']]],
  ['line_20utility_20jkqtplotter_5fdoc_5fimagegenerator_23',['Tool (JKQTMathText): Command-Line Utility jkqtplotter_doc_imagegenerator',['../_j_k_q_t_plotter_doc_image_render_cmd_line_tool.html',1,'exampleTutorialProjects']]],
  ['linear_20regression_24',['Linear Regression',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html#autotoc_md43',1,'Robust Linear Regression'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html#autotoc_md42',1,'Simple Linear Regression'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html#autotoc_md44',1,'Weighted Linear Regression']]],
  ['linearizable_20regression_20models_25',['Linearizable Regression Models',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html#autotoc_md45',1,'']]],
  ['linebreaks_20and_20blocks_26',['Linebreaks and Blocks',['../group__jkqtmathtext__renderingmodel.html#jkqtmathtext_renderingmodel_linebreaks',1,'']]],
  ['lines_27',['Lines',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md109',1,'']]],
  ['list_28',['Deprecated List',['../deprecated.html',1,'']]],
  ['list_20für_20future_20releases_20versions_29',['Todo List für Future Releases/Versions',['../page_todo.html',1,'']]],
  ['live_20data_20speed_20test_30',['Example (JKQTPlotter): Simple line-graph with live-data (speed test)',['../_j_k_q_t_plotter_speed_test.html',1,'exampleTutorialProjects']]],
  ['load_20palettes_20from_20files_31',['Load Palettes from Files',['../_j_k_q_t_plotter_image_plot_user_palette.html#autotoc_md81',1,'']]],
  ['logarithmic_20y_20axis_32',['Example (JKQTPlotter): Line Graph with Logarithmic y-axis',['../_j_k_q_t_plotter_log_axes.html',1,'exampleTutorialProjects']]]
];
