var searchData=
[
  ['s_20fetchcontent_20api_0',['Using JKQTPlotter with CMake&apos;s FetchContent-API',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_FETCHCONTENT',1,'']]],
  ['s_20new_20release_20notes_20versions_1',['What&apos;s New (Release Notes/Versions)',['../page_whatsnew.html',1,'']]],
  ['safety_20re_20entrancy_20guarantees_2',['Thread-Safety/Re-Entrancy Guarantees',['../class_j_k_q_t_math_text.html#JKQTMathTextUsageThreadSafety',1,'']]],
  ['saving_20and_20printing_20graphs_3',['Saving and Printing Graphs',['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_saveprint',1,'']]],
  ['saving_20exporting_4',['Printing, Saving &amp;amp; Exporting',['../class_j_k_q_t_base_plotter.html#jkqtbaseplotter_dataexport_print',1,'']]],
  ['scaling_5',['Axis Tick Units/Scaling',['../class_j_k_q_t_p_coordinate_axis.html#jkqtplotter_coordinateaxes_tickscaling',1,'']]],
  ['scatter_20graph_6',['Example (JKQTPlotter): Draw an Artistic Image with a Parametrized Scatter Graph',['../_j_k_q_t_plotter_param_scatter_image.html',1,'exampleTutorialProjects']]],
  ['scatter_20graph_7',['Example (JKQTPlotter): Very simple scatter-graph',['../_j_k_q_t_plotterscatter.html',1,'exampleTutorialProjects']]],
  ['scatter_20graph_20with_20custom_20symbols_8',['Scatter graph with custom symbols',['../_j_k_q_t_plotterparamscatter_custom_symbol.html',1,'Example (JKQTPlotter): Parametrized Scatter-graph with custom symbols'],['../_j_k_q_t_plotterscatter_custom_symbol.html',1,'Example (JKQTPlotter): Scatter-graph with custom symbols']]],
  ['scatter_20graph_20with_20parametrized_20symbols_20colors_9',['Example (JKQTPlotter): Scatter Graph with Parametrized Symbols/Colors',['../_j_k_q_t_plotter_param_scatter.html',1,'exampleTutorialProjects']]],
  ['scatter_20graphs_10',['Dataset for XY Scatter Graphs',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md35',1,'']]],
  ['scatter_20graphs_20with_20x_20y_20errors_20from_20categorized_20data_11',['(Scatter-)Graphs with X/Y-errors from Categorized Data',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md34',1,'']]],
  ['scope_12',['Scope',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md4',1,'Scope'],['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html#autotoc_md10',1,'Scope']]],
  ['screenshot_13',['Screenshot',['../_j_k_q_t_plotter_eval_curves.html#autotoc_md67',1,'Screenshot'],['../_j_k_q_t_plotter_function_plots.html#autotoc_md75',1,'Screenshot'],['../_j_k_q_t_plotter_geometric_arrows.html#autotoc_md79',1,'Screenshot']]],
  ['screenshot_20of_20the_20full_20program_14',['Screenshot of the full Program',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md37',1,'Screenshot of the full Program'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html#autotoc_md47',1,'Screenshot of the full Program'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md56',1,'Screenshot of the full Program'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html#autotoc_md61',1,'Screenshot of the full Program']]],
  ['secondary_20axes_15',['Example (JKQTPlotter): Secondary Axes',['../_j_k_q_t_plotter_secondary_axes.html',1,'exampleTutorialProjects']]],
  ['secondary_20coordinate_20axes_16',['Secondary Coordinate Axes',['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_grids_baseplotter_secondaryaxes',1,'']]],
  ['security_20policy_17',['Security Policy',['../md__s_e_c_u_r_i_t_y.html',1,'']]],
  ['seismographic_20style_18',['Plot black/transparent wiggle plot using &lt;span class=&quot;tt&quot;&gt;JKQTPFilledCurveYGraph&lt;/span&gt; in a &quot;seismographic style&quot;',['../_j_k_q_t_plotter_wiggle_plots.html#autotoc_md119',1,'']]],
  ['selection_19',['Font Selection',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXFontPropsFonts',1,'']]],
  ['set_20explorer_20',['Example (JKQTPlotter): Mandelbrot Set Explorer',['../_j_k_q_t_plotter_mandelbrot.html',1,'exampleTutorialProjects']]],
  ['sets_20of_20random_20numbers_21',['sets of random numbers',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md48',1,'Generating different sets of random numbers'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html#autotoc_md57',1,'Generating different sets of random numbers']]],
  ['setting_20up_20plots_22',['Performance Considerations when Setting up Plots',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_PERFORMACEWHILESETUP',1,'']]],
  ['settings_23',['Global/System-wide Settings',['../_j_k_q_t_plotter_styling.html#autotoc_md95',1,'']]],
  ['several_20financial_20graphs_20side_20by_20side_24',['Several Financial Graphs side-by-side',['../class_j_k_q_t_p_financial_graph.html#JKQTPFinancialGraphSideBySide',1,'']]],
  ['several_20jkqtpbargraphbase_20side_20by_20side_25',['several JKQTPBarGraphBase side-by-side',['../class_j_k_q_t_p_bar_graph_base.html#JKQTPBarGraphBase_SideBySide',1,'']]],
  ['several_20plots_26',['Several Plots',['../_j_k_q_t_plotter_multi_plot_layout.html',1,'Example (JKQTPlotter): Laying out Several Plots'],['../class_j_k_q_t_base_plotter.html#JKQTBASEPLOTTER_SYNCMULTIPLOT',1,'Synchronizing Several Plots'],['../class_j_k_q_t_plotter.html#JKQTPLOTTER_SYNCMULTIPLOT',1,'Synchronizing Several Plots']]],
  ['shortcuts_20to_20drawing_20violin_20plots_27',['Adapters as shortcuts to drawing Violin Plots',['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md122',1,'']]],
  ['showin_20a_201_20channel_20cimg_20image_28',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel CImg image',['../_j_k_q_t_plotter_image_plot_c_img.html',1,'exampleTutorialProjects']]],
  ['showin_20a_201_20channel_20opencv_20cv_3a_3amat_29',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_open_c_v.html',1,'exampleTutorialProjects']]],
  ['showing_20a_203_20channel_20cimg_20image_30',['Example (JKQTPlotter): Simple math image plot, showing a 3-channel CImg image',['../_j_k_q_t_plotter_image_plot_r_g_b_c_img.html',1,'exampleTutorialProjects']]],
  ['showing_20a_203_20channel_20opencv_20cv_3a_3amat_31',['Example (JKQTPlotter): Simple RGB image plot, showing a 3-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_r_g_b_open_c_v.html',1,'exampleTutorialProjects']]],
  ['side_32',['side',['../class_j_k_q_t_p_financial_graph.html#JKQTPFinancialGraphSideBySide',1,'Several Financial Graphs side-by-side'],['../class_j_k_q_t_p_bar_graph_base.html#JKQTPBarGraphBase_SideBySide',1,'several JKQTPBarGraphBase side-by-side']]],
  ['side_20by_20side_33',['side by side',['../class_j_k_q_t_p_financial_graph.html#JKQTPFinancialGraphSideBySide',1,'Several Financial Graphs side-by-side'],['../class_j_k_q_t_p_bar_graph_base.html#JKQTPBarGraphBase_SideBySide',1,'several JKQTPBarGraphBase side-by-side']]],
  ['signaling_20and_20actions_34',['Mouse Move Signaling and Actions',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSEMOVE',1,'']]],
  ['simple_20barchart_35',['Example (JKQTPlotter): Simple barchart',['../_j_k_q_t_plotter_barcharts.html',1,'exampleTutorialProjects']]],
  ['simple_20c_20inline_20function_36',['Simple C inline function',['../_j_k_q_t_plotter_eval_curves.html#autotoc_md65',1,'Simple C++ inline function'],['../_j_k_q_t_plotter_function_plots.html#autotoc_md70',1,'Simple C++ inline function']]],
  ['simple_20c_20inline_20function_20with_20parameters_37',['Simple C++ inline function with Parameters',['../_j_k_q_t_plotter_eval_curves.html#autotoc_md66',1,'']]],
  ['simple_20c_20inline_20function_20with_20parameters_38',['Simple C++ inline function with parameters',['../_j_k_q_t_plotter_function_plots.html#autotoc_md71',1,'']]],
  ['simple_20example_20of_20usage_39',['Simple Example of Usage',['../class_j_k_q_t_p_math_parser.html#jkmp_example',1,'']]],
  ['simple_20graph_20labels_20example_40',['Example (JKQTPlotter): Simple Graph Labels Example',['../_j_k_q_t_plotter_graph_labels_example.html',1,'exampleTutorialProjects']]],
  ['simple_20impulse_20plots_41',['Example (JKQTPlotter): Simple impulse plots',['../_j_k_q_t_plotter_impulse_plots.html',1,'exampleTutorialProjects']]],
  ['simple_20line_20graph_42',['Example (JKQTPlotter): Very simple line-graph',['../_j_k_q_t_plotter_simple_test.html',1,'exampleTutorialProjects']]],
  ['simple_20line_20graph_20with_20error_20bars_43',['Example (JKQTPlotter): Simple line-graph with error bars',['../_j_k_q_t_plotter_symbols_errors.html',1,'exampleTutorialProjects']]],
  ['simple_20line_20graph_20with_20live_20data_20speed_20test_44',['Example (JKQTPlotter): Simple line-graph with live-data (speed test)',['../_j_k_q_t_plotter_speed_test.html',1,'exampleTutorialProjects']]],
  ['simple_20linear_20regression_45',['Simple Linear Regression',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html#autotoc_md42',1,'']]],
  ['simple_20math_20image_20plot_46',['Example (JKQTPlotter): Simple math image plot',['../_j_k_q_t_plotter_image_plot.html',1,'exampleTutorialProjects']]],
  ['simple_20math_20image_20plot_20showin_20a_201_20channel_20cimg_20image_47',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel CImg image',['../_j_k_q_t_plotter_image_plot_c_img.html',1,'exampleTutorialProjects']]],
  ['simple_20math_20image_20plot_20showin_20a_201_20channel_20opencv_20cv_3a_3amat_48',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_open_c_v.html',1,'exampleTutorialProjects']]],
  ['simple_20math_20image_20plot_20showing_20a_203_20channel_20cimg_20image_49',['Example (JKQTPlotter): Simple math image plot, showing a 3-channel CImg image',['../_j_k_q_t_plotter_image_plot_r_g_b_c_img.html',1,'exampleTutorialProjects']]],
  ['simple_20math_20image_20plot_20with_20modifier_20datat_50',['Example (JKQTPlotter): Simple math image plot with modifier datat',['../_j_k_q_t_plotter_image_plot_modifier.html',1,'exampleTutorialProjects']]],
  ['simple_20math_20image_20plot_20without_20use_20of_20central_20jkqtdatastore_51',['Example (JKQTPlotter): Simple math image plot without use of central JKQTdatastore',['../_j_k_q_t_plotter_image_plot_no_datastore.html',1,'exampleTutorialProjects']]],
  ['simple_20math_20rgb_20cmy_20image_20plot_52',['Example (JKQTPlotter): Simple Math RGB/CMY Image Plot',['../_j_k_q_t_plotter_r_g_b_image_plot.html',1,'exampleTutorialProjects']]],
  ['simple_20rgb_20image_20plot_20showing_20a_203_20channel_20opencv_20cv_3a_3amat_53',['Example (JKQTPlotter): Simple RGB image plot, showing a 3-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_r_g_b_open_c_v.html',1,'exampleTutorialProjects']]],
  ['simple_20scatter_20graph_54',['Example (JKQTPlotter): Very simple scatter-graph',['../_j_k_q_t_plotterscatter.html',1,'exampleTutorialProjects']]],
  ['simple_20stacked_20barchart_55',['Example (JKQTPlotter): Simple stacked barchart',['../_j_k_q_t_plotter_stacked_bar_chart.html',1,'exampleTutorialProjects']]],
  ['simple_20usage_20example_56',['Example (JKQTMathText): A simple usage example',['../_j_k_q_t_math_text_simple_example.html',1,'exampleTutorialProjects']]],
  ['size_20of_20an_20equation_57',['Determining the size of an equation',['../class_j_k_q_t_math_text.html#JKQTMathTextSizing',1,'']]],
  ['sizes_58',['Font Sizes',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXFontPropsFontSizes',1,'']]],
  ['sizes_20borders_59',['Plot Sizes &amp;amp; Borders',['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_plotsize',1,'']]],
  ['some_20example_20styles_60',['Some Example Styles',['../_j_k_q_t_plotter_styling.html#autotoc_md97',1,'']]],
  ['special_20characters_61',['Symbols and special characters',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXSymbols',1,'']]],
  ['special_20context_20menu_62',['Special Context Menu',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md115',1,'']]],
  ['special_20font_20names_63',['Special Font Names',['../struct_j_k_q_t_math_text_font_specifier.html#JKQTMathTextFontSpecifier_specialNames',1,'']]],
  ['special_20functions_64',['Math Special Functions',['../group__jkqtmathtext__supportedlatexsymbols.html#jkqtmathtext_supportedlatexsymbols_mathspecialfunctions',1,'']]],
  ['special_20functions_65',['Predefined &quot;special&quot; functions',['../_j_k_q_t_plotter_function_plots.html#autotoc_md74',1,'']]],
  ['special_20properties_20of_20the_20jkqtpdatastore_20iterators_66',['Special Properties of the JKQTPDatastore-Iterators',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md41',1,'']]],
  ['special_20use_20cases_67',['Examples for special Use-Cases',['../example_tutorial_projects.html#jkqtp_extut_specialusecasesexamples',1,'']]],
  ['special_20user_20defined_20context_20menu_20of_20jkqtplotter_68',['Special (User-Defined) Context Menu of JKQTPlotter',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_SPECIALCONTEXTMENU',1,'']]],
  ['speed_20test_69',['Example (JKQTPlotter): Simple line-graph with live-data (speed test)',['../_j_k_q_t_plotter_speed_test.html',1,'exampleTutorialProjects']]],
  ['stacked_20barchart_70',['Example (JKQTPlotter): Simple stacked barchart',['../_j_k_q_t_plotter_stacked_bar_chart.html',1,'exampleTutorialProjects']]],
  ['standalone_20usage_20non_20visible_20class_71',['JKQTBasePlotter Standalone Usage (non-visible class)',['../class_j_k_q_t_base_plotter.html#jkqtplotter_usage_baseplotter_standalone',1,'']]],
  ['standard_20boxplots_72',['Standard Boxplots',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md51',1,'']]],
  ['standard_20context_20menu_73',['Standard Context Menu',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md114',1,'']]],
  ['standards_74',['Standards',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md2',1,'Our Standards'],['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html#autotoc_md8',1,'Our Standards']]],
  ['static_20c_20functions_75',['Static C functions',['../_j_k_q_t_plotter_function_plots.html#autotoc_md73',1,'']]],
  ['static_20library_76',['DEPRECATED: QMake Static Library',['../page_buildinstructions__q_m_a_k_e.html#page_buildinstructions_QMAKESTATIC',1,'']]],
  ['statistical_20distribution_20of_20data_77',['Example (JKQTPlotter): Plotting a Statistical Distribution of Data',['../_j_k_q_t_plotter_distribution_plot.html',1,'exampleTutorialProjects']]],
  ['statistics_78',['Statistics',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md49',1,'Basic Statistics'],['../example_tutorial_projects.html#jkqtp_extut_datamanagement',1,'Examples for Data Management &amp; Statistics'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html#autotoc_md58',1,'Marginal Statistics']]],
  ['statistics_20for_20a_20barchart_79',['Calculating Grouped Statistics for a Barchart',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md32',1,'']]],
  ['statistics_20for_20a_20boxplot_80',['Calculating Grouped Statistics for a Boxplot',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md33',1,'']]],
  ['statistics_20library_81',['Tutorial (JKQTPDatastore): Regression Analysis (with the Statistics Library)',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html',1,'exampleTutorialProjects']]],
  ['statistics_20with_20jkqtpdatastore_82',['Statistics with JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html',1,'Tutorial (JKQTPDatastore): 1-Dimensional Group Statistics with JKQTPDatastore'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html',1,'Tutorial (JKQTPDatastore): Advanced 1-Dimensional Statistics with JKQTPDatastore'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html',1,'Tutorial (JKQTPDatastore): Advanced 2-Dimensional Statistics with JKQTPDatastore']]],
  ['step_20line_20plots_20in_20different_20styles_83',['Example (JKQTPlotter): Step Line Plots in Different Styles',['../_j_k_q_t_plotter_special_step_line_plot.html',1,'exampleTutorialProjects']]],
  ['stl_20algorithms_84',['Using C++ STL algorithms',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md40',1,'']]],
  ['storage_85',['Data Storage',['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_datastore',1,'']]],
  ['strikeout_86',['Text Decoration: Underline, Overlines, Strikeout, ...',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXUnderlinesEtz',1,'']]],
  ['structure_87',['Graph Class Structure',['../group__jkqtplotter__graphsgroup__classstructure.html#jkqtplotter_graphsgroup_classstructure_basics',1,'']]],
  ['studio_20msvc_88',['Configuring&amp;amp;Building with Visual Studio/MSVC',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_VSTUDIO',1,'']]],
  ['style_89',['Altering the Default Style',['../_j_k_q_t_plotter_styling.html#autotoc_md94',1,'']]],
  ['style_90',['Plot black/transparent wiggle plot using &lt;span class=&quot;tt&quot;&gt;JKQTPFilledCurveYGraph&lt;/span&gt; in a &quot;seismographic style&quot;',['../_j_k_q_t_plotter_wiggle_plots.html#autotoc_md119',1,'']]],
  ['style_20to_20an_20existing_20jkqtplotter_91',['Apply a new Style to an Existing JKQTPlotter',['../_j_k_q_t_plotter_styling.html#autotoc_md96',1,'']]],
  ['styles_92',['Styles',['../_j_k_q_t_plotter_symbols_and_styles.html',1,'Example (JKQTPlotter): Line Graph with Different Symbols and Line Styles'],['../_j_k_q_t_plotter_special_step_line_plot.html',1,'Example (JKQTPlotter): Step Line Plots in Different Styles'],['../example_tutorial_projects.html#jkqtp_extut_plotstyles',1,'Examples for Different Plot Data Styles'],['../_j_k_q_t_plotter_styling.html#autotoc_md97',1,'Some Example Styles']]],
  ['styling_93',['Styling',['../class_j_k_q_t_p_bar_graph_base.html#JKQTPBarGraphBaseStyling',1,'Basic Bargraph Styling'],['../_j_k_q_t_plotter_advanced_line_and_fill_styling.html',1,'Example (JKQTPlotter): Advanced Line and Fill Styling'],['../example_tutorial_projects.html#jkqtp_extut_guitoolslayout',1,'Examples for Layout &amp; Styling'],['../class_j_k_q_t_p_base_key.html#JKQTPBaseKey_Styling',1,'Key/Legend Styling']]],
  ['styling_20a_20contour_20plot_94',['Styling a Contour Plot',['../_j_k_q_t_plotter_contour_plot.html#autotoc_md14',1,'']]],
  ['styling_20a_20jkqtplotter_95',['Tutorial (JKQTPlotter): Styling a JKQtPlotter',['../_j_k_q_t_plotter_styling.html',1,'exampleTutorialProjects']]],
  ['styling_20different_20aspects_20of_20boxplots_96',['Example (JKQTPlotter): Styling different aspects of boxplots',['../_j_k_q_t_plotter_boxplot_styling.html',1,'exampleTutorialProjects']]],
  ['styling_20of_20bargraphs_97',['Data-Dependent Styling of Bargraphs',['../class_j_k_q_t_p_bar_graph_base.html#JKQTPBarGraphBaseDataDependentFilling',1,'']]],
  ['styling_20of_20the_20graph_98',['Appearance &amp;amp; Styling of the Graph',['../class_j_k_q_t_base_plotter.html#jkqtbaseplotter_appearance_and_style',1,'']]],
  ['styling_20the_20financial_20graphs_99',['Styling the Financial Graphs',['../class_j_k_q_t_p_financial_graph.html#JKQTPFinancialGraphStyling',1,'']]],
  ['styling_20the_20plot_20keys_20axes_100',['Examples for Styling the Plot, Keys, Axes, ...',['../example_tutorial_projects.html#jkqtp_extut_keyaxesstyles',1,'']]],
  ['sub_20and_20superscript_101',['Sub- and Superscript',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXSubSuper',1,'']]],
  ['superscript_102',['Sub- and Superscript',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXSubSuper',1,'']]],
  ['support_20for_20arrows_103',['Classes with support for arrows',['../_j_k_q_t_plotter_geometric_arrows.html#autotoc_md78',1,'']]],
  ['supported_20mathematical_20constructs_104',['Supported Mathematical Constructs',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXMathSupport',1,'']]],
  ['supported_20versions_105',['Supported Versions',['../md__s_e_c_u_r_i_t_y.html#autotoc_md124',1,'']]],
  ['switch_20between_20math_20and_20text_20mode_106',['Switch between Math- and Text-Mode',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXMathTextMode',1,'']]],
  ['switching_20graph_20visibility_20via_20context_20menu_107',['Switching Graph Visibility via Context Menu',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md101',1,'']]],
  ['symbols_108',['Other Symbols',['../group__jkqtmathtext__supportedlatexsymbols.html#jkqtmathtext_supportedlatexsymbols_other',1,'']]],
  ['symbols_109',['symbols',['../_j_k_q_t_plotterparamscatter_custom_symbol.html',1,'Example (JKQTPlotter): Parametrized Scatter-graph with custom symbols'],['../_j_k_q_t_plotterscatter_custom_symbol.html',1,'Example (JKQTPlotter): Scatter-graph with custom symbols']]],
  ['symbols_20and_20line_20styles_110',['Example (JKQTPlotter): Line Graph with Different Symbols and Line Styles',['../_j_k_q_t_plotter_symbols_and_styles.html',1,'exampleTutorialProjects']]],
  ['symbols_20and_20special_20characters_111',['Symbols and special characters',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXSymbols',1,'']]],
  ['symbols_20colors_112',['Example (JKQTPlotter): Scatter Graph with Parametrized Symbols/Colors',['../_j_k_q_t_plotter_param_scatter.html',1,'exampleTutorialProjects']]],
  ['synchronizing_20axis_20range_20plot_20width_113',['Synchronizing Axis Range &amp;amp; Plot Width',['../class_j_k_q_t_base_plotter.html#JKQTBASEPLOTTER_SYNCMULTIPLOT_SYNC',1,'']]],
  ['synchronizing_20several_20plots_114',['Synchronizing Several Plots',['../class_j_k_q_t_base_plotter.html#JKQTBASEPLOTTER_SYNCMULTIPLOT',1,'Synchronizing Several Plots'],['../class_j_k_q_t_plotter.html#JKQTPLOTTER_SYNCMULTIPLOT',1,'Synchronizing Several Plots']]],
  ['syntax_115',['Font Definition Syntax',['../struct_j_k_q_t_math_text_font_specifier.html#JKQTMathTextFontSpecifier_specialSyntax',1,'']]],
  ['system_116',['Examples for CMake Build System',['../example_tutorial_projects.html#jkqtp_extut_cmake_build',1,'']]],
  ['system_20wide_20settings_117',['Global/System-wide Settings',['../_j_k_q_t_plotter_styling.html#autotoc_md95',1,'']]],
  ['systems_118',['Coordinate Systems',['../class_j_k_q_t_p_geometric_plot_element.html#JKQTPGeometricPlotElement_coordinates',1,'']]],
  ['systems_20and_20transformations_119',['Systems and Transformations',['../class_j_k_q_t_p_coordinate_axis.html#jkqtplotter_base_systems_baseelements',1,'Coordinate Systems and Transformations'],['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_systems_baseplotter',1,'Coordinate Systems and Transformations']]]
];
