var searchData=
[
  ['c_20array_20into_20a_20column_20of_20the_20jkqtpdatastore_0',['Copy Data from a C-array into a Column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md18',1,'']]],
  ['c_20functions_1',['Static C functions',['../_j_k_q_t_plotter_function_plots.html#autotoc_md73',1,'']]],
  ['c_20functors_20as_20plot_20functions_2',['C++ functors as plot functions',['../_j_k_q_t_plotter_function_plots.html#autotoc_md72',1,'']]],
  ['c_20inline_20function_3',['C inline function',['../_j_k_q_t_plotter_eval_curves.html#autotoc_md65',1,'Simple C++ inline function'],['../_j_k_q_t_plotter_function_plots.html#autotoc_md70',1,'Simple C++ inline function']]],
  ['c_20inline_20function_20with_20parameters_4',['Simple C++ inline function with Parameters',['../_j_k_q_t_plotter_eval_curves.html#autotoc_md66',1,'']]],
  ['c_20inline_20function_20with_20parameters_5',['Simple C++ inline function with parameters',['../_j_k_q_t_plotter_function_plots.html#autotoc_md71',1,'']]],
  ['c_20stl_20algorithms_6',['Using C++ STL algorithms',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md40',1,'']]],
  ['calculate_20another_7',['Using Data from one Column to Calculate Another',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md27',1,'']]],
  ['calculating_20grouped_20statistics_20for_20a_20barchart_8',['Calculating Grouped Statistics for a Barchart',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md32',1,'']]],
  ['calculating_20grouped_20statistics_20for_20a_20boxplot_9',['Calculating Grouped Statistics for a Boxplot',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md33',1,'']]],
  ['calculating_20x_20and_20y_20errors_20from_20categorized_20data_10',['Calculating x- and y-Errors from Categorized Data',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md36',1,'']]],
  ['candlestick_20ohlc_20example_11',['Example (JKQTPlotter): Financial Chart (Candlestick/OHLC) Example',['../_j_k_q_t_plotter_financial_chart_example.html',1,'exampleTutorialProjects']]],
  ['cases_12',['Examples for special Use-Cases',['../example_tutorial_projects.html#jkqtp_extut_specialusecasesexamples',1,'']]],
  ['categorized_20data_13',['Categorized Data',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md34',1,'(Scatter-)Graphs with X/Y-errors from Categorized Data'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md36',1,'Calculating x- and y-Errors from Categorized Data']]],
  ['categorized_20data_14',['Barcharts &amp;amp; Boxplots from categorized data',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md30',1,'']]],
  ['central_20jkqtdatastore_15',['Example (JKQTPlotter): Simple math image plot without use of central JKQTdatastore',['../_j_k_q_t_plotter_image_plot_no_datastore.html',1,'exampleTutorialProjects']]],
  ['channel_20cimg_20image_16',['channel CImg image',['../_j_k_q_t_plotter_image_plot_c_img.html',1,'Example (JKQTPlotter): Simple math image plot, showin a 1-channel CImg image'],['../_j_k_q_t_plotter_image_plot_r_g_b_c_img.html',1,'Example (JKQTPlotter): Simple math image plot, showing a 3-channel CImg image']]],
  ['channel_20opencv_20cv_3a_3amat_17',['channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_open_c_v.html',1,'Example (JKQTPlotter): Simple math image plot, showin a 1-channel OpenCV cv::Mat'],['../_j_k_q_t_plotter_image_plot_r_g_b_open_c_v.html',1,'Example (JKQTPlotter): Simple RGB image plot, showing a 3-channel OpenCV cv::Mat']]],
  ['characters_18',['Symbols and special characters',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXSymbols',1,'']]],
  ['chart_20candlestick_20ohlc_20example_19',['Example (JKQTPlotter): Financial Chart (Candlestick/OHLC) Example',['../_j_k_q_t_plotter_financial_chart_example.html',1,'exampleTutorialProjects']]],
  ['cimg_20image_20',['CImg image',['../_j_k_q_t_plotter_image_plot_c_img.html',1,'Example (JKQTPlotter): Simple math image plot, showin a 1-channel CImg image'],['../_j_k_q_t_plotter_image_plot_r_g_b_c_img.html',1,'Example (JKQTPlotter): Simple math image plot, showing a 3-channel CImg image']]],
  ['circles_21',['Circles',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md111',1,'']]],
  ['class_22',['JKQTBasePlotter Standalone Usage (non-visible class)',['../class_j_k_q_t_base_plotter.html#jkqtplotter_usage_baseplotter_standalone',1,'']]],
  ['class_20formwithjkqtplotter_23',['Form Class &lt;span class=&quot;tt&quot;&gt;FormWithJKQTPlotter&lt;/span&gt;',['../_j_k_q_t_plotter_qt_creator.html#autotoc_md92',1,'']]],
  ['class_20jkqtmathtextlabel_24',['Usage within a QLabel class JKQTMathTextLabel',['../class_j_k_q_t_math_text.html#JKQTMathTextUsageQLabel',1,'']]],
  ['class_20structure_25',['Graph Class Structure',['../group__jkqtplotter__graphsgroup__classstructure.html#jkqtplotter_graphsgroup_classstructure_basics',1,'']]],
  ['classes_20for_20graphs_26',['Mix-In Classes for Graphs',['../group__jkqtplotter__graphsgroup__classstructure.html#jkqtplotter_graphsgroup_classstructure_mixins',1,'']]],
  ['classes_20with_20support_20for_20arrows_27',['Classes with support for arrows',['../_j_k_q_t_plotter_geometric_arrows.html#autotoc_md78',1,'']]],
  ['clicks_20on_20the_20mouse_20buttons_28',['Actions After (Double-)Clicks on the Mouse Buttons',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSECLICK',1,'']]],
  ['cmake_29',['CMake',['../page_buildinstructions__c_m_a_k_e.html',1,'Build using CMake'],['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_CONFIG',1,'Configuring a Build with CMake'],['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_INSTALL',1,'Installing with CMake'],['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_RUN',1,'Running a Build with CMake']]],
  ['cmake_20build_30',['Using a CMake Build',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_USAGE',1,'']]],
  ['cmake_20build_20system_31',['Examples for CMake Build System',['../example_tutorial_projects.html#jkqtp_extut_cmake_build',1,'']]],
  ['cmake_20example_32',['Example (JKQTPlotter): CMake Example',['../_j_k_q_t_c_make_link_example.html',1,'exampleTutorialProjects']]],
  ['cmake_20fetchcontent_20example_33',['Example (JKQTPlotter): CMake FetchContent Example',['../_j_k_q_t_c_make_fetch_content_example.html',1,'exampleTutorialProjects']]],
  ['cmake_20s_20fetchcontent_20api_34',['Using JKQTPlotter with CMake&apos;s FetchContent-API',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_FETCHCONTENT',1,'']]],
  ['cmy_20image_20plot_35',['Example (JKQTPlotter): Simple Math RGB/CMY Image Plot',['../_j_k_q_t_plotter_r_g_b_image_plot.html',1,'exampleTutorialProjects']]],
  ['code_36',['Example Code',['../class_j_k_q_t_math_text.html#JKQTMathTextUsageExample',1,'']]],
  ['code_20of_20conduct_37',['Contributor Covenant Code of Conduct',['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html',1,'']]],
  ['color_38',['Text Color',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXTextColor',1,'']]],
  ['color_20fill_20mode_39',['Example (JKQTPlotter): Barchart With Two-Color Fill-Mode',['../_j_k_q_t_plotter_barcharts_two_color_filling.html',1,'exampleTutorialProjects']]],
  ['colors_40',['Example (JKQTPlotter): Scatter Graph with Parametrized Symbols/Colors',['../_j_k_q_t_plotter_param_scatter.html',1,'exampleTutorialProjects']]],
  ['column_41',['Image Column',['../class_j_k_q_t_p_datastore.html#jkqtpdatastore_column_management_images',1,'']]],
  ['column_20contents_42',['Modify Column Contents',['../class_j_k_q_t_p_datastore.html#jkqtpdatastore_column_management_modify',1,'']]],
  ['column_20data_20access_20to_20existing_20rows_43',['Iterator-based Column Data Access To Existing Rows',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md38',1,'']]],
  ['column_20generation_20deletion_44',['Column Generation/Deletion',['../class_j_k_q_t_p_datastore.html#jkqtpdatastore_column_management_generation',1,'']]],
  ['column_20management_45',['Column Management',['../class_j_k_q_t_p_datastore.html#jkqtpdatastore_column_management',1,'']]],
  ['column_20of_20the_20jkqtpdatastore_46',['Copy Data from a C-array into a Column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md18',1,'']]],
  ['column_20of_20the_20jkqtpdatastore_47',['column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md17',1,'Copy Data from a Vector into a column of the JKQTPDatastore'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md20',1,'Reference External Data in a column of the JKQTPDatastore']]],
  ['column_20properties_48',['Column Properties',['../class_j_k_q_t_p_datastore.html#jkqtpdatastore_column_management_props',1,'']]],
  ['column_20to_20calculate_20another_49',['Using Data from one Column to Calculate Another',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md27',1,'']]],
  ['columns_50',['Columns',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md26',1,'Appending to Columns'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md39',1,'Back-Inserter for Columns'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md25',1,'Generating Columns Preinitialized Columns']]],
  ['columns_20and_20filling_20them_51',['Generating Non-Initialized Columns and Filling Them',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md24',1,'']]],
  ['columns_20preinitialized_20columns_52',['Generating Columns Preinitialized Columns',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md25',1,'']]],
  ['command_20line_20utility_20jkqtmathtext_5frender_53',['Tool (JKQTMathText): Command-Line Utility jkqtmathtext_render',['../_j_k_q_t_math_text_render_cmd_line_tool.html',1,'exampleTutorialProjects']]],
  ['command_20line_20utility_20jkqtplotter_5fdoc_5fimagegenerator_54',['Tool (JKQTMathText): Command-Line Utility jkqtplotter_doc_imagegenerator',['../_j_k_q_t_plotter_doc_image_render_cmd_line_tool.html',1,'exampleTutorialProjects']]],
  ['compatibility_20diverse_20improvements_20bugfixes_55',['V4.0.0: Qt6 compatibility &amp;amp; diverse improvements + bugfixes',['../page_whatsnew.html#page_whatsnew_V4_0_0',1,'']]],
  ['compatible_20version_56',['v2018.08: Minor Modifications (Final QuickFit3-compatible Version)',['../page_whatsnew.html#page_whatsnew_V2018_08',1,'']]],
  ['complex_20examples_57',['More Complex Examples',['../example_tutorial_projects.html#jkqtp_extut_complexexamples',1,'']]],
  ['conduct_58',['Contributor Covenant Code of Conduct',['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html',1,'']]],
  ['configuring_20a_20build_20with_20cmake_59',['Configuring a Build with CMake',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_CONFIG',1,'']]],
  ['configuring_20building_60',['Generic Configuring&amp;amp;Building',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_MAKEFILE',1,'']]],
  ['configuring_20building_20with_20visual_20studio_20msvc_61',['Configuring&amp;amp;Building with Visual Studio/MSVC',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_VSTUDIO',1,'']]],
  ['considerations_20when_20setting_20up_20plots_62',['Performance Considerations when Setting up Plots',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_PERFORMACEWHILESETUP',1,'']]],
  ['constants_20and_20variables_3a_63',['constants and variables:',['../class_j_k_q_t_p_math_parser.html#jkmp_constantsAndVars',1,'']]],
  ['constructs_64',['Supported Mathematical Constructs',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXMathSupport',1,'']]],
  ['contained_20in_20jkqtplotter_65',['Licenses of 3rd Party Products Contained in JKQTPlotter',['../licensepage.html#extlicense_sec',1,'']]],
  ['containers_20into_20jkqtpdatastore_66',['Copying Data from External COntainers into JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md16',1,'']]],
  ['contents_67',['Contents',['../class_j_k_q_t_p_datastore.html#jkqtpdatastore_column_management_modify',1,'Modify Column Contents'],['../index.html#jkqtplottertic',1,'Table Of Contents']]],
  ['context_20menu_68',['Context Menu',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md115',1,'Special Context Menu'],['../_j_k_q_t_plotter_user_interaction.html#autotoc_md114',1,'Standard Context Menu'],['../_j_k_q_t_plotter_user_interaction.html#autotoc_md101',1,'Switching Graph Visibility via Context Menu']]],
  ['context_20menu_20of_20jkqtplotter_69',['Context Menu of JKQTPlotter',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_CONTEXTMENU',1,'Context Menu of JKQTPlotter'],['../class_j_k_q_t_plotter.html#JKQTPLOTTER_SPECIALCONTEXTMENU',1,'Special (User-Defined) Context Menu of JKQTPlotter']]],
  ['context_20menus_70',['Context Menus',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md113',1,'']]],
  ['contour_20plot_71',['Contour Plot',['../_j_k_q_t_plotter_contour_plot.html#autotoc_md13',1,'Drawing a Contour Plot'],['../_j_k_q_t_plotter_contour_plot.html#autotoc_md15',1,'Gimmick: Animating a Contour Plot'],['../_j_k_q_t_plotter_contour_plot.html#autotoc_md14',1,'Styling a Contour Plot']]],
  ['contour_20plots_72',['Example (JKQTPlotter): Contour Plots',['../_j_k_q_t_plotter_contour_plot.html',1,'exampleTutorialProjects']]],
  ['contributing_73',['Contributing',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html',1,'']]],
  ['contributor_20covenant_20code_20of_20conduct_74',['Contributor Covenant Code of Conduct',['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html',1,'']]],
  ['convenience_20functions_75',['Convenience Functions',['../class_j_k_q_t_math_text.html#JKQTMathTextUsageConvenience',1,'']]],
  ['convert_20to_20html_76',['Convert to HTML',['../class_j_k_q_t_math_text.html#JKQTMathTextToHTML',1,'']]],
  ['coordinate_20axes_77',['Coordinate Axes',['../class_j_k_q_t_p_coordinate_axis.html#jkqtplotter_coordinateaxes_inverted',1,'Inverted Coordinate Axes'],['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_grids_baseplotter_majoraxes',1,'Major Coordinate Axes'],['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_grids_baseplotter_secondaryaxes',1,'Secondary Coordinate Axes']]],
  ['coordinate_20systems_78',['Coordinate Systems',['../class_j_k_q_t_p_geometric_plot_element.html#JKQTPGeometricPlotElement_coordinates',1,'']]],
  ['coordinate_20systems_20and_20transformations_79',['Coordinate Systems and Transformations',['../class_j_k_q_t_p_coordinate_axis.html#jkqtplotter_base_systems_baseelements',1,'Coordinate Systems and Transformations'],['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_systems_baseplotter',1,'Coordinate Systems and Transformations']]],
  ['copy_20data_20from_20a_20c_20array_20into_20a_20column_20of_20the_20jkqtpdatastore_80',['Copy Data from a C-array into a Column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md18',1,'']]],
  ['copy_20data_20from_20a_20map_20into_20a_20jkqtpdatastore_81',['Copy Data from a Map into a JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md19',1,'']]],
  ['copy_20data_20from_20a_20vector_20into_20a_20column_20of_20the_20jkqtpdatastore_82',['Copy Data from a Vector into a column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md17',1,'']]],
  ['copying_20data_20from_20external_20containers_20into_20jkqtpdatastore_83',['Copying Data from External COntainers into JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md16',1,'']]],
  ['covenant_20code_20of_20conduct_84',['Contributor Covenant Code of Conduct',['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html',1,'']]],
  ['cummulative_20histograms_20and_20kdes_85',['Cummulative Histograms and KDEs',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md55',1,'']]],
  ['curve_20plots_86',['Example (JKQTPlotter): Filled Curve Plots',['../_j_k_q_t_plotter_filled_graphs.html',1,'exampleTutorialProjects']]],
  ['curves_87',['Curves',['../_j_k_q_t_plotter_geometric_bezier.html',1,'Example (JKQTPlotter): Plotting Bezier Curves'],['../_j_k_q_t_plotter_parametric_curves.html',1,'Example (JKQTPlotter): Plotting Parametric Curves']]],
  ['curves_20as_20line_20graphs_88',['Example (JKQTPlotter): Plotting Parametric Mathematical Curves as Line Graphs',['../_j_k_q_t_plotter_eval_curves.html',1,'exampleTutorialProjects']]],
  ['custom_20bargraph_20drawing_89',['Custom Bargraph Drawing',['../class_j_k_q_t_p_bar_graph_base.html#JKQTPBarGraphBaseCustomStyling',1,'']]],
  ['custom_20draw_20functor_90',['Example (JKQTPlotter): Barchart With Custom Draw Functor',['../_j_k_q_t_plotter_barcharts_custom_draw_functor.html',1,'exampleTutorialProjects']]],
  ['custom_20palettes_91',['Example (JKQTPlotter): Image Plots with Custom Palettes',['../_j_k_q_t_plotter_image_plot_user_palette.html',1,'exampleTutorialProjects']]],
  ['custom_20symbols_92',['custom symbols',['../_j_k_q_t_plotterparamscatter_custom_symbol.html',1,'Example (JKQTPlotter): Parametrized Scatter-graph with custom symbols'],['../_j_k_q_t_plotterscatter_custom_symbol.html',1,'Example (JKQTPlotter): Scatter-graph with custom symbols']]],
  ['cv_3a_3amat_93',['cv::Mat',['../_j_k_q_t_plotter_image_plot_open_c_v.html',1,'Example (JKQTPlotter): Simple math image plot, showin a 1-channel OpenCV cv::Mat'],['../_j_k_q_t_plotter_image_plot_r_g_b_open_c_v.html',1,'Example (JKQTPlotter): Simple RGB image plot, showing a 3-channel OpenCV cv::Mat']]]
];
