var searchData=
[
  ['table_20of_20contents_0',['Table Of Contents',['../index.html#jkqtplottertic',1,'']]],
  ['tabular_20environments_1',['Tabular Environments',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXTabular',1,'']]],
  ['terms_20for_20jkqtplotter_2',['Licensing Terms for JKQTPlotter',['../licensepage.html',1,'']]],
  ['test_3',['Example (JKQTPlotter): Simple line-graph with live-data (speed test)',['../_j_k_q_t_plotter_speed_test.html',1,'exampleTutorialProjects']]],
  ['test_20application_4',['Example (JKQTMathText): A test application',['../_j_k_q_t_math_text_test_app.html',1,'exampleTutorialProjects']]],
  ['test_20dataset_5',['Generating a test Dataset',['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md117',1,'']]],
  ['text_6',['Verbatim Text',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXVerbatim',1,'']]],
  ['text_7',['Environments for Multi-line text',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXTextAlignment',1,'']]],
  ['text_20color_8',['Text Color',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXTextColor',1,'']]],
  ['text_20decoration_3a_20underline_20overlines_20strikeout_9',['Text Decoration: Underline, Overlines, Strikeout, ...',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXUnderlinesEtz',1,'']]],
  ['text_20mode_10',['Switch between Math- and Text-Mode',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXMathTextMode',1,'']]],
  ['the_20adaptive_20plotting_20algorithm_11',['Properties of the Adaptive Plotting Algorithm',['../_j_k_q_t_plotter_parsed_function_plot.html#autotoc_md90',1,'']]],
  ['the_20default_20style_12',['Altering the Default Style',['../_j_k_q_t_plotter_styling.html#autotoc_md94',1,'']]],
  ['the_20example_20gui_13',['Main Program of the Example (GUI)',['../_j_k_q_t_plotter_image_plot_user_palette.html#autotoc_md82',1,'']]],
  ['the_20financial_20graphs_14',['Styling the Financial Graphs',['../class_j_k_q_t_p_financial_graph.html#JKQTPFinancialGraphStyling',1,'']]],
  ['the_20full_20program_15',['the full Program',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md37',1,'Screenshot of the full Program'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html#autotoc_md47',1,'Screenshot of the full Program'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md56',1,'Screenshot of the full Program'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html#autotoc_md61',1,'Screenshot of the full Program']]],
  ['the_20graph_16',['Appearance &amp;amp; Styling of the Graph',['../class_j_k_q_t_base_plotter.html#jkqtbaseplotter_appearance_and_style',1,'']]],
  ['the_20jkqtpdatastore_17',['the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md18',1,'Copy Data from a C-array into a Column of the JKQTPDatastore'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md17',1,'Copy Data from a Vector into a column of the JKQTPDatastore'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md20',1,'Reference External Data in a column of the JKQTPDatastore']]],
  ['the_20jkqtpdatastore_20iterators_18',['Special Properties of the JKQTPDatastore-Iterators',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md41',1,'']]],
  ['the_20library_19',['v2019.11: Major rework of the library',['../page_whatsnew.html#page_whatsnew_V2019_11',1,'']]],
  ['the_20mouse_20',['the Mouse',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSEDRAG',1,'Actions When Dragging the Mouse'],['../_j_k_q_t_plotter_user_interaction.html#autotoc_md105',1,'Zooming with the Mouse']]],
  ['the_20mouse_20buttons_21',['Actions After (Double-)Clicks on the Mouse Buttons',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSECLICK',1,'']]],
  ['the_20parsed_20expressions_22',['the parsed expressions',['../class_j_k_q_t_p_c_s_s_parser.html#jkqtpcss_ebnf',1,'EBNF definition of the parsed expressions'],['../class_j_k_q_t_p_math_parser.html#jkmp_ebnf',1,'EBNF definition of the parsed expressions']]],
  ['the_20plot_23',['Toolbar at the top of the Plot',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md102',1,'']]],
  ['the_20plot_20keys_20axes_24',['Examples for Styling the Plot, Keys, Axes, ...',['../example_tutorial_projects.html#jkqtp_extut_keyaxesstyles',1,'']]],
  ['the_20plot_20viewport_25',['Drag the Plot Viewport',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md104',1,'']]],
  ['the_20qt_20form_20designer_26',['the Qt Form Designer',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USEQTCREATOR',1,'How to use JKQTPlotter in the Qt Form Designer'],['../_j_k_q_t_plotter_qt_creator.html#autotoc_md91',1,'Instructions on how to use JKQTPlotter in the Qt Form Designer']]],
  ['the_20size_20of_20an_20equation_27',['Determining the size of an equation',['../class_j_k_q_t_math_text.html#JKQTMathTextSizing',1,'']]],
  ['the_20statistics_20library_28',['Tutorial (JKQTPDatastore): Regression Analysis (with the Statistics Library)',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html',1,'exampleTutorialProjects']]],
  ['the_20top_20of_20the_20plot_29',['Toolbar at the top of the Plot',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md102',1,'']]],
  ['the_20vertical_20violin_20plot_30',['Drawing the (vertical) Violin Plot',['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md120',1,'']]],
  ['them_31',['Generating Non-Initialized Columns and Filling Them',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md24',1,'']]],
  ['thread_20safety_20re_20entrancy_20guarantees_32',['Thread-Safety/Re-Entrancy Guarantees',['../class_j_k_q_t_math_text.html#JKQTMathTextUsageThreadSafety',1,'']]],
  ['threaded_20parallel_20plotting_33',['Example (JKQTPlotter): Multi-Threaded (Parallel) Plotting',['../_j_k_q_t_plotter_multi_threaded.html',1,'exampleTutorialProjects']]],
  ['through_20origin_34',['Example (JKQTPlotter): Plot With Axes through Origin',['../_j_k_q_t_plotter_geometric_coordinate_axis0.html',1,'exampleTutorialProjects']]],
  ['tick_20units_20scaling_35',['Axis Tick Units/Scaling',['../class_j_k_q_t_p_coordinate_axis.html#jkqtplotter_coordinateaxes_tickscaling',1,'']]],
  ['ticks_20and_20grids_36',['Ticks and Grids',['../class_j_k_q_t_p_coordinate_axis.html#jkqtplotter_base_grids_baseelemenets',1,'Axis Ticks and Grids'],['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_grids_baseplotter',1,'Axis Ticks and Grids']]],
  ['time_20axes_37',['Example (JKQTPlotter): Date/Time Axes',['../_j_k_q_t_plotter_date_time_axes.html',1,'exampleTutorialProjects']]],
  ['time_20axis_38',['Time Axis',['../_j_k_q_t_plotter_date_time_axes.html#autotoc_md63',1,'']]],
  ['to_20an_20existing_20jkqtplotter_39',['Apply a new Style to an Existing JKQTPlotter',['../_j_k_q_t_plotter_styling.html#autotoc_md96',1,'']]],
  ['to_20calculate_20another_40',['Using Data from one Column to Calculate Another',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md27',1,'']]],
  ['to_20columns_41',['Appending to Columns',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md26',1,'']]],
  ['to_20drawing_20violin_20plots_42',['Adapters as shortcuts to drawing Violin Plots',['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md122',1,'']]],
  ['to_20existing_20rows_43',['Iterator-based Column Data Access To Existing Rows',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md38',1,'']]],
  ['to_20html_44',['Convert to HTML',['../class_j_k_q_t_math_text.html#JKQTMathTextToHTML',1,'']]],
  ['to_20use_20jkqtplotter_20in_20the_20qt_20form_20designer_45',['to use JKQTPlotter in the Qt Form Designer',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USEQTCREATOR',1,'How to use JKQTPlotter in the Qt Form Designer'],['../_j_k_q_t_plotter_qt_creator.html#autotoc_md91',1,'Instructions on how to use JKQTPlotter in the Qt Form Designer']]],
  ['todo_20list_20für_20future_20releases_20versions_46',['Todo List für Future Releases/Versions',['../page_todo.html',1,'']]],
  ['together_20with_20jkqtplotter_47',['Example (JKQTPlotter): Using a QScrollbar together with JKQtPlotter',['../_j_k_q_t_plotter_u_i_scrollbar.html',1,'exampleTutorialProjects']]],
  ['tool_48',['Tool',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md107',1,'Data ToolTip Tool'],['../_j_k_q_t_plotter_user_interaction.html#autotoc_md106',1,'Ruler/Measurement Tool']]],
  ['tool_20jkqtmathtext_20_3a_20command_20line_20utility_20jkqtmathtext_5frender_49',['Tool (JKQTMathText): Command-Line Utility jkqtmathtext_render',['../_j_k_q_t_math_text_render_cmd_line_tool.html',1,'exampleTutorialProjects']]],
  ['tool_20jkqtmathtext_20_3a_20command_20line_20utility_20jkqtplotter_5fdoc_5fimagegenerator_50',['Tool (JKQTMathText): Command-Line Utility jkqtplotter_doc_imagegenerator',['../_j_k_q_t_plotter_doc_image_render_cmd_line_tool.html',1,'exampleTutorialProjects']]],
  ['tool_20programs_51',['Tool Programs',['../example_tutorial_projects.html#jkqtp_extut_tools',1,'']]],
  ['toolbar_20at_20the_20top_20of_20the_20plot_52',['Toolbar at the top of the Plot',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md102',1,'']]],
  ['toolbar_20of_20jkqtplotter_53',['Toolbar of JKQTPlotter',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_TOOLBAR',1,'']]],
  ['tools_54',['Examples for GUI Tools',['../example_tutorial_projects.html#jkqtp_extut_guitools',1,'']]],
  ['tooltip_20tool_55',['Data ToolTip Tool',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md107',1,'']]],
  ['top_20of_20the_20plot_56',['Toolbar at the top of the Plot',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md102',1,'']]],
  ['transfer_20of_20ownership_57',['Referencing with Transfer of Ownership',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md22',1,'']]],
  ['transfer_20of_20ownership_58',['Referencing without transfer of ownership',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md21',1,'']]],
  ['transformations_59',['Transformations',['../class_j_k_q_t_p_coordinate_axis.html#jkqtplotter_base_systems_baseelements',1,'Coordinate Systems and Transformations'],['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_systems_baseplotter',1,'Coordinate Systems and Transformations']]],
  ['transparent_20wiggle_20plot_20using_20jkqtpfilledcurveygraph_20in_20a_20seismographic_20style_60',['Plot black/transparent wiggle plot using &lt;span class=&quot;tt&quot;&gt;JKQTPFilledCurveYGraph&lt;/span&gt; in a &quot;seismographic style&quot;',['../_j_k_q_t_plotter_wiggle_plots.html#autotoc_md119',1,'']]],
  ['trunk_20master_61',['trunk/master',['../page_whatsnew.html#page_whatsnew_TRUNK',1,'']]],
  ['trunk_3a_20download_62',['trunk: Download',['../page_whatsnew.html#page_whatsnew_TRUNK_DOWNLOAD',1,'']]],
  ['trunk_3a_20overview_63',['trunk: Overview',['../page_whatsnew.html#page_whatsnew_TRUNK_OVERVIEW',1,'']]],
  ['tutorial_20jkqtpdatastore_20_3a_201_20dimensional_20group_20statistics_20with_20jkqtpdatastore_64',['Tutorial (JKQTPDatastore): 1-Dimensional Group Statistics with JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html',1,'exampleTutorialProjects']]],
  ['tutorial_20jkqtpdatastore_20_3a_20advanced_201_20dimensional_20statistics_20with_20jkqtpdatastore_65',['Tutorial (JKQTPDatastore): Advanced 1-Dimensional Statistics with JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html',1,'exampleTutorialProjects']]],
  ['tutorial_20jkqtpdatastore_20_3a_20advanced_202_20dimensional_20statistics_20with_20jkqtpdatastore_66',['Tutorial (JKQTPDatastore): Advanced 2-Dimensional Statistics with JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html',1,'exampleTutorialProjects']]],
  ['tutorial_20jkqtpdatastore_20_3a_20basic_20usage_20of_20jkqtpdatastore_67',['Tutorial (JKQTPDatastore): Basic Usage of JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html',1,'exampleTutorialProjects']]],
  ['tutorial_20jkqtpdatastore_20_3a_20iterator_20based_20usage_20of_20jkqtpdatastore_68',['Tutorial (JKQTPDatastore): Iterator-Based usage of JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html',1,'exampleTutorialProjects']]],
  ['tutorial_20jkqtpdatastore_20_3a_20regression_20analysis_20with_20the_20statistics_20library_69',['Tutorial (JKQTPDatastore): Regression Analysis (with the Statistics Library)',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html',1,'exampleTutorialProjects']]],
  ['tutorial_20jkqtplotter_20_3a_20styling_20a_20jkqtplotter_70',['Tutorial (JKQTPlotter): Styling a JKQtPlotter',['../_j_k_q_t_plotter_styling.html',1,'exampleTutorialProjects']]],
  ['tutorial_20jkqtplotter_20_3a_20user_20interactions_20in_20jkqtplotter_71',['Tutorial (JKQTPlotter): User-Interactions in JKQtPlotter',['../_j_k_q_t_plotter_user_interaction.html',1,'exampleTutorialProjects']]],
  ['tutorial_20jkqtplotter_20_3a_20using_20a_20jkqtplotter_20inside_20a_20qt_20user_20interface_20designer_20ui_20file_72',['Tutorial (JKQTPlotter): Using a JKQTPlotter inside a Qt User Interface Designer (UI) File',['../_j_k_q_t_plotter_qt_creator.html',1,'exampleTutorialProjects']]],
  ['tutorial_20projects_73',['Example &amp;amp; Tutorial Projects',['../example_tutorial_projects.html',1,'']]],
  ['tutorials_20for_20jkqtplotter_74',['Examples &amp;amp; Tutorials for JKQTPlotter',['../example_tutorial_projects.html#jkqtp_extut_jkqtplotter',1,'']]],
  ['two_20color_20fill_20mode_75',['Example (JKQTPlotter): Barchart With Two-Color Fill-Mode',['../_j_k_q_t_plotter_barcharts_two_color_filling.html',1,'exampleTutorialProjects']]],
  ['type_20instructions_76',['Type Instructions',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXFrac',1,'Fraction Type Instructions'],['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXMatrix',1,'Matrix/Array Type Instructions']]],
  ['types_20of_20arrows_77',['Different types of arrows',['../_j_k_q_t_plotter_geometric_arrows.html#autotoc_md77',1,'']]],
  ['types_20of_20errorindicators_78',['Example (JKQTPlotter): Different Types of Errorindicators',['../_j_k_q_t_plotter_error_bar_styles.html',1,'exampleTutorialProjects']]]
];
