var searchData=
[
  ['ebnf_20definition_20of_20the_20parsed_20expressions_0',['EBNF definition of the parsed expressions',['../class_j_k_q_t_p_c_s_s_parser.html#jkqtpcss_ebnf',1,'EBNF definition of the parsed expressions'],['../class_j_k_q_t_p_math_parser.html#jkmp_ebnf',1,'EBNF definition of the parsed expressions']]],
  ['ellipses_1',['Ellipses',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md112',1,'']]],
  ['end_20decorators_20for_20jkqtpgeobeziercurve_2',['Line-End Decorators for JKQTPGeoBezierCurve',['../class_j_k_q_t_p_geo_bezier_curve.html#JKQTPGeoBezierCurveDecorators',1,'']]],
  ['enforcement_3',['Enforcement',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md5',1,'Enforcement'],['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html#autotoc_md11',1,'Enforcement']]],
  ['entrancy_20guarantees_4',['Thread-Safety/Re-Entrancy Guarantees',['../class_j_k_q_t_math_text.html#JKQTMathTextUsageThreadSafety',1,'']]],
  ['environments_5',['Tabular Environments',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXTabular',1,'']]],
  ['environments_20for_20multi_20line_20text_6',['Environments for Multi-line text',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXTextAlignment',1,'']]],
  ['equation_7',['Determining the size of an equation',['../class_j_k_q_t_math_text.html#JKQTMathTextSizing',1,'']]],
  ['error_20bars_8',['Example (JKQTPlotter): Barchart With Error Bars',['../_j_k_q_t_plotter_barcharts_error_bars.html',1,'exampleTutorialProjects']]],
  ['error_20bars_9',['Example (JKQTPlotter): Simple line-graph with error bars',['../_j_k_q_t_plotter_symbols_errors.html',1,'exampleTutorialProjects']]],
  ['error_20handling_10',['Error Handling',['../class_j_k_q_t_p_math_parser.html#jkmp_errorhandling',1,'Error Handling'],['../class_j_k_q_t_math_text.html#JKQTMathTextErrorHandling',1,'Error Handling']]],
  ['error_20indicators_11',['Example (JKQTPlotter): Filled Graphs with Error Indicators',['../_j_k_q_t_plotter_filled_graphs_error_bars.html',1,'exampleTutorialProjects']]],
  ['errorindicators_12',['Example (JKQTPlotter): Different Types of Errorindicators',['../_j_k_q_t_plotter_error_bar_styles.html',1,'exampleTutorialProjects']]],
  ['errors_20from_20categorized_20data_13',['Calculating x- and y-Errors from Categorized Data',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md36',1,'']]],
  ['errors_20from_20categorized_20data_14',['(Scatter-)Graphs with X/Y-errors from Categorized Data',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md34',1,'']]],
  ['estimates_20kde_15',['Estimates KDE',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md54',1,'Kernel Density Estimates (KDE)'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html#autotoc_md60',1,'Kernel Density Estimates (KDE)']]],
  ['evaluation_3a_16',['result of parsing and evaluation:',['../class_j_k_q_t_p_math_parser.html#jkmp_resultsofparsing',1,'']]],
  ['event_20occurs_17',['Actions When a Mouse Wheel Event Occurs',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSEWHEEL',1,'']]],
  ['example_18',['Example',['../_j_k_q_t_c_make_link_example.html',1,'Example (JKQTPlotter): CMake Example'],['../_j_k_q_t_c_make_fetch_content_example.html',1,'Example (JKQTPlotter): CMake FetchContent Example'],['../_j_k_q_t_plotter_financial_chart_example.html',1,'Example (JKQTPlotter): Financial Chart (Candlestick/OHLC) Example'],['../_j_k_q_t_plotter_graph_labels_example.html',1,'Example (JKQTPlotter): Simple Graph Labels Example'],['../_j_k_q_t_p_parametrized_vector_field_graph_example.html',1,'Example (JKQTPlotter): Vector Field Plot Example'],['../_j_k_q_t_plotter_vector_field_example.html',1,'Example (JKQTPlotter): Vector Field Plot Example']]],
  ['example_19',['Example (JKQTMathText): A simple usage example',['../_j_k_q_t_math_text_simple_example.html',1,'exampleTutorialProjects']]],
  ['example_20code_20',['Example Code',['../class_j_k_q_t_math_text.html#JKQTMathTextUsageExample',1,'']]],
  ['example_20gui_21',['Main Program of the Example (GUI)',['../_j_k_q_t_plotter_image_plot_user_palette.html#autotoc_md82',1,'']]],
  ['example_20jkqtfastplotter_22',['Example (JKQTFastPlotter)',['../_j_k_q_t_fast_plotter_test.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtmathtext_20_3a_20a_20simple_20usage_20example_23',['Example (JKQTMathText): A simple usage example',['../_j_k_q_t_math_text_simple_example.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtmathtext_20_3a_20a_20test_20application_24',['Example (JKQTMathText): A test application',['../_j_k_q_t_math_text_test_app.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20advanced_20line_20and_20fill_20styling_25',['Example (JKQTPlotter): Advanced Line and Fill Styling',['../_j_k_q_t_plotter_advanced_line_and_fill_styling.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20barchart_20with_20custom_20draw_20functor_26',['Example (JKQTPlotter): Barchart With Custom Draw Functor',['../_j_k_q_t_plotter_barcharts_custom_draw_functor.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20barchart_20with_20error_20bars_27',['Example (JKQTPlotter): Barchart With Error Bars',['../_j_k_q_t_plotter_barcharts_error_bars.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20barchart_20with_20functor_20fill_20mode_28',['Example (JKQTPlotter): Barchart With Functor Fill-Mode',['../_j_k_q_t_plotter_barcharts_functor_filling.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20barchart_20with_20two_20color_20fill_20mode_29',['Example (JKQTPlotter): Barchart With Two-Color Fill-Mode',['../_j_k_q_t_plotter_barcharts_two_color_filling.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20boxplots_30',['Example (JKQTPlotter): Boxplots',['../_j_k_q_t_plotter_boxplots_graphs.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20cmake_20example_31',['Example (JKQTPlotter): CMake Example',['../_j_k_q_t_c_make_link_example.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20cmake_20fetchcontent_20example_32',['Example (JKQTPlotter): CMake FetchContent Example',['../_j_k_q_t_c_make_fetch_content_example.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20contour_20plots_33',['Example (JKQTPlotter): Contour Plots',['../_j_k_q_t_plotter_contour_plot.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20date_20time_20axes_34',['Example (JKQTPlotter): Date/Time Axes',['../_j_k_q_t_plotter_date_time_axes.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20different_20types_20of_20errorindicators_35',['Example (JKQTPlotter): Different Types of Errorindicators',['../_j_k_q_t_plotter_error_bar_styles.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20draw_20an_20artistic_20image_20with_20a_20parametrized_20scatter_20graph_36',['Example (JKQTPlotter): Draw an Artistic Image with a Parametrized Scatter Graph',['../_j_k_q_t_plotter_param_scatter_image.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20filled_20curve_20plots_37',['Example (JKQTPlotter): Filled Curve Plots',['../_j_k_q_t_plotter_filled_graphs.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20filled_20graphs_20with_20error_20indicators_38',['Example (JKQTPlotter): Filled Graphs with Error Indicators',['../_j_k_q_t_plotter_filled_graphs_error_bars.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20financial_20chart_20candlestick_20ohlc_20example_39',['Example (JKQTPlotter): Financial Chart (Candlestick/OHLC) Example',['../_j_k_q_t_plotter_financial_chart_example.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20generating_20demo_20plots_20of_20geometric_20objects_20for_20documentation_40',['Example (JKQTPlotter): Generating Demo-Plots of Geometric Objects for Documentation',['../_j_k_q_t_plotter_geometric_graphs_simple.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20image_20plots_20with_20custom_20palettes_41',['Example (JKQTPlotter): Image Plots with Custom Palettes',['../_j_k_q_t_plotter_image_plot_user_palette.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20laying_20out_20several_20plots_42',['Example (JKQTPlotter): Laying out Several Plots',['../_j_k_q_t_plotter_multi_plot_layout.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20line_20graph_20with_20different_20symbols_20and_20line_20styles_43',['Example (JKQTPlotter): Line Graph with Different Symbols and Line Styles',['../_j_k_q_t_plotter_symbols_and_styles.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20line_20graph_20with_20logarithmic_20y_20axis_44',['Example (JKQTPlotter): Line Graph with Logarithmic y-axis',['../_j_k_q_t_plotter_log_axes.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20mandelbrot_20set_20explorer_45',['Example (JKQTPlotter): Mandelbrot Set Explorer',['../_j_k_q_t_plotter_mandelbrot.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20multi_20threaded_20parallel_20plotting_46',['Example (JKQTPlotter): Multi-Threaded (Parallel) Plotting',['../_j_k_q_t_plotter_multi_threaded.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20parametrized_20scatter_20graph_20with_20custom_20symbols_47',['Example (JKQTPlotter): Parametrized Scatter-graph with custom symbols',['../_j_k_q_t_plotterparamscatter_custom_symbol.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20plot_20with_20axes_20through_20origin_48',['Example (JKQTPlotter): Plot With Axes through Origin',['../_j_k_q_t_plotter_geometric_coordinate_axis0.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20plotting_20a_20statistical_20distribution_20of_20data_49',['Example (JKQTPlotter): Plotting a Statistical Distribution of Data',['../_j_k_q_t_plotter_distribution_plot.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20plotting_20arrows_50',['Example (JKQTPlotter): Plotting Arrows',['../_j_k_q_t_plotter_geometric_arrows.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20plotting_20bezier_20curves_51',['Example (JKQTPlotter): Plotting Bezier Curves',['../_j_k_q_t_plotter_geometric_bezier.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20plotting_20geometric_20objects_52',['Example (JKQTPlotter): Plotting Geometric Objects',['../_j_k_q_t_plotter_geometric_graphs.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20plotting_20mathematical_20functions_20as_20line_20graphs_53',['Example (JKQTPlotter): Plotting Mathematical Functions as Line Graphs',['../_j_k_q_t_plotter_function_plots.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20plotting_20parametric_20curves_54',['Example (JKQTPlotter): Plotting Parametric Curves',['../_j_k_q_t_plotter_parametric_curves.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20plotting_20parametric_20mathematical_20curves_20as_20line_20graphs_55',['Example (JKQTPlotter): Plotting Parametric Mathematical Curves as Line Graphs',['../_j_k_q_t_plotter_eval_curves.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20plotting_20parsed_20mathematical_20functions_20as_20line_20graphs_56',['Example (JKQTPlotter): Plotting Parsed Mathematical Functions as Line Graphs',['../_j_k_q_t_plotter_parsed_function_plot.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20qimage_20as_20a_20graph_57',['Example (JKQTPlotter): QImage as a Graph',['../_j_k_q_t_plotter_image_plot_q_image_r_g_b.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20scatter_20graph_20with_20custom_20symbols_58',['Example (JKQTPlotter): Scatter-graph with custom symbols',['../_j_k_q_t_plotterscatter_custom_symbol.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20scatter_20graph_20with_20parametrized_20symbols_20colors_59',['Example (JKQTPlotter): Scatter Graph with Parametrized Symbols/Colors',['../_j_k_q_t_plotter_param_scatter.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20secondary_20axes_60',['Example (JKQTPlotter): Secondary Axes',['../_j_k_q_t_plotter_secondary_axes.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20simple_20barchart_61',['Example (JKQTPlotter): Simple barchart',['../_j_k_q_t_plotter_barcharts.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20simple_20graph_20labels_20example_62',['Example (JKQTPlotter): Simple Graph Labels Example',['../_j_k_q_t_plotter_graph_labels_example.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20simple_20impulse_20plots_63',['Example (JKQTPlotter): Simple impulse plots',['../_j_k_q_t_plotter_impulse_plots.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20simple_20line_20graph_20with_20error_20bars_64',['Example (JKQTPlotter): Simple line-graph with error bars',['../_j_k_q_t_plotter_symbols_errors.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20simple_20line_20graph_20with_20live_20data_20speed_20test_65',['Example (JKQTPlotter): Simple line-graph with live-data (speed test)',['../_j_k_q_t_plotter_speed_test.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20simple_20math_20image_20plot_66',['Example (JKQTPlotter): Simple math image plot',['../_j_k_q_t_plotter_image_plot.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20simple_20math_20image_20plot_20showin_20a_201_20channel_20cimg_20image_67',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel CImg image',['../_j_k_q_t_plotter_image_plot_c_img.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20simple_20math_20image_20plot_20showin_20a_201_20channel_20opencv_20cv_3a_3amat_68',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_open_c_v.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20simple_20math_20image_20plot_20showing_20a_203_20channel_20cimg_20image_69',['Example (JKQTPlotter): Simple math image plot, showing a 3-channel CImg image',['../_j_k_q_t_plotter_image_plot_r_g_b_c_img.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20simple_20math_20image_20plot_20with_20modifier_20datat_70',['Example (JKQTPlotter): Simple math image plot with modifier datat',['../_j_k_q_t_plotter_image_plot_modifier.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20simple_20math_20image_20plot_20without_20use_20of_20central_20jkqtdatastore_71',['Example (JKQTPlotter): Simple math image plot without use of central JKQTdatastore',['../_j_k_q_t_plotter_image_plot_no_datastore.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20simple_20math_20rgb_20cmy_20image_20plot_72',['Example (JKQTPlotter): Simple Math RGB/CMY Image Plot',['../_j_k_q_t_plotter_r_g_b_image_plot.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20simple_20rgb_20image_20plot_20showing_20a_203_20channel_20opencv_20cv_3a_3amat_73',['Example (JKQTPlotter): Simple RGB image plot, showing a 3-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_r_g_b_open_c_v.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20simple_20stacked_20barchart_74',['Example (JKQTPlotter): Simple stacked barchart',['../_j_k_q_t_plotter_stacked_bar_chart.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20step_20line_20plots_20in_20different_20styles_75',['Example (JKQTPlotter): Step Line Plots in Different Styles',['../_j_k_q_t_plotter_special_step_line_plot.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20styling_20different_20aspects_20of_20boxplots_76',['Example (JKQTPlotter): Styling different aspects of boxplots',['../_j_k_q_t_plotter_boxplot_styling.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20using_20a_20qscrollbar_20together_20with_20jkqtplotter_77',['Example (JKQTPlotter): Using a QScrollbar together with JKQtPlotter',['../_j_k_q_t_plotter_u_i_scrollbar.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20vector_20field_20plot_20example_78',['Example JKQTPlotter : Vector Field Plot Example',['../_j_k_q_t_p_parametrized_vector_field_graph_example.html',1,'Example (JKQTPlotter): Vector Field Plot Example'],['../_j_k_q_t_plotter_vector_field_example.html',1,'Example (JKQTPlotter): Vector Field Plot Example']]],
  ['example_20jkqtplotter_20_3a_20very_20simple_20line_20graph_79',['Example (JKQTPlotter): Very simple line-graph',['../_j_k_q_t_plotter_simple_test.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20very_20simple_20scatter_20graph_80',['Example (JKQTPlotter): Very simple scatter-graph',['../_j_k_q_t_plotterscatter.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20violin_20plots_81',['Example (JKQTPlotter): Violin Plots',['../_j_k_q_t_plotter_violinplot_graphs.html',1,'exampleTutorialProjects']]],
  ['example_20jkqtplotter_20_3a_20wiggle_20plots_82',['Example (JKQTPlotter): Wiggle Plots',['../_j_k_q_t_plotter_wiggle_plots.html',1,'exampleTutorialProjects']]],
  ['example_20of_20usage_83',['Simple Example of Usage',['../class_j_k_q_t_p_math_parser.html#jkmp_example',1,'']]],
  ['example_20projects_84',['Example Projects',['../class_j_k_q_t_math_text.html#JKQTMathTextExamples',1,'']]],
  ['example_20styles_85',['Some Example Styles',['../_j_k_q_t_plotter_styling.html#autotoc_md97',1,'']]],
  ['example_20tutorial_20projects_86',['Example &amp;amp; Tutorial Projects',['../example_tutorial_projects.html',1,'']]],
  ['examples_87',['More Complex Examples',['../example_tutorial_projects.html#jkqtp_extut_complexexamples',1,'']]],
  ['examples_20for_20cmake_20build_20system_88',['Examples for CMake Build System',['../example_tutorial_projects.html#jkqtp_extut_cmake_build',1,'']]],
  ['examples_20for_20data_20management_20statistics_89',['Examples for Data Management &amp;amp; Statistics',['../example_tutorial_projects.html#jkqtp_extut_datamanagement',1,'']]],
  ['examples_20for_20different_20plot_20data_20styles_90',['Examples for Different Plot Data Styles',['../example_tutorial_projects.html#jkqtp_extut_plotstyles',1,'']]],
  ['examples_20for_20geometric_20forms_20arrows_20annotaions_91',['Examples for Geometric Forms, Arrows, Annotaions ...',['../example_tutorial_projects.html#jkqtp_extut_geometric',1,'']]],
  ['examples_20for_20gui_20tools_92',['Examples for GUI Tools',['../example_tutorial_projects.html#jkqtp_extut_guitools',1,'']]],
  ['examples_20for_20image_20data_20plots_93',['Examples for Image data Plots',['../example_tutorial_projects.html#jkqtp_extut_plotimagedata',1,'']]],
  ['examples_20for_20jkqtfastplotter_94',['DEPRECATED: Examples for JKQTFastPlotter',['../example_tutorial_projects.html#jkqtp_extut_jkqtfastplotter',1,'']]],
  ['examples_20for_20jkqtmathtext_95',['Examples for JKQTMathText',['../example_tutorial_projects.html#jkqtp_extut_jkqtmathtext',1,'']]],
  ['examples_20for_20layout_20styling_96',['Examples for Layout &amp;amp; Styling',['../example_tutorial_projects.html#jkqtp_extut_guitoolslayout',1,'']]],
  ['examples_20for_20special_20use_20cases_97',['Examples for special Use-Cases',['../example_tutorial_projects.html#jkqtp_extut_specialusecasesexamples',1,'']]],
  ['examples_20for_20styling_20the_20plot_20keys_20axes_98',['Examples for Styling the Plot, Keys, Axes, ...',['../example_tutorial_projects.html#jkqtp_extut_keyaxesstyles',1,'']]],
  ['examples_20tutorials_20for_20jkqtplotter_99',['Examples &amp;amp; Tutorials for JKQTPlotter',['../example_tutorial_projects.html#jkqtp_extut_jkqtplotter',1,'']]],
  ['existing_20jkqtplotter_100',['Apply a new Style to an Existing JKQTPlotter',['../_j_k_q_t_plotter_styling.html#autotoc_md96',1,'']]],
  ['existing_20rows_101',['Iterator-based Column Data Access To Existing Rows',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md38',1,'']]],
  ['explicit_20whitespaces_102',['Explicit Whitespaces',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXWhitespace',1,'']]],
  ['explorer_103',['Example (JKQTPlotter): Mandelbrot Set Explorer',['../_j_k_q_t_plotter_mandelbrot.html',1,'exampleTutorialProjects']]],
  ['exporting_104',['Printing, Saving &amp;amp; Exporting',['../class_j_k_q_t_base_plotter.html#jkqtbaseplotter_dataexport_print',1,'']]],
  ['exporting_20graph_20data_105',['Exporting Graph Data',['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_dataexport',1,'']]],
  ['expressions_106',['expressions',['../class_j_k_q_t_p_c_s_s_parser.html#jkqtpcss_ebnf',1,'EBNF definition of the parsed expressions'],['../class_j_k_q_t_p_math_parser.html#jkmp_ebnf',1,'EBNF definition of the parsed expressions']]],
  ['external_20containers_20into_20jkqtpdatastore_107',['Copying Data from External COntainers into JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md16',1,'']]],
  ['external_20data_20in_20a_20column_20of_20the_20jkqtpdatastore_108',['Reference External Data in a column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md20',1,'']]]
];
