var searchData=
[
  ['generating_20a_20dataset_20for_20grouped_20barcharts_0',['Generating a Dataset for Grouped Barcharts',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md31',1,'']]],
  ['generating_20a_20test_20dataset_1',['Generating a test Dataset',['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md117',1,'']]],
  ['generating_20columns_20preinitialized_20columns_2',['Generating Columns Preinitialized Columns',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md25',1,'']]],
  ['generating_20demo_20plots_20of_20geometric_20objects_20for_20documentation_3',['Example (JKQTPlotter): Generating Demo-Plots of Geometric Objects for Documentation',['../_j_k_q_t_plotter_geometric_graphs_simple.html',1,'exampleTutorialProjects']]],
  ['generating_20different_20sets_20of_20random_20numbers_4',['Generating different sets of random numbers',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md48',1,'Generating different sets of random numbers'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html#autotoc_md57',1,'Generating different sets of random numbers']]],
  ['generating_20non_20initialized_20columns_20and_20filling_20them_5',['Generating Non-Initialized Columns and Filling Them',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md24',1,'']]],
  ['generation_20deletion_6',['Column Generation/Deletion',['../class_j_k_q_t_p_datastore.html#jkqtpdatastore_column_management_generation',1,'']]],
  ['generic_20configuring_20building_7',['Generic Configuring&amp;amp;Building',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_MAKEFILE',1,'']]],
  ['geometric_20forms_20arrows_20annotaions_8',['Examples for Geometric Forms, Arrows, Annotaions ...',['../example_tutorial_projects.html#jkqtp_extut_geometric',1,'']]],
  ['geometric_20objects_9',['Example (JKQTPlotter): Plotting Geometric Objects',['../_j_k_q_t_plotter_geometric_graphs.html',1,'exampleTutorialProjects']]],
  ['geometric_20objects_20for_20documentation_10',['Example (JKQTPlotter): Generating Demo-Plots of Geometric Objects for Documentation',['../_j_k_q_t_plotter_geometric_graphs_simple.html',1,'exampleTutorialProjects']]],
  ['geometrical_20forms_11',['Drawing Geometrical Forms',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md108',1,'']]],
  ['gimmick_3a_20animating_20a_20contour_20plot_12',['Gimmick: Animating a Contour Plot',['../_j_k_q_t_plotter_contour_plot.html#autotoc_md15',1,'']]],
  ['global_20system_20wide_20settings_13',['Global/System-wide Settings',['../_j_k_q_t_plotter_styling.html#autotoc_md95',1,'']]],
  ['graph_14',['Graph',['../class_j_k_q_t_base_plotter.html#jkqtbaseplotter_appearance_and_style',1,'Appearance &amp; Styling of the Graph'],['../_j_k_q_t_plotter_param_scatter_image.html',1,'Example (JKQTPlotter): Draw an Artistic Image with a Parametrized Scatter Graph'],['../_j_k_q_t_plotter_image_plot_q_image_r_g_b.html',1,'Example (JKQTPlotter): QImage as a Graph']]],
  ['graph_15',['graph',['../_j_k_q_t_plotter_simple_test.html',1,'Example (JKQTPlotter): Very simple line-graph'],['../_j_k_q_t_plotterscatter.html',1,'Example (JKQTPlotter): Very simple scatter-graph']]],
  ['graph_20class_20structure_16',['Graph Class Structure',['../group__jkqtplotter__graphsgroup__classstructure.html#jkqtplotter_graphsgroup_classstructure_basics',1,'']]],
  ['graph_20data_17',['Exporting Graph Data',['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_dataexport',1,'']]],
  ['graph_20keys_20legends_18',['Graph Keys (Legends)',['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_key',1,'']]],
  ['graph_20labels_20example_19',['Example (JKQTPlotter): Simple Graph Labels Example',['../_j_k_q_t_plotter_graph_labels_example.html',1,'exampleTutorialProjects']]],
  ['graph_20visibility_20via_20context_20menu_20',['Switching Graph Visibility via Context Menu',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md101',1,'']]],
  ['graph_20with_20custom_20symbols_21',['graph with custom symbols',['../_j_k_q_t_plotterparamscatter_custom_symbol.html',1,'Example (JKQTPlotter): Parametrized Scatter-graph with custom symbols'],['../_j_k_q_t_plotterscatter_custom_symbol.html',1,'Example (JKQTPlotter): Scatter-graph with custom symbols']]],
  ['graph_20with_20different_20symbols_20and_20line_20styles_22',['Example (JKQTPlotter): Line Graph with Different Symbols and Line Styles',['../_j_k_q_t_plotter_symbols_and_styles.html',1,'exampleTutorialProjects']]],
  ['graph_20with_20error_20bars_23',['Example (JKQTPlotter): Simple line-graph with error bars',['../_j_k_q_t_plotter_symbols_errors.html',1,'exampleTutorialProjects']]],
  ['graph_20with_20live_20data_20speed_20test_24',['Example (JKQTPlotter): Simple line-graph with live-data (speed test)',['../_j_k_q_t_plotter_speed_test.html',1,'exampleTutorialProjects']]],
  ['graph_20with_20logarithmic_20y_20axis_25',['Example (JKQTPlotter): Line Graph with Logarithmic y-axis',['../_j_k_q_t_plotter_log_axes.html',1,'exampleTutorialProjects']]],
  ['graph_20with_20parametrized_20symbols_20colors_26',['Example (JKQTPlotter): Scatter Graph with Parametrized Symbols/Colors',['../_j_k_q_t_plotter_param_scatter.html',1,'exampleTutorialProjects']]],
  ['graphs_27',['Graphs',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md35',1,'Dataset for XY Scatter Graphs'],['../_j_k_q_t_plotter_function_plots.html',1,'Example (JKQTPlotter): Plotting Mathematical Functions as Line Graphs'],['../_j_k_q_t_plotter_eval_curves.html',1,'Example (JKQTPlotter): Plotting Parametric Mathematical Curves as Line Graphs'],['../_j_k_q_t_plotter_parsed_function_plot.html',1,'Example (JKQTPlotter): Plotting Parsed Mathematical Functions as Line Graphs'],['../group__jkqtplotter__graphsgroup__classstructure.html#jkqtplotter_graphsgroup_classstructure_mixins',1,'Mix-In Classes for Graphs'],['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_saveprint',1,'Saving and Printing Graphs'],['../class_j_k_q_t_p_financial_graph.html#JKQTPFinancialGraphStyling',1,'Styling the Financial Graphs']]],
  ['graphs_20side_20by_20side_28',['Several Financial Graphs side-by-side',['../class_j_k_q_t_p_financial_graph.html#JKQTPFinancialGraphSideBySide',1,'']]],
  ['graphs_20with_20error_20indicators_29',['Example (JKQTPlotter): Filled Graphs with Error Indicators',['../_j_k_q_t_plotter_filled_graphs_error_bars.html',1,'exampleTutorialProjects']]],
  ['graphs_20with_20x_20y_20errors_20from_20categorized_20data_30',['(Scatter-)Graphs with X/Y-errors from Categorized Data',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md34',1,'']]],
  ['greek_20letters_31',['Greek Letters',['../group__jkqtmathtext__supportedlatexsymbols.html#jkqtmathtext_supportedlatexsymbols_greek',1,'']]],
  ['grid_20printing_20declaring_20relations_20between_20plots_32',['Grid Printing/Declaring Relations between Plots',['../class_j_k_q_t_base_plotter.html#JKQTBASEPLOTTER_SYNCMULTIPLOT_GRIDPRINT',1,'']]],
  ['grids_33',['Grids',['../class_j_k_q_t_p_coordinate_axis.html#jkqtplotter_base_grids_baseelemenets',1,'Axis Ticks and Grids'],['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_grids_baseplotter',1,'Axis Ticks and Grids']]],
  ['group_20statistics_20with_20jkqtpdatastore_34',['Tutorial (JKQTPDatastore): 1-Dimensional Group Statistics with JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html',1,'exampleTutorialProjects']]],
  ['grouped_20barcharts_35',['Generating a Dataset for Grouped Barcharts',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md31',1,'']]],
  ['grouped_20statistics_20for_20a_20barchart_36',['Calculating Grouped Statistics for a Barchart',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md32',1,'']]],
  ['grouped_20statistics_20for_20a_20boxplot_37',['Calculating Grouped Statistics for a Boxplot',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md33',1,'']]],
  ['guarantees_38',['Thread-Safety/Re-Entrancy Guarantees',['../class_j_k_q_t_math_text.html#JKQTMathTextUsageThreadSafety',1,'']]],
  ['gui_39',['Main Program of the Example (GUI)',['../_j_k_q_t_plotter_image_plot_user_palette.html#autotoc_md82',1,'']]],
  ['gui_20features_40',['User-Interactions/GUI Features',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERINTERACTION',1,'']]],
  ['gui_20tools_41',['Examples for GUI Tools',['../example_tutorial_projects.html#jkqtp_extut_guitools',1,'']]]
];
