var searchData=
[
  ['weighted_20linear_20regression_0',['Weighted Linear Regression',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html#autotoc_md44',1,'']]],
  ['what_20s_20new_20release_20notes_20versions_1',['What&apos;s New (Release Notes/Versions)',['../page_whatsnew.html',1,'']]],
  ['wheel_20event_20occurs_2',['Actions When a Mouse Wheel Event Occurs',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSEWHEEL',1,'']]],
  ['when_20a_20mouse_20wheel_20event_20occurs_3',['Actions When a Mouse Wheel Event Occurs',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSEWHEEL',1,'']]],
  ['when_20dragging_20the_20mouse_4',['Actions When Dragging the Mouse',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSEDRAG',1,'']]],
  ['when_20setting_20up_20plots_5',['Performance Considerations when Setting up Plots',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_PERFORMACEWHILESETUP',1,'']]],
  ['whitespaces_6',['Explicit Whitespaces',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXWhitespace',1,'']]],
  ['wide_20settings_7',['Global/System-wide Settings',['../_j_k_q_t_plotter_styling.html#autotoc_md95',1,'']]],
  ['widget_8',['Fast Resizing of a Plot Widget',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_FASTRESIZING',1,'']]],
  ['width_9',['Synchronizing Axis Range &amp;amp; Plot Width',['../class_j_k_q_t_base_plotter.html#JKQTBASEPLOTTER_SYNCMULTIPLOT_SYNC',1,'']]],
  ['wiggle_20plot_20using_20jkqtpfilledcurvexgraph_10',['Plot red/blue wiggle plot using &lt;span class=&quot;tt&quot;&gt;JKQTPFilledCurveXGraph&lt;/span&gt;',['../_j_k_q_t_plotter_wiggle_plots.html#autotoc_md116',1,'']]],
  ['wiggle_20plot_20using_20jkqtpfilledcurveygraph_20in_20a_20seismographic_20style_11',['Plot black/transparent wiggle plot using &lt;span class=&quot;tt&quot;&gt;JKQTPFilledCurveYGraph&lt;/span&gt; in a &quot;seismographic style&quot;',['../_j_k_q_t_plotter_wiggle_plots.html#autotoc_md119',1,'']]],
  ['wiggle_20plots_12',['Example (JKQTPlotter): Wiggle Plots',['../_j_k_q_t_plotter_wiggle_plots.html',1,'exampleTutorialProjects']]],
  ['with_20a_20parametrized_20scatter_20graph_13',['Example (JKQTPlotter): Draw an Artistic Image with a Parametrized Scatter Graph',['../_j_k_q_t_plotter_param_scatter_image.html',1,'exampleTutorialProjects']]],
  ['with_20axes_20through_20origin_14',['Example (JKQTPlotter): Plot With Axes through Origin',['../_j_k_q_t_plotter_geometric_coordinate_axis0.html',1,'exampleTutorialProjects']]],
  ['with_20cmake_15',['with CMake',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_CONFIG',1,'Configuring a Build with CMake'],['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_INSTALL',1,'Installing with CMake'],['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_RUN',1,'Running a Build with CMake']]],
  ['with_20cmake_20s_20fetchcontent_20api_16',['Using JKQTPlotter with CMake&apos;s FetchContent-API',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_FETCHCONTENT',1,'']]],
  ['with_20custom_20draw_20functor_17',['Example (JKQTPlotter): Barchart With Custom Draw Functor',['../_j_k_q_t_plotter_barcharts_custom_draw_functor.html',1,'exampleTutorialProjects']]],
  ['with_20custom_20palettes_18',['Example (JKQTPlotter): Image Plots with Custom Palettes',['../_j_k_q_t_plotter_image_plot_user_palette.html',1,'exampleTutorialProjects']]],
  ['with_20custom_20symbols_19',['with custom symbols',['../_j_k_q_t_plotterparamscatter_custom_symbol.html',1,'Example (JKQTPlotter): Parametrized Scatter-graph with custom symbols'],['../_j_k_q_t_plotterscatter_custom_symbol.html',1,'Example (JKQTPlotter): Scatter-graph with custom symbols']]],
  ['with_20different_20symbols_20and_20line_20styles_20',['Example (JKQTPlotter): Line Graph with Different Symbols and Line Styles',['../_j_k_q_t_plotter_symbols_and_styles.html',1,'exampleTutorialProjects']]],
  ['with_20error_20bars_21',['Example (JKQTPlotter): Barchart With Error Bars',['../_j_k_q_t_plotter_barcharts_error_bars.html',1,'exampleTutorialProjects']]],
  ['with_20error_20bars_22',['Example (JKQTPlotter): Simple line-graph with error bars',['../_j_k_q_t_plotter_symbols_errors.html',1,'exampleTutorialProjects']]],
  ['with_20error_20indicators_23',['Example (JKQTPlotter): Filled Graphs with Error Indicators',['../_j_k_q_t_plotter_filled_graphs_error_bars.html',1,'exampleTutorialProjects']]],
  ['with_20functor_20fill_20mode_24',['Example (JKQTPlotter): Barchart With Functor Fill-Mode',['../_j_k_q_t_plotter_barcharts_functor_filling.html',1,'exampleTutorialProjects']]],
  ['with_20jkqtpdatastore_25',['with JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html',1,'Tutorial (JKQTPDatastore): 1-Dimensional Group Statistics with JKQTPDatastore'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html',1,'Tutorial (JKQTPDatastore): Advanced 1-Dimensional Statistics with JKQTPDatastore'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html',1,'Tutorial (JKQTPDatastore): Advanced 2-Dimensional Statistics with JKQTPDatastore']]],
  ['with_20jkqtplotter_26',['Example (JKQTPlotter): Using a QScrollbar together with JKQtPlotter',['../_j_k_q_t_plotter_u_i_scrollbar.html',1,'exampleTutorialProjects']]],
  ['with_20live_20data_20speed_20test_27',['Example (JKQTPlotter): Simple line-graph with live-data (speed test)',['../_j_k_q_t_plotter_speed_test.html',1,'exampleTutorialProjects']]],
  ['with_20logarithmic_20y_20axis_28',['Example (JKQTPlotter): Line Graph with Logarithmic y-axis',['../_j_k_q_t_plotter_log_axes.html',1,'exampleTutorialProjects']]],
  ['with_20modifier_20datat_29',['Example (JKQTPlotter): Simple math image plot with modifier datat',['../_j_k_q_t_plotter_image_plot_modifier.html',1,'exampleTutorialProjects']]],
  ['with_20outliers_30',['Boxplots with Outliers',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md52',1,'']]],
  ['with_20parameters_31',['Simple C++ inline function with Parameters',['../_j_k_q_t_plotter_eval_curves.html#autotoc_md66',1,'']]],
  ['with_20parameters_32',['with parameters',['../_j_k_q_t_plotter_parsed_function_plot.html#autotoc_md88',1,'Plotting with parameters'],['../_j_k_q_t_plotter_function_plots.html#autotoc_md71',1,'Simple C++ inline function with parameters']]],
  ['with_20parametrized_20symbols_20colors_33',['Example (JKQTPlotter): Scatter Graph with Parametrized Symbols/Colors',['../_j_k_q_t_plotter_param_scatter.html',1,'exampleTutorialProjects']]],
  ['with_20support_20for_20arrows_34',['Classes with support for arrows',['../_j_k_q_t_plotter_geometric_arrows.html#autotoc_md78',1,'']]],
  ['with_20the_20mouse_35',['Zooming with the Mouse',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md105',1,'']]],
  ['with_20the_20statistics_20library_36',['Tutorial (JKQTPDatastore): Regression Analysis (with the Statistics Library)',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html',1,'exampleTutorialProjects']]],
  ['with_20transfer_20of_20ownership_37',['Referencing with Transfer of Ownership',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md22',1,'']]],
  ['with_20two_20color_20fill_20mode_38',['Example (JKQTPlotter): Barchart With Two-Color Fill-Mode',['../_j_k_q_t_plotter_barcharts_two_color_filling.html',1,'exampleTutorialProjects']]],
  ['with_20visual_20studio_20msvc_39',['Configuring&amp;amp;Building with Visual Studio/MSVC',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_VSTUDIO',1,'']]],
  ['with_20x_20y_20errors_20from_20categorized_20data_40',['(Scatter-)Graphs with X/Y-errors from Categorized Data',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md34',1,'']]],
  ['within_20a_20qlabel_20class_20jkqtmathtextlabel_41',['Usage within a QLabel class JKQTMathTextLabel',['../class_j_k_q_t_math_text.html#JKQTMathTextUsageQLabel',1,'']]],
  ['without_20transfer_20of_20ownership_42',['Referencing without transfer of ownership',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md21',1,'']]],
  ['without_20use_20of_20central_20jkqtdatastore_43',['Example (JKQTPlotter): Simple math image plot without use of central JKQTdatastore',['../_j_k_q_t_plotter_image_plot_no_datastore.html',1,'exampleTutorialProjects']]],
  ['working_44',['Internal Working',['../class_j_k_q_t_p_datastore.html#jkqtpdatastore_internals',1,'']]],
  ['workings_45',['Inner Workings',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md99',1,'']]],
  ['works_46',['How it works',['../_j_k_q_t_plotter_mandelbrot.html#autotoc_md84',1,'']]]
];
