var searchData=
[
  ['image_0',['image',['../_j_k_q_t_plotter_image_plot_c_img.html',1,'Example (JKQTPlotter): Simple math image plot, showin a 1-channel CImg image'],['../_j_k_q_t_plotter_image_plot_r_g_b_c_img.html',1,'Example (JKQTPlotter): Simple math image plot, showing a 3-channel CImg image']]],
  ['image_20column_1',['Image Column',['../class_j_k_q_t_p_datastore.html#jkqtpdatastore_column_management_images',1,'']]],
  ['image_20data_20plots_2',['Examples for Image data Plots',['../example_tutorial_projects.html#jkqtp_extut_plotimagedata',1,'']]],
  ['image_20plot_3',['Example (JKQTPlotter): Simple Math RGB/CMY Image Plot',['../_j_k_q_t_plotter_r_g_b_image_plot.html',1,'exampleTutorialProjects']]],
  ['image_20plot_4',['Example (JKQTPlotter): Simple math image plot',['../_j_k_q_t_plotter_image_plot.html',1,'exampleTutorialProjects']]],
  ['image_20plot_20showin_20a_201_20channel_20cimg_20image_5',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel CImg image',['../_j_k_q_t_plotter_image_plot_c_img.html',1,'exampleTutorialProjects']]],
  ['image_20plot_20showin_20a_201_20channel_20opencv_20cv_3a_3amat_6',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_open_c_v.html',1,'exampleTutorialProjects']]],
  ['image_20plot_20showing_20a_203_20channel_20cimg_20image_7',['Example (JKQTPlotter): Simple math image plot, showing a 3-channel CImg image',['../_j_k_q_t_plotter_image_plot_r_g_b_c_img.html',1,'exampleTutorialProjects']]],
  ['image_20plot_20showing_20a_203_20channel_20opencv_20cv_3a_3amat_8',['Example (JKQTPlotter): Simple RGB image plot, showing a 3-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_r_g_b_open_c_v.html',1,'exampleTutorialProjects']]],
  ['image_20plot_20with_20modifier_20datat_9',['Example (JKQTPlotter): Simple math image plot with modifier datat',['../_j_k_q_t_plotter_image_plot_modifier.html',1,'exampleTutorialProjects']]],
  ['image_20plot_20without_20use_20of_20central_20jkqtdatastore_10',['Example (JKQTPlotter): Simple math image plot without use of central JKQTdatastore',['../_j_k_q_t_plotter_image_plot_no_datastore.html',1,'exampleTutorialProjects']]],
  ['image_20plots_20with_20custom_20palettes_11',['Example (JKQTPlotter): Image Plots with Custom Palettes',['../_j_k_q_t_plotter_image_plot_user_palette.html',1,'exampleTutorialProjects']]],
  ['image_20with_20a_20parametrized_20scatter_20graph_12',['Example (JKQTPlotter): Draw an Artistic Image with a Parametrized Scatter Graph',['../_j_k_q_t_plotter_param_scatter_image.html',1,'exampleTutorialProjects']]],
  ['images_13',['2D-Datasets and Images',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md28',1,'']]],
  ['implementation_20details_14',['Implementation Details',['../class_j_k_q_t_p_base_key.html#JKQTPBaseKey_ImplementationDetails',1,'']]],
  ['improvements_20bugfixes_15',['V4.0.0: Qt6 compatibility &amp;amp; diverse improvements + bugfixes',['../page_whatsnew.html#page_whatsnew_V4_0_0',1,'']]],
  ['impulse_20plots_16',['Example (JKQTPlotter): Simple impulse plots',['../_j_k_q_t_plotter_impulse_plots.html',1,'exampleTutorialProjects']]],
  ['in_20a_20column_20of_20the_20jkqtpdatastore_17',['Reference External Data in a column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md20',1,'']]],
  ['in_20a_20seismographic_20style_18',['Plot black/transparent wiggle plot using &lt;span class=&quot;tt&quot;&gt;JKQTPFilledCurveYGraph&lt;/span&gt; in a &quot;seismographic style&quot;',['../_j_k_q_t_plotter_wiggle_plots.html#autotoc_md119',1,'']]],
  ['in_20classes_20for_20graphs_19',['Mix-In Classes for Graphs',['../group__jkqtplotter__graphsgroup__classstructure.html#jkqtplotter_graphsgroup_classstructure_mixins',1,'']]],
  ['in_20different_20styles_20',['Example (JKQTPlotter): Step Line Plots in Different Styles',['../_j_k_q_t_plotter_special_step_line_plot.html',1,'exampleTutorialProjects']]],
  ['in_20jkqtplotter_21',['in JKQTPlotter',['../licensepage.html#extlicense_sec',1,'Licenses of 3rd Party Products Contained in JKQTPlotter'],['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION',1,'Mouse-Interaction in JKQTPlotter']]],
  ['in_20jkqtplotter_22',['Tutorial (JKQTPlotter): User-Interactions in JKQtPlotter',['../_j_k_q_t_plotter_user_interaction.html',1,'exampleTutorialProjects']]],
  ['in_20qtcreator_23',['DEPRECATED: QMake in QTCreator',['../page_buildinstructions__q_m_a_k_e.html#page_buildinstructions_QMAKEQTCREATOR',1,'']]],
  ['in_20the_20qt_20form_20designer_24',['in the Qt Form Designer',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USEQTCREATOR',1,'How to use JKQTPlotter in the Qt Form Designer'],['../_j_k_q_t_plotter_qt_creator.html#autotoc_md91',1,'Instructions on how to use JKQTPlotter in the Qt Form Designer']]],
  ['include_20project_25',['DEPRECATED: QMake Include Project',['../page_buildinstructions__q_m_a_k_e.html#page_buildinstructions_QMAKEINCLUDE',1,'']]],
  ['indicators_26',['Example (JKQTPlotter): Filled Graphs with Error Indicators',['../_j_k_q_t_plotter_filled_graphs_error_bars.html',1,'exampleTutorialProjects']]],
  ['initial_20release_27',['v2015.10: Initial Release',['../page_whatsnew.html#page_whatsnew_V2015_10',1,'']]],
  ['initialized_20columns_20and_20filling_20them_28',['Generating Non-Initialized Columns and Filling Them',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md24',1,'']]],
  ['inline_20function_29',['inline function',['../_j_k_q_t_plotter_eval_curves.html#autotoc_md65',1,'Simple C++ inline function'],['../_j_k_q_t_plotter_function_plots.html#autotoc_md70',1,'Simple C++ inline function']]],
  ['inline_20function_20with_20parameters_30',['Simple C++ inline function with Parameters',['../_j_k_q_t_plotter_eval_curves.html#autotoc_md66',1,'']]],
  ['inline_20function_20with_20parameters_31',['Simple C++ inline function with parameters',['../_j_k_q_t_plotter_function_plots.html#autotoc_md71',1,'']]],
  ['inner_20workings_32',['Inner Workings',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md99',1,'']]],
  ['inserter_20for_20columns_33',['Back-Inserter for Columns',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md39',1,'']]],
  ['inside_20a_20qt_20user_20interface_20designer_20ui_20file_34',['Tutorial (JKQTPlotter): Using a JKQTPlotter inside a Qt User Interface Designer (UI) File',['../_j_k_q_t_plotter_qt_creator.html',1,'exampleTutorialProjects']]],
  ['installing_20with_20cmake_35',['Installing with CMake',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_INSTALL',1,'']]],
  ['instructions_36',['Instructions',['../page_buildinstructions.html',1,'Build Instructions'],['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXFrac',1,'Fraction Type Instructions'],['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXMatrix',1,'Matrix/Array Type Instructions']]],
  ['instructions_20on_20how_20to_20use_20jkqtplotter_20in_20the_20qt_20form_20designer_37',['Instructions on how to use JKQTPlotter in the Qt Form Designer',['../_j_k_q_t_plotter_qt_creator.html#autotoc_md91',1,'']]],
  ['interaction_20in_20jkqtplotter_38',['Mouse-Interaction in JKQTPlotter',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION',1,'']]],
  ['interactions_39',['Available User-Interactions',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md100',1,'']]],
  ['interactions_20gui_20features_40',['User-Interactions/GUI Features',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERINTERACTION',1,'']]],
  ['interactions_20in_20jkqtplotter_41',['Tutorial (JKQTPlotter): User-Interactions in JKQtPlotter',['../_j_k_q_t_plotter_user_interaction.html',1,'exampleTutorialProjects']]],
  ['interface_42',['Interface',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md29',1,'Iterator Interface'],['../class_j_k_q_t_p_datastore.html#jkqtpdatastore_column_management_iterators',1,'Iterator Interface']]],
  ['interface_20designer_20ui_20file_43',['Tutorial (JKQTPlotter): Using a JKQTPlotter inside a Qt User Interface Designer (UI) File',['../_j_k_q_t_plotter_qt_creator.html',1,'exampleTutorialProjects']]],
  ['internal_20data_20management_44',['JKQTPDatastore-internal Data Management',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md23',1,'']]],
  ['internal_20working_45',['Internal Working',['../class_j_k_q_t_p_datastore.html#jkqtpdatastore_internals',1,'']]],
  ['into_20a_20column_20of_20the_20jkqtpdatastore_46',['Copy Data from a C-array into a Column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md18',1,'']]],
  ['into_20a_20column_20of_20the_20jkqtpdatastore_47',['Copy Data from a Vector into a column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md17',1,'']]],
  ['into_20a_20jkqtpdatastore_48',['Copy Data from a Map into a JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md19',1,'']]],
  ['into_20jkqtpdatastore_49',['Copying Data from External COntainers into JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md16',1,'']]],
  ['introduction_20and_20usage_50',['Introduction and Usage',['../_j_k_q_t_plotter_mandelbrot.html#autotoc_md83',1,'']]],
  ['inverted_20coordinate_20axes_51',['Inverted Coordinate Axes',['../class_j_k_q_t_p_coordinate_axis.html#jkqtplotter_coordinateaxes_inverted',1,'']]],
  ['it_20works_52',['How it works',['../_j_k_q_t_plotter_mandelbrot.html#autotoc_md84',1,'']]],
  ['iterator_20based_20column_20data_20access_20to_20existing_20rows_53',['Iterator-based Column Data Access To Existing Rows',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md38',1,'']]],
  ['iterator_20based_20usage_20of_20jkqtpdatastore_54',['Tutorial (JKQTPDatastore): Iterator-Based usage of JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html',1,'exampleTutorialProjects']]],
  ['iterator_20interface_55',['Iterator Interface',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md29',1,'Iterator Interface'],['../class_j_k_q_t_p_datastore.html#jkqtpdatastore_column_management_iterators',1,'Iterator Interface']]],
  ['iterators_56',['Special Properties of the JKQTPDatastore-Iterators',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md41',1,'']]]
];
