var searchData=
[
  ['random_20numbers_0',['random numbers',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md48',1,'Generating different sets of random numbers'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html#autotoc_md57',1,'Generating different sets of random numbers']]],
  ['range_20plot_20width_1',['Synchronizing Axis Range &amp;amp; Plot Width',['../class_j_k_q_t_base_plotter.html#JKQTBASEPLOTTER_SYNCMULTIPLOT_SYNC',1,'']]],
  ['ratios_2',['Aspect Ratios',['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_aspectratios',1,'']]],
  ['re_20entrancy_20guarantees_3',['Thread-Safety/Re-Entrancy Guarantees',['../class_j_k_q_t_math_text.html#JKQTMathTextUsageThreadSafety',1,'']]],
  ['rectangles_4',['Rectangles',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md110',1,'']]],
  ['red_20blue_20wiggle_20plot_20using_20jkqtpfilledcurvexgraph_5',['Plot red/blue wiggle plot using &lt;span class=&quot;tt&quot;&gt;JKQTPFilledCurveXGraph&lt;/span&gt;',['../_j_k_q_t_plotter_wiggle_plots.html#autotoc_md116',1,'']]],
  ['reference_20external_20data_20in_20a_20column_20of_20the_20jkqtpdatastore_6',['Reference External Data in a column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md20',1,'']]],
  ['referencing_20with_20transfer_20of_20ownership_7',['Referencing with Transfer of Ownership',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md22',1,'']]],
  ['referencing_20without_20transfer_20of_20ownership_8',['Referencing without transfer of ownership',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md21',1,'']]],
  ['regression_9',['Regression',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html#autotoc_md43',1,'Robust Linear Regression'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html#autotoc_md42',1,'Simple Linear Regression'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html#autotoc_md44',1,'Weighted Linear Regression']]],
  ['regression_20analysis_20with_20the_20statistics_20library_10',['Tutorial (JKQTPDatastore): Regression Analysis (with the Statistics Library)',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html',1,'exampleTutorialProjects']]],
  ['regression_20models_11',['Linearizable Regression Models',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html#autotoc_md45',1,'']]],
  ['relations_20between_20plots_12',['Grid Printing/Declaring Relations between Plots',['../class_j_k_q_t_base_plotter.html#JKQTBASEPLOTTER_SYNCMULTIPLOT_GRIDPRINT',1,'']]],
  ['release_13',['v2015.10: Initial Release',['../page_whatsnew.html#page_whatsnew_V2015_10',1,'']]],
  ['release_20notes_20versions_14',['What&apos;s New (Release Notes/Versions)',['../page_whatsnew.html',1,'']]],
  ['releases_20versions_15',['Todo List für Future Releases/Versions',['../page_todo.html',1,'']]],
  ['reporting_20a_20vulnerability_16',['Reporting a Vulnerability',['../md__s_e_c_u_r_i_t_y.html#autotoc_md125',1,'']]],
  ['request_20process_17',['Pull Request Process',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md1',1,'']]],
  ['resizing_20of_20a_20plot_20widget_18',['Fast Resizing of a Plot Widget',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_FASTRESIZING',1,'']]],
  ['responsibilities_19',['Responsibilities',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md3',1,'Our Responsibilities'],['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html#autotoc_md9',1,'Our Responsibilities']]],
  ['result_20of_20parsing_20and_20evaluation_3a_20',['result of parsing and evaluation:',['../class_j_k_q_t_p_math_parser.html#jkmp_resultsofparsing',1,'']]],
  ['rework_20of_20the_20library_21',['v2019.11: Major rework of the library',['../page_whatsnew.html#page_whatsnew_V2019_11',1,'']]],
  ['rgb_20cmy_20image_20plot_22',['Example (JKQTPlotter): Simple Math RGB/CMY Image Plot',['../_j_k_q_t_plotter_r_g_b_image_plot.html',1,'exampleTutorialProjects']]],
  ['rgb_20image_20plot_20showing_20a_203_20channel_20opencv_20cv_3a_3amat_23',['Example (JKQTPlotter): Simple RGB image plot, showing a 3-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_r_g_b_open_c_v.html',1,'exampleTutorialProjects']]],
  ['robust_20linear_20regression_24',['Robust Linear Regression',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html#autotoc_md43',1,'']]],
  ['roots_25',['Roots',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXRoots',1,'']]],
  ['rows_26',['Iterator-based Column Data Access To Existing Rows',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md38',1,'']]],
  ['rug_20plot_27',['Visualizing data as a Rug Plot',['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md118',1,'']]],
  ['ruler_20measurement_20tool_28',['Ruler/Measurement Tool',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md106',1,'']]],
  ['running_20a_20build_20with_20cmake_29',['Running a Build with CMake',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_RUN',1,'']]]
];
