var searchData=
[
  ['objects_0',['Example (JKQTPlotter): Plotting Geometric Objects',['../_j_k_q_t_plotter_geometric_graphs.html',1,'exampleTutorialProjects']]],
  ['objects_20for_20documentation_1',['Example (JKQTPlotter): Generating Demo-Plots of Geometric Objects for Documentation',['../_j_k_q_t_plotter_geometric_graphs_simple.html',1,'exampleTutorialProjects']]],
  ['occurs_2',['Actions When a Mouse Wheel Event Occurs',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSEWHEEL',1,'']]],
  ['of_203rd_20party_20products_20contained_20in_20jkqtplotter_3',['Licenses of 3rd Party Products Contained in JKQTPlotter',['../licensepage.html#extlicense_sec',1,'']]],
  ['of_20a_20plot_20widget_4',['Fast Resizing of a Plot Widget',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_FASTRESIZING',1,'']]],
  ['of_20an_20equation_5',['Determining the size of an equation',['../class_j_k_q_t_math_text.html#JKQTMathTextSizing',1,'']]],
  ['of_20arrows_6',['Different types of arrows',['../_j_k_q_t_plotter_geometric_arrows.html#autotoc_md77',1,'']]],
  ['of_20bargraphs_7',['Data-Dependent Styling of Bargraphs',['../class_j_k_q_t_p_bar_graph_base.html#JKQTPBarGraphBaseDataDependentFilling',1,'']]],
  ['of_20boxplots_8',['Example (JKQTPlotter): Styling different aspects of boxplots',['../_j_k_q_t_plotter_boxplot_styling.html',1,'exampleTutorialProjects']]],
  ['of_20central_20jkqtdatastore_9',['Example (JKQTPlotter): Simple math image plot without use of central JKQTdatastore',['../_j_k_q_t_plotter_image_plot_no_datastore.html',1,'exampleTutorialProjects']]],
  ['of_20conduct_10',['Contributor Covenant Code of Conduct',['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html',1,'']]],
  ['of_20contents_11',['Table Of Contents',['../index.html#jkqtplottertic',1,'']]],
  ['of_20data_12',['Example (JKQTPlotter): Plotting a Statistical Distribution of Data',['../_j_k_q_t_plotter_distribution_plot.html',1,'exampleTutorialProjects']]],
  ['of_20errorindicators_13',['Example (JKQTPlotter): Different Types of Errorindicators',['../_j_k_q_t_plotter_error_bar_styles.html',1,'exampleTutorialProjects']]],
  ['of_20geometric_20objects_20for_20documentation_14',['Example (JKQTPlotter): Generating Demo-Plots of Geometric Objects for Documentation',['../_j_k_q_t_plotter_geometric_graphs_simple.html',1,'exampleTutorialProjects']]],
  ['of_20jkqtpdatastore_15',['of JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html',1,'Tutorial (JKQTPDatastore): Basic Usage of JKQTPDatastore'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html',1,'Tutorial (JKQTPDatastore): Iterator-Based usage of JKQTPDatastore']]],
  ['of_20jkqtplotter_16',['of JKQTPlotter',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_BASICUSAGE',1,'Basic Usage of JKQTPlotter'],['../class_j_k_q_t_plotter.html#JKQTPLOTTER_CONTEXTMENU',1,'Context Menu of JKQTPlotter'],['../class_j_k_q_t_plotter.html#JKQTPLOTTER_SPECIALCONTEXTMENU',1,'Special (User-Defined) Context Menu of JKQTPlotter'],['../class_j_k_q_t_plotter.html#JKQTPLOTTER_TOOLBAR',1,'Toolbar of JKQTPlotter']]],
  ['of_20ownership_17',['Referencing with Transfer of Ownership',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md22',1,'']]],
  ['of_20ownership_18',['Referencing without transfer of ownership',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md21',1,'']]],
  ['of_20parsing_20and_20evaluation_3a_19',['result of parsing and evaluation:',['../class_j_k_q_t_p_math_parser.html#jkmp_resultsofparsing',1,'']]],
  ['of_20random_20numbers_20',['of random numbers',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md48',1,'Generating different sets of random numbers'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html#autotoc_md57',1,'Generating different sets of random numbers']]],
  ['of_20the_20adaptive_20plotting_20algorithm_21',['Properties of the Adaptive Plotting Algorithm',['../_j_k_q_t_plotter_parsed_function_plot.html#autotoc_md90',1,'']]],
  ['of_20the_20example_20gui_22',['Main Program of the Example (GUI)',['../_j_k_q_t_plotter_image_plot_user_palette.html#autotoc_md82',1,'']]],
  ['of_20the_20full_20program_23',['of the full Program',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md37',1,'Screenshot of the full Program'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html#autotoc_md47',1,'Screenshot of the full Program'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md56',1,'Screenshot of the full Program'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html#autotoc_md61',1,'Screenshot of the full Program']]],
  ['of_20the_20graph_24',['Appearance &amp;amp; Styling of the Graph',['../class_j_k_q_t_base_plotter.html#jkqtbaseplotter_appearance_and_style',1,'']]],
  ['of_20the_20jkqtpdatastore_25',['of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md18',1,'Copy Data from a C-array into a Column of the JKQTPDatastore'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md17',1,'Copy Data from a Vector into a column of the JKQTPDatastore'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md20',1,'Reference External Data in a column of the JKQTPDatastore']]],
  ['of_20the_20jkqtpdatastore_20iterators_26',['Special Properties of the JKQTPDatastore-Iterators',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md41',1,'']]],
  ['of_20the_20library_27',['v2019.11: Major rework of the library',['../page_whatsnew.html#page_whatsnew_V2019_11',1,'']]],
  ['of_20the_20parsed_20expressions_28',['of the parsed expressions',['../class_j_k_q_t_p_c_s_s_parser.html#jkqtpcss_ebnf',1,'EBNF definition of the parsed expressions'],['../class_j_k_q_t_p_math_parser.html#jkmp_ebnf',1,'EBNF definition of the parsed expressions']]],
  ['of_20the_20plot_29',['Toolbar at the top of the Plot',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md102',1,'']]],
  ['of_20usage_30',['Simple Example of Usage',['../class_j_k_q_t_p_math_parser.html#jkmp_example',1,'']]],
  ['ohlc_20example_31',['Example (JKQTPlotter): Financial Chart (Candlestick/OHLC) Example',['../_j_k_q_t_plotter_financial_chart_example.html',1,'exampleTutorialProjects']]],
  ['on_20how_20to_20use_20jkqtplotter_20in_20the_20qt_20form_20designer_32',['Instructions on how to use JKQTPlotter in the Qt Form Designer',['../_j_k_q_t_plotter_qt_creator.html#autotoc_md91',1,'']]],
  ['on_20the_20mouse_20buttons_33',['Actions After (Double-)Clicks on the Mouse Buttons',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSECLICK',1,'']]],
  ['one_20column_20to_20calculate_20another_34',['Using Data from one Column to Calculate Another',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md27',1,'']]],
  ['opencv_20cv_3a_3amat_35',['OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_open_c_v.html',1,'Example (JKQTPlotter): Simple math image plot, showin a 1-channel OpenCV cv::Mat'],['../_j_k_q_t_plotter_image_plot_r_g_b_open_c_v.html',1,'Example (JKQTPlotter): Simple RGB image plot, showing a 3-channel OpenCV cv::Mat']]],
  ['operators_36',['Big Math Operators',['../group__jkqtmathtext__supportedlatexsymbols.html#jkqtmathtext_supportedlatexsymbols_bigmathop',1,'']]],
  ['origin_37',['Example (JKQTPlotter): Plot With Axes through Origin',['../_j_k_q_t_plotter_geometric_coordinate_axis0.html',1,'exampleTutorialProjects']]],
  ['other_20symbols_38',['Other Symbols',['../group__jkqtmathtext__supportedlatexsymbols.html#jkqtmathtext_supportedlatexsymbols_other',1,'']]],
  ['our_20pledge_39',['Our Pledge',['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html#autotoc_md7',1,'']]],
  ['our_20responsibilities_40',['Our Responsibilities',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md3',1,'Our Responsibilities'],['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html#autotoc_md9',1,'Our Responsibilities']]],
  ['our_20standards_41',['Our Standards',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md2',1,'Our Standards'],['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html#autotoc_md8',1,'Our Standards']]],
  ['out_20several_20plots_42',['Example (JKQTPlotter): Laying out Several Plots',['../_j_k_q_t_plotter_multi_plot_layout.html',1,'exampleTutorialProjects']]],
  ['outliers_43',['Outliers',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md52',1,'Boxplots with Outliers'],['../class_j_k_q_t_p_boxplot_vertical_graph.html#BoxplotOutliers',1,'Outliers']]],
  ['output_44',['Data Output',['../class_j_k_q_t_p_datastore.html#jkqtpdatastore_dataio',1,'']]],
  ['overbraces_45',['Undersetting, Oversetting, Underbraces, Overbraces ...',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXUnderOver',1,'']]],
  ['overlines_20strikeout_46',['Text Decoration: Underline, Overlines, Strikeout, ...',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXUnderlinesEtz',1,'']]],
  ['oversetting_20underbraces_20overbraces_47',['Undersetting, Oversetting, Underbraces, Overbraces ...',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXUnderOver',1,'']]],
  ['overview_48',['Overview',['../page_whatsnew.html#page_whatsnew_TRUNK_OVERVIEW',1,'trunk: Overview'],['../page_whatsnew.html#page_whatsnew_V2015_10_OVERVIEW',1,'v2015.10: Overview'],['../page_whatsnew.html#page_whatsnew_V2018_08_OVERVIEW',1,'v2018.08: Overview'],['../page_whatsnew.html#page_whatsnew_V2019_11_OVERVIEW',1,'v2019.11: Overview'],['../page_whatsnew.html#page_whatsnew_V4_0_0_OVERVIEW',1,'V4.0.0: Overview']]],
  ['ownership_49',['Referencing with Transfer of Ownership',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md22',1,'']]],
  ['ownership_50',['Referencing without transfer of ownership',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md21',1,'']]]
];
