var searchData=
[
  ['für_20future_20releases_20versions_0',['Todo List für Future Releases/Versions',['../page_todo.html',1,'']]],
  ['f_20x_1',['Plot Function f(x)',['../_j_k_q_t_plotter_parsed_function_plot.html#autotoc_md87',1,'']]],
  ['f_20y_2',['Plot Function f(y)',['../_j_k_q_t_plotter_parsed_function_plot.html#autotoc_md89',1,'']]],
  ['fast_20resizing_20of_20a_20plot_20widget_3',['Fast Resizing of a Plot Widget',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_FASTRESIZING',1,'']]],
  ['features_4',['Features',['../index.html#jkqtp_main_features',1,'Main Features'],['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERINTERACTION',1,'User-Interactions/GUI Features']]],
  ['fetchcontent_20api_5',['Using JKQTPlotter with CMake&apos;s FetchContent-API',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_FETCHCONTENT',1,'']]],
  ['fetchcontent_20example_6',['Example (JKQTPlotter): CMake FetchContent Example',['../_j_k_q_t_c_make_fetch_content_example.html',1,'exampleTutorialProjects']]],
  ['field_20plot_20example_7',['Field Plot Example',['../_j_k_q_t_p_parametrized_vector_field_graph_example.html',1,'Example (JKQTPlotter): Vector Field Plot Example'],['../_j_k_q_t_plotter_vector_field_example.html',1,'Example (JKQTPlotter): Vector Field Plot Example']]],
  ['file_8',['Tutorial (JKQTPlotter): Using a JKQTPlotter inside a Qt User Interface Designer (UI) File',['../_j_k_q_t_plotter_qt_creator.html',1,'exampleTutorialProjects']]],
  ['files_9',['Load Palettes from Files',['../_j_k_q_t_plotter_image_plot_user_palette.html#autotoc_md81',1,'']]],
  ['fill_20mode_10',['Fill Mode',['../_j_k_q_t_plotter_barcharts_functor_filling.html',1,'Example (JKQTPlotter): Barchart With Functor Fill-Mode'],['../_j_k_q_t_plotter_barcharts_two_color_filling.html',1,'Example (JKQTPlotter): Barchart With Two-Color Fill-Mode']]],
  ['fill_20styling_11',['Example (JKQTPlotter): Advanced Line and Fill Styling',['../_j_k_q_t_plotter_advanced_line_and_fill_styling.html',1,'exampleTutorialProjects']]],
  ['filled_20curve_20plots_12',['Example (JKQTPlotter): Filled Curve Plots',['../_j_k_q_t_plotter_filled_graphs.html',1,'exampleTutorialProjects']]],
  ['filled_20graphs_20with_20error_20indicators_13',['Example (JKQTPlotter): Filled Graphs with Error Indicators',['../_j_k_q_t_plotter_filled_graphs_error_bars.html',1,'exampleTutorialProjects']]],
  ['filling_20them_14',['Generating Non-Initialized Columns and Filling Them',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md24',1,'']]],
  ['final_20quickfit3_20compatible_20version_15',['v2018.08: Minor Modifications (Final QuickFit3-compatible Version)',['../page_whatsnew.html#page_whatsnew_V2018_08',1,'']]],
  ['financial_20chart_20candlestick_20ohlc_20example_16',['Example (JKQTPlotter): Financial Chart (Candlestick/OHLC) Example',['../_j_k_q_t_plotter_financial_chart_example.html',1,'exampleTutorialProjects']]],
  ['financial_20graphs_17',['Styling the Financial Graphs',['../class_j_k_q_t_p_financial_graph.html#JKQTPFinancialGraphStyling',1,'']]],
  ['financial_20graphs_20side_20by_20side_18',['Several Financial Graphs side-by-side',['../class_j_k_q_t_p_financial_graph.html#JKQTPFinancialGraphSideBySide',1,'']]],
  ['fira_20math_20fonts_20for_20jkqtmathtext_19',['Fira Math Fonts for JKQTMathText',['../licensepage.html#extlicense_firamath',1,'']]],
  ['fitting_20',['Polynom Fitting',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html#autotoc_md46',1,'']]],
  ['font_20definition_20syntax_21',['Font Definition Syntax',['../struct_j_k_q_t_math_text_font_specifier.html#JKQTMathTextFontSpecifier_specialSyntax',1,'']]],
  ['font_20names_22',['Special Font Names',['../struct_j_k_q_t_math_text_font_specifier.html#JKQTMathTextFontSpecifier_specialNames',1,'']]],
  ['font_20properties_23',['Font Properties',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXFontPropsFontProps',1,'']]],
  ['font_20selection_24',['Font Selection',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXFontPropsFonts',1,'']]],
  ['font_20sizes_25',['Font Sizes',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXFontPropsFontSizes',1,'']]],
  ['fonts_20for_20jkqtmathtext_26',['Fonts for JKQTMathText',['../licensepage.html#extlicense_firamath',1,'Fira Math Fonts for JKQTMathText'],['../licensepage.html#extlicense_xits',1,'XITS Fonts for JKQTMathText']]],
  ['for_20a_20barchart_27',['Calculating Grouped Statistics for a Barchart',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md32',1,'']]],
  ['for_20a_20boxplot_28',['Calculating Grouped Statistics for a Boxplot',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md33',1,'']]],
  ['for_20arrows_29',['Classes with support for arrows',['../_j_k_q_t_plotter_geometric_arrows.html#autotoc_md78',1,'']]],
  ['for_20cmake_20build_20system_30',['Examples for CMake Build System',['../example_tutorial_projects.html#jkqtp_extut_cmake_build',1,'']]],
  ['for_20columns_31',['Back-Inserter for Columns',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md39',1,'']]],
  ['for_20data_20management_20statistics_32',['Examples for Data Management &amp;amp; Statistics',['../example_tutorial_projects.html#jkqtp_extut_datamanagement',1,'']]],
  ['for_20different_20plot_20data_20styles_33',['Examples for Different Plot Data Styles',['../example_tutorial_projects.html#jkqtp_extut_plotstyles',1,'']]],
  ['for_20documentation_34',['Example (JKQTPlotter): Generating Demo-Plots of Geometric Objects for Documentation',['../_j_k_q_t_plotter_geometric_graphs_simple.html',1,'exampleTutorialProjects']]],
  ['for_20geometric_20forms_20arrows_20annotaions_35',['Examples for Geometric Forms, Arrows, Annotaions ...',['../example_tutorial_projects.html#jkqtp_extut_geometric',1,'']]],
  ['for_20graphs_36',['Mix-In Classes for Graphs',['../group__jkqtplotter__graphsgroup__classstructure.html#jkqtplotter_graphsgroup_classstructure_mixins',1,'']]],
  ['for_20grouped_20barcharts_37',['Generating a Dataset for Grouped Barcharts',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md31',1,'']]],
  ['for_20gui_20tools_38',['Examples for GUI Tools',['../example_tutorial_projects.html#jkqtp_extut_guitools',1,'']]],
  ['for_20image_20data_20plots_39',['Examples for Image data Plots',['../example_tutorial_projects.html#jkqtp_extut_plotimagedata',1,'']]],
  ['for_20jkqtfastplotter_40',['DEPRECATED: Examples for JKQTFastPlotter',['../example_tutorial_projects.html#jkqtp_extut_jkqtfastplotter',1,'']]],
  ['for_20jkqtmathtext_41',['for JKQTMathText',['../example_tutorial_projects.html#jkqtp_extut_jkqtmathtext',1,'Examples for JKQTMathText'],['../licensepage.html#extlicense_firamath',1,'Fira Math Fonts for JKQTMathText'],['../licensepage.html#extlicense_xits',1,'XITS Fonts for JKQTMathText']]],
  ['for_20jkqtpgeobeziercurve_42',['for JKQTPGeoBezierCurve',['../class_j_k_q_t_p_geo_bezier_curve.html#JKQTPGeoBezierCurveDrawMode',1,'DrawMode for JKQTPGeoBezierCurve'],['../class_j_k_q_t_p_geo_bezier_curve.html#JKQTPGeoBezierCurveDecorators',1,'Line-End Decorators for JKQTPGeoBezierCurve']]],
  ['for_20jkqtplotter_43',['for JKQTPlotter',['../example_tutorial_projects.html#jkqtp_extut_jkqtplotter',1,'Examples &amp; Tutorials for JKQTPlotter'],['../class_j_k_q_t_base_plotter.html#jkqtplotter_usage_baseplotter_in_widget',1,'JKQTBasePlotter as Basis for JKQTPlotter'],['../licensepage.html',1,'Licensing Terms for JKQTPlotter']]],
  ['for_20layout_20styling_44',['Examples for Layout &amp;amp; Styling',['../example_tutorial_projects.html#jkqtp_extut_guitoolslayout',1,'']]],
  ['for_20multi_20line_20text_45',['Environments for Multi-line text',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXTextAlignment',1,'']]],
  ['for_20special_20use_20cases_46',['Examples for special Use-Cases',['../example_tutorial_projects.html#jkqtp_extut_specialusecasesexamples',1,'']]],
  ['for_20styling_20the_20plot_20keys_20axes_47',['Examples for Styling the Plot, Keys, Axes, ...',['../example_tutorial_projects.html#jkqtp_extut_keyaxesstyles',1,'']]],
  ['for_20xy_20scatter_20graphs_48',['Dataset for XY Scatter Graphs',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md35',1,'']]],
  ['form_20class_20formwithjkqtplotter_49',['Form Class &lt;span class=&quot;tt&quot;&gt;FormWithJKQTPlotter&lt;/span&gt;',['../_j_k_q_t_plotter_qt_creator.html#autotoc_md92',1,'']]],
  ['form_20designer_50',['Form Designer',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USEQTCREATOR',1,'How to use JKQTPlotter in the Qt Form Designer'],['../_j_k_q_t_plotter_qt_creator.html#autotoc_md91',1,'Instructions on how to use JKQTPlotter in the Qt Form Designer']]],
  ['formatting_51',['Formatting',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXFormatting',1,'']]],
  ['forms_52',['Drawing Geometrical Forms',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md108',1,'']]],
  ['forms_20arrows_20annotaions_53',['Examples for Geometric Forms, Arrows, Annotaions ...',['../example_tutorial_projects.html#jkqtp_extut_geometric',1,'']]],
  ['formwithjkqtplotter_54',['Form Class &lt;span class=&quot;tt&quot;&gt;FormWithJKQTPlotter&lt;/span&gt;',['../_j_k_q_t_plotter_qt_creator.html#autotoc_md92',1,'']]],
  ['fraction_20type_20instructions_55',['Fraction Type Instructions',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXFrac',1,'']]],
  ['from_20a_20c_20array_20into_20a_20column_20of_20the_20jkqtpdatastore_56',['Copy Data from a C-array into a Column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md18',1,'']]],
  ['from_20a_20jkqtplotter_57',['QActions from a JKQTPlotter',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_ACTIONS',1,'']]],
  ['from_20a_20map_20into_20a_20jkqtpdatastore_58',['Copy Data from a Map into a JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md19',1,'']]],
  ['from_20a_20vector_20into_20a_20column_20of_20the_20jkqtpdatastore_59',['Copy Data from a Vector into a column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md17',1,'']]],
  ['from_20categorized_20data_60',['from Categorized Data',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md34',1,'(Scatter-)Graphs with X/Y-errors from Categorized Data'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md36',1,'Calculating x- and y-Errors from Categorized Data']]],
  ['from_20categorized_20data_61',['Barcharts &amp;amp; Boxplots from categorized data',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md30',1,'']]],
  ['from_20external_20containers_20into_20jkqtpdatastore_62',['Copying Data from External COntainers into JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md16',1,'']]],
  ['from_20files_63',['Load Palettes from Files',['../_j_k_q_t_plotter_image_plot_user_palette.html#autotoc_md81',1,'']]],
  ['from_20one_20column_20to_20calculate_20another_64',['Using Data from one Column to Calculate Another',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md27',1,'']]],
  ['full_20program_65',['full Program',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md37',1,'Screenshot of the full Program'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html#autotoc_md47',1,'Screenshot of the full Program'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md56',1,'Screenshot of the full Program'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html#autotoc_md61',1,'Screenshot of the full Program']]],
  ['function_66',['function',['../_j_k_q_t_plotter_eval_curves.html#autotoc_md65',1,'Simple C++ inline function'],['../_j_k_q_t_plotter_function_plots.html#autotoc_md70',1,'Simple C++ inline function']]],
  ['function_20f_20x_67',['Plot Function f(x)',['../_j_k_q_t_plotter_parsed_function_plot.html#autotoc_md87',1,'']]],
  ['function_20f_20y_68',['Plot Function f(y)',['../_j_k_q_t_plotter_parsed_function_plot.html#autotoc_md89',1,'']]],
  ['function_20with_20parameters_69',['Simple C++ inline function with Parameters',['../_j_k_q_t_plotter_eval_curves.html#autotoc_md66',1,'']]],
  ['function_20with_20parameters_70',['Simple C++ inline function with parameters',['../_j_k_q_t_plotter_function_plots.html#autotoc_md71',1,'']]],
  ['functions_71',['Functions',['../class_j_k_q_t_math_text.html#JKQTMathTextUsageConvenience',1,'Convenience Functions'],['../class_j_k_q_t_math_text.html#JKQTMathTextUsageDirect',1,'Drawing Functions'],['../group__jkqtmathtext__supportedlatexsymbols.html#jkqtmathtext_supportedlatexsymbols_mathspecialfunctions',1,'Math Special Functions'],['../class_j_k_q_t_math_text.html#JKQTMathTextUsageParsing',1,'Parsing Functions']]],
  ['functions_72',['functions',['../_j_k_q_t_plotter_function_plots.html#autotoc_md72',1,'C++ functors as plot functions'],['../_j_k_q_t_plotter_function_plots.html#autotoc_md74',1,'Predefined "special" functions'],['../_j_k_q_t_plotter_function_plots.html#autotoc_md73',1,'Static C functions']]],
  ['functions_20as_20line_20graphs_73',['Functions as Line Graphs',['../_j_k_q_t_plotter_function_plots.html',1,'Example (JKQTPlotter): Plotting Mathematical Functions as Line Graphs'],['../_j_k_q_t_plotter_parsed_function_plot.html',1,'Example (JKQTPlotter): Plotting Parsed Mathematical Functions as Line Graphs']]],
  ['functions_3a_74',['functions:',['../class_j_k_q_t_p_math_parser.html#jkmp_functions',1,'']]],
  ['functor_75',['Example (JKQTPlotter): Barchart With Custom Draw Functor',['../_j_k_q_t_plotter_barcharts_custom_draw_functor.html',1,'exampleTutorialProjects']]],
  ['functor_20fill_20mode_76',['Example (JKQTPlotter): Barchart With Functor Fill-Mode',['../_j_k_q_t_plotter_barcharts_functor_filling.html',1,'exampleTutorialProjects']]],
  ['functors_20as_20plot_20functions_77',['C++ functors as plot functions',['../_j_k_q_t_plotter_function_plots.html#autotoc_md72',1,'']]],
  ['future_20releases_20versions_78',['Todo List für Future Releases/Versions',['../page_todo.html',1,'']]]
];
