var searchData=
[
  ['data_0',['Data',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md34',1,'(Scatter-)Graphs with X/Y-errors from Categorized Data'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md36',1,'Calculating x- and y-Errors from Categorized Data'],['../_j_k_q_t_plotter_distribution_plot.html',1,'Example (JKQTPlotter): Plotting a Statistical Distribution of Data'],['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_dataexport',1,'Exporting Graph Data']]],
  ['data_1',['Barcharts &amp;amp; Boxplots from categorized data',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md30',1,'']]],
  ['data_20access_20to_20existing_20rows_2',['Iterator-based Column Data Access To Existing Rows',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md38',1,'']]],
  ['data_20as_20a_20rug_20plot_3',['Visualizing data as a Rug Plot',['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md118',1,'']]],
  ['data_20dependent_20styling_20of_20bargraphs_4',['Data-Dependent Styling of Bargraphs',['../class_j_k_q_t_p_bar_graph_base.html#JKQTPBarGraphBaseDataDependentFilling',1,'']]],
  ['data_20from_20a_20c_20array_20into_20a_20column_20of_20the_20jkqtpdatastore_5',['Copy Data from a C-array into a Column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md18',1,'']]],
  ['data_20from_20a_20map_20into_20a_20jkqtpdatastore_6',['Copy Data from a Map into a JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md19',1,'']]],
  ['data_20from_20a_20vector_20into_20a_20column_20of_20the_20jkqtpdatastore_7',['Copy Data from a Vector into a column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md17',1,'']]],
  ['data_20from_20external_20containers_20into_20jkqtpdatastore_8',['Copying Data from External COntainers into JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md16',1,'']]],
  ['data_20from_20one_20column_20to_20calculate_20another_9',['Using Data from one Column to Calculate Another',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md27',1,'']]],
  ['data_20in_20a_20column_20of_20the_20jkqtpdatastore_10',['Reference External Data in a column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md20',1,'']]],
  ['data_20management_11',['JKQTPDatastore-internal Data Management',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md23',1,'']]],
  ['data_20management_20statistics_12',['Examples for Data Management &amp;amp; Statistics',['../example_tutorial_projects.html#jkqtp_extut_datamanagement',1,'']]],
  ['data_20output_13',['Data Output',['../class_j_k_q_t_p_datastore.html#jkqtpdatastore_dataio',1,'']]],
  ['data_20plots_14',['Examples for Image data Plots',['../example_tutorial_projects.html#jkqtp_extut_plotimagedata',1,'']]],
  ['data_20speed_20test_15',['Example (JKQTPlotter): Simple line-graph with live-data (speed test)',['../_j_k_q_t_plotter_speed_test.html',1,'exampleTutorialProjects']]],
  ['data_20storage_16',['Data Storage',['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_datastore',1,'']]],
  ['data_20styles_17',['Examples for Different Plot Data Styles',['../example_tutorial_projects.html#jkqtp_extut_plotstyles',1,'']]],
  ['data_20tooltip_20tool_18',['Data ToolTip Tool',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md107',1,'']]],
  ['dataset_19',['Generating a test Dataset',['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md117',1,'']]],
  ['dataset_20for_20grouped_20barcharts_20',['Generating a Dataset for Grouped Barcharts',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md31',1,'']]],
  ['dataset_20for_20xy_20scatter_20graphs_21',['Dataset for XY Scatter Graphs',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md35',1,'']]],
  ['datasets_20and_20images_22',['2D-Datasets and Images',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md28',1,'']]],
  ['datat_23',['Example (JKQTPlotter): Simple math image plot with modifier datat',['../_j_k_q_t_plotter_image_plot_modifier.html',1,'exampleTutorialProjects']]],
  ['date_20axis_24',['Date Axis',['../_j_k_q_t_plotter_date_time_axes.html#autotoc_md62',1,'']]],
  ['date_20time_20axes_25',['Example (JKQTPlotter): Date/Time Axes',['../_j_k_q_t_plotter_date_time_axes.html',1,'exampleTutorialProjects']]],
  ['declaring_20relations_20between_20plots_26',['Grid Printing/Declaring Relations between Plots',['../class_j_k_q_t_base_plotter.html#JKQTBASEPLOTTER_SYNCMULTIPLOT_GRIDPRINT',1,'']]],
  ['decoration_3a_20underline_20overlines_20strikeout_27',['Text Decoration: Underline, Overlines, Strikeout, ...',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXUnderlinesEtz',1,'']]],
  ['decorators_20for_20jkqtpgeobeziercurve_28',['Line-End Decorators for JKQTPGeoBezierCurve',['../class_j_k_q_t_p_geo_bezier_curve.html#JKQTPGeoBezierCurveDecorators',1,'']]],
  ['default_20style_29',['Altering the Default Style',['../_j_k_q_t_plotter_styling.html#autotoc_md94',1,'']]],
  ['defined_20context_20menu_20of_20jkqtplotter_30',['Special (User-Defined) Context Menu of JKQTPlotter',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_SPECIALCONTEXTMENU',1,'']]],
  ['definition_20of_20the_20parsed_20expressions_31',['definition of the parsed expressions',['../class_j_k_q_t_p_c_s_s_parser.html#jkqtpcss_ebnf',1,'EBNF definition of the parsed expressions'],['../class_j_k_q_t_p_math_parser.html#jkmp_ebnf',1,'EBNF definition of the parsed expressions']]],
  ['definition_20syntax_32',['Font Definition Syntax',['../struct_j_k_q_t_math_text_font_specifier.html#JKQTMathTextFontSpecifier_specialSyntax',1,'']]],
  ['deletion_33',['Column Generation/Deletion',['../class_j_k_q_t_p_datastore.html#jkqtpdatastore_column_management_generation',1,'']]],
  ['demo_20plots_20of_20geometric_20objects_20for_20documentation_34',['Example (JKQTPlotter): Generating Demo-Plots of Geometric Objects for Documentation',['../_j_k_q_t_plotter_geometric_graphs_simple.html',1,'exampleTutorialProjects']]],
  ['density_20estimates_20kde_35',['Density Estimates KDE',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md54',1,'Kernel Density Estimates (KDE)'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html#autotoc_md60',1,'Kernel Density Estimates (KDE)']]],
  ['dependent_20styling_20of_20bargraphs_36',['Data-Dependent Styling of Bargraphs',['../class_j_k_q_t_p_bar_graph_base.html#JKQTPBarGraphBaseDataDependentFilling',1,'']]],
  ['deprecated_20list_37',['Deprecated List',['../deprecated.html',1,'']]],
  ['deprecated_3a_20build_20using_20qmake_38',['DEPRECATED: Build using QMake',['../page_buildinstructions__q_m_a_k_e.html',1,'page_buildinstructions']]],
  ['deprecated_3a_20examples_20for_20jkqtfastplotter_39',['DEPRECATED: Examples for JKQTFastPlotter',['../example_tutorial_projects.html#jkqtp_extut_jkqtfastplotter',1,'']]],
  ['deprecated_3a_20qmake_20dynamic_20library_40',['DEPRECATED: QMake Dynamic Library',['../page_buildinstructions__q_m_a_k_e.html#page_buildinstructions_QMAKEDYNAMIC',1,'']]],
  ['deprecated_3a_20qmake_20in_20qtcreator_41',['DEPRECATED: QMake in QTCreator',['../page_buildinstructions__q_m_a_k_e.html#page_buildinstructions_QMAKEQTCREATOR',1,'']]],
  ['deprecated_3a_20qmake_20include_20project_42',['DEPRECATED: QMake Include Project',['../page_buildinstructions__q_m_a_k_e.html#page_buildinstructions_QMAKEINCLUDE',1,'']]],
  ['deprecated_3a_20qmake_20static_20library_43',['DEPRECATED: QMake Static Library',['../page_buildinstructions__q_m_a_k_e.html#page_buildinstructions_QMAKESTATIC',1,'']]],
  ['description_44',['Description',['../_j_k_q_t_plotter_styling.html#autotoc_md93',1,'Basic Description'],['../_j_k_q_t_plotter_user_interaction.html#autotoc_md98',1,'Basic Description']]],
  ['designer_45',['Designer',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USEQTCREATOR',1,'How to use JKQTPlotter in the Qt Form Designer'],['../_j_k_q_t_plotter_qt_creator.html#autotoc_md91',1,'Instructions on how to use JKQTPlotter in the Qt Form Designer']]],
  ['designer_20ui_20file_46',['Tutorial (JKQTPlotter): Using a JKQTPlotter inside a Qt User Interface Designer (UI) File',['../_j_k_q_t_plotter_qt_creator.html',1,'exampleTutorialProjects']]],
  ['details_47',['Implementation Details',['../class_j_k_q_t_p_base_key.html#JKQTPBaseKey_ImplementationDetails',1,'']]],
  ['determining_20the_20size_20of_20an_20equation_48',['Determining the size of an equation',['../class_j_k_q_t_math_text.html#JKQTMathTextSizing',1,'']]],
  ['different_20aspects_20of_20boxplots_49',['Example (JKQTPlotter): Styling different aspects of boxplots',['../_j_k_q_t_plotter_boxplot_styling.html',1,'exampleTutorialProjects']]],
  ['different_20plot_20data_20styles_50',['Examples for Different Plot Data Styles',['../example_tutorial_projects.html#jkqtp_extut_plotstyles',1,'']]],
  ['different_20sets_20of_20random_20numbers_51',['different sets of random numbers',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md48',1,'Generating different sets of random numbers'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html#autotoc_md57',1,'Generating different sets of random numbers']]],
  ['different_20styles_52',['Example (JKQTPlotter): Step Line Plots in Different Styles',['../_j_k_q_t_plotter_special_step_line_plot.html',1,'exampleTutorialProjects']]],
  ['different_20symbols_20and_20line_20styles_53',['Example (JKQTPlotter): Line Graph with Different Symbols and Line Styles',['../_j_k_q_t_plotter_symbols_and_styles.html',1,'exampleTutorialProjects']]],
  ['different_20types_20of_20arrows_54',['Different types of arrows',['../_j_k_q_t_plotter_geometric_arrows.html#autotoc_md77',1,'']]],
  ['different_20types_20of_20errorindicators_55',['Example (JKQTPlotter): Different Types of Errorindicators',['../_j_k_q_t_plotter_error_bar_styles.html',1,'exampleTutorialProjects']]],
  ['dimensional_20group_20statistics_20with_20jkqtpdatastore_56',['Tutorial (JKQTPDatastore): 1-Dimensional Group Statistics with JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html',1,'exampleTutorialProjects']]],
  ['dimensional_20statistics_20with_20jkqtpdatastore_57',['Dimensional Statistics with JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html',1,'Tutorial (JKQTPDatastore): Advanced 1-Dimensional Statistics with JKQTPDatastore'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html',1,'Tutorial (JKQTPDatastore): Advanced 2-Dimensional Statistics with JKQTPDatastore']]],
  ['display_58',['Mouse Position Display',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md103',1,'']]],
  ['distribution_20of_20data_59',['Example (JKQTPlotter): Plotting a Statistical Distribution of Data',['../_j_k_q_t_plotter_distribution_plot.html',1,'exampleTutorialProjects']]],
  ['diverse_20improvements_20bugfixes_60',['V4.0.0: Qt6 compatibility &amp;amp; diverse improvements + bugfixes',['../page_whatsnew.html#page_whatsnew_V4_0_0',1,'']]],
  ['documentation_61',['Example (JKQTPlotter): Generating Demo-Plots of Geometric Objects for Documentation',['../_j_k_q_t_plotter_geometric_graphs_simple.html',1,'exampleTutorialProjects']]],
  ['double_20clicks_20on_20the_20mouse_20buttons_62',['Actions After (Double-)Clicks on the Mouse Buttons',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSECLICK',1,'']]],
  ['download_63',['Download',['../page_whatsnew.html#page_whatsnew_TRUNK_DOWNLOAD',1,'trunk: Download'],['../page_whatsnew.html#page_whatsnew_V2015_10_DOWNLOAD',1,'v2015.10: Download'],['../page_whatsnew.html#page_whatsnew_V2018_08_DOWNLOAD',1,'v2018.08: Download'],['../page_whatsnew.html#page_whatsnew_V2019_11_DOWNLOAD',1,'v2019.11: Download'],['../page_whatsnew.html#page_whatsnew_V4_0_0_DOWNLOAD',1,'V4.0.0: Download']]],
  ['drag_20the_20plot_20viewport_64',['Drag the Plot Viewport',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md104',1,'']]],
  ['dragging_20the_20mouse_65',['Actions When Dragging the Mouse',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSEDRAG',1,'']]],
  ['draw_20an_20artistic_20image_20with_20a_20parametrized_20scatter_20graph_66',['Example (JKQTPlotter): Draw an Artistic Image with a Parametrized Scatter Graph',['../_j_k_q_t_plotter_param_scatter_image.html',1,'exampleTutorialProjects']]],
  ['draw_20functor_67',['Example (JKQTPlotter): Barchart With Custom Draw Functor',['../_j_k_q_t_plotter_barcharts_custom_draw_functor.html',1,'exampleTutorialProjects']]],
  ['draw_20modes_68',['Draw Modes',['../class_j_k_q_t_p_geometric_plot_element.html#JKQTPGeometricPlotElement_DrawMode',1,'']]],
  ['drawing_69',['Custom Bargraph Drawing',['../class_j_k_q_t_p_bar_graph_base.html#JKQTPBarGraphBaseCustomStyling',1,'']]],
  ['drawing_20a_20contour_20plot_70',['Drawing a Contour Plot',['../_j_k_q_t_plotter_contour_plot.html#autotoc_md13',1,'']]],
  ['drawing_20a_20horizontal_20violin_20plot_71',['Drawing a horizontal Violin Plot',['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md121',1,'']]],
  ['drawing_20functions_72',['Drawing Functions',['../class_j_k_q_t_math_text.html#JKQTMathTextUsageDirect',1,'']]],
  ['drawing_20geometrical_20forms_73',['Drawing Geometrical Forms',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md108',1,'']]],
  ['drawing_20the_20vertical_20violin_20plot_74',['Drawing the (vertical) Violin Plot',['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md120',1,'']]],
  ['drawing_20violin_20plots_75',['Adapters as shortcuts to drawing Violin Plots',['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md122',1,'']]],
  ['drawmode_20for_20jkqtpgeobeziercurve_76',['DrawMode for JKQTPGeoBezierCurve',['../class_j_k_q_t_p_geo_bezier_curve.html#JKQTPGeoBezierCurveDrawMode',1,'']]],
  ['dynamic_20library_77',['DEPRECATED: QMake Dynamic Library',['../page_buildinstructions__q_m_a_k_e.html#page_buildinstructions_QMAKEDYNAMIC',1,'']]]
];
