var searchData=
[
  ['ui_20file_0',['Tutorial (JKQTPlotter): Using a JKQTPlotter inside a Qt User Interface Designer (UI) File',['../_j_k_q_t_plotter_qt_creator.html',1,'exampleTutorialProjects']]],
  ['underbraces_20overbraces_1',['Undersetting, Oversetting, Underbraces, Overbraces ...',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXUnderOver',1,'']]],
  ['underline_20overlines_20strikeout_2',['Text Decoration: Underline, Overlines, Strikeout, ...',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXUnderlinesEtz',1,'']]],
  ['undersetting_20oversetting_20underbraces_20overbraces_3',['Undersetting, Oversetting, Underbraces, Overbraces ...',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXUnderOver',1,'']]],
  ['units_20scaling_4',['Axis Tick Units/Scaling',['../class_j_k_q_t_p_coordinate_axis.html#jkqtplotter_coordinateaxes_tickscaling',1,'']]],
  ['up_20plots_5',['Performance Considerations when Setting up Plots',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_PERFORMACEWHILESETUP',1,'']]],
  ['usage_6',['Usage',['../_j_k_q_t_plotter_mandelbrot.html#autotoc_md83',1,'Introduction and Usage'],['../class_j_k_q_t_base_plotter.html#jkqtplotter_usage_baseplotter',1,'JKQTBasePlotter Usage'],['../class_j_k_q_t_p_math_parser.html#jkmp_example',1,'Simple Example of Usage'],['../class_j_k_q_t_math_text.html#JKQTMathTextUsage',1,'Usage'],['../class_j_k_q_t_p_base_key.html#JKQTPBaseKey_Usage',1,'Usage']]],
  ['usage_20example_7',['Example (JKQTMathText): A simple usage example',['../_j_k_q_t_math_text_simple_example.html',1,'exampleTutorialProjects']]],
  ['usage_20non_20visible_20class_8',['JKQTBasePlotter Standalone Usage (non-visible class)',['../class_j_k_q_t_base_plotter.html#jkqtplotter_usage_baseplotter_standalone',1,'']]],
  ['usage_20of_20jkqtpdatastore_9',['Tutorial (JKQTPDatastore): Basic Usage of JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html',1,'exampleTutorialProjects']]],
  ['usage_20of_20jkqtpdatastore_10',['Tutorial (JKQTPDatastore): Iterator-Based usage of JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html',1,'exampleTutorialProjects']]],
  ['usage_20of_20jkqtplotter_11',['Basic Usage of JKQTPlotter',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_BASICUSAGE',1,'']]],
  ['usage_20within_20a_20qlabel_20class_20jkqtmathtextlabel_12',['Usage within a QLabel class JKQTMathTextLabel',['../class_j_k_q_t_math_text.html#JKQTMathTextUsageQLabel',1,'']]],
  ['use_20cases_13',['Examples for special Use-Cases',['../example_tutorial_projects.html#jkqtp_extut_specialusecasesexamples',1,'']]],
  ['use_20jkqtplotter_20in_20the_20qt_20form_20designer_14',['use JKQTPlotter in the Qt Form Designer',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USEQTCREATOR',1,'How to use JKQTPlotter in the Qt Form Designer'],['../_j_k_q_t_plotter_qt_creator.html#autotoc_md91',1,'Instructions on how to use JKQTPlotter in the Qt Form Designer']]],
  ['use_20of_20central_20jkqtdatastore_15',['Example (JKQTPlotter): Simple math image plot without use of central JKQTdatastore',['../_j_k_q_t_plotter_image_plot_no_datastore.html',1,'exampleTutorialProjects']]],
  ['user_20defined_20context_20menu_20of_20jkqtplotter_16',['Special (User-Defined) Context Menu of JKQTPlotter',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_SPECIALCONTEXTMENU',1,'']]],
  ['user_20interactions_17',['Available User-Interactions',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md100',1,'']]],
  ['user_20interactions_20gui_20features_18',['User-Interactions/GUI Features',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERINTERACTION',1,'']]],
  ['user_20interactions_20in_20jkqtplotter_19',['Tutorial (JKQTPlotter): User-Interactions in JKQtPlotter',['../_j_k_q_t_plotter_user_interaction.html',1,'exampleTutorialProjects']]],
  ['user_20interface_20designer_20ui_20file_20',['Tutorial (JKQTPlotter): Using a JKQTPlotter inside a Qt User Interface Designer (UI) File',['../_j_k_q_t_plotter_qt_creator.html',1,'exampleTutorialProjects']]],
  ['user_20properties_21',['User Properties',['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_userprops',1,'']]],
  ['using_20a_20cmake_20build_22',['Using a CMake Build',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_USAGE',1,'']]],
  ['using_20a_20jkqtplotter_20inside_20a_20qt_20user_20interface_20designer_20ui_20file_23',['Tutorial (JKQTPlotter): Using a JKQTPlotter inside a Qt User Interface Designer (UI) File',['../_j_k_q_t_plotter_qt_creator.html',1,'exampleTutorialProjects']]],
  ['using_20a_20qscrollbar_20together_20with_20jkqtplotter_24',['Example (JKQTPlotter): Using a QScrollbar together with JKQtPlotter',['../_j_k_q_t_plotter_u_i_scrollbar.html',1,'exampleTutorialProjects']]],
  ['using_20c_20stl_20algorithms_25',['Using C++ STL algorithms',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md40',1,'']]],
  ['using_20cmake_26',['Build using CMake',['../page_buildinstructions__c_m_a_k_e.html',1,'page_buildinstructions']]],
  ['using_20data_20from_20one_20column_20to_20calculate_20another_27',['Using Data from one Column to Calculate Another',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md27',1,'']]],
  ['using_20jkqtpfilledcurvexgraph_28',['Plot red/blue wiggle plot using &lt;span class=&quot;tt&quot;&gt;JKQTPFilledCurveXGraph&lt;/span&gt;',['../_j_k_q_t_plotter_wiggle_plots.html#autotoc_md116',1,'']]],
  ['using_20jkqtpfilledcurveygraph_20in_20a_20seismographic_20style_29',['Plot black/transparent wiggle plot using &lt;span class=&quot;tt&quot;&gt;JKQTPFilledCurveYGraph&lt;/span&gt; in a &quot;seismographic style&quot;',['../_j_k_q_t_plotter_wiggle_plots.html#autotoc_md119',1,'']]],
  ['using_20jkqtplotter_20with_20cmake_20s_20fetchcontent_20api_30',['Using JKQTPlotter with CMake&apos;s FetchContent-API',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_FETCHCONTENT',1,'']]],
  ['using_20qmake_31',['DEPRECATED: Build using QMake',['../page_buildinstructions__q_m_a_k_e.html',1,'page_buildinstructions']]],
  ['utility_20jkqtmathtext_5frender_32',['Tool (JKQTMathText): Command-Line Utility jkqtmathtext_render',['../_j_k_q_t_math_text_render_cmd_line_tool.html',1,'exampleTutorialProjects']]],
  ['utility_20jkqtplotter_5fdoc_5fimagegenerator_33',['Tool (JKQTMathText): Command-Line Utility jkqtplotter_doc_imagegenerator',['../_j_k_q_t_plotter_doc_image_render_cmd_line_tool.html',1,'exampleTutorialProjects']]]
];
