var searchData=
[
  ['palettes_0',['Example (JKQTPlotter): Image Plots with Custom Palettes',['../_j_k_q_t_plotter_image_plot_user_palette.html',1,'exampleTutorialProjects']]],
  ['palettes_20from_20files_1',['Load Palettes from Files',['../_j_k_q_t_plotter_image_plot_user_palette.html#autotoc_md81',1,'']]],
  ['palettes_20programmatically_2',['Build Palettes Programmatically',['../_j_k_q_t_plotter_image_plot_user_palette.html#autotoc_md80',1,'']]],
  ['parallel_20plotting_3',['Example (JKQTPlotter): Multi-Threaded (Parallel) Plotting',['../_j_k_q_t_plotter_multi_threaded.html',1,'exampleTutorialProjects']]],
  ['parameters_4',['Simple C++ inline function with Parameters',['../_j_k_q_t_plotter_eval_curves.html#autotoc_md66',1,'']]],
  ['parameters_5',['parameters',['../_j_k_q_t_plotter_parsed_function_plot.html#autotoc_md88',1,'Plotting with parameters'],['../_j_k_q_t_plotter_function_plots.html#autotoc_md71',1,'Simple C++ inline function with parameters']]],
  ['parametric_20curves_6',['Example (JKQTPlotter): Plotting Parametric Curves',['../_j_k_q_t_plotter_parametric_curves.html',1,'exampleTutorialProjects']]],
  ['parametric_20mathematical_20curves_20as_20line_20graphs_7',['Example (JKQTPlotter): Plotting Parametric Mathematical Curves as Line Graphs',['../_j_k_q_t_plotter_eval_curves.html',1,'exampleTutorialProjects']]],
  ['parametrized_20scatter_20graph_8',['Example (JKQTPlotter): Draw an Artistic Image with a Parametrized Scatter Graph',['../_j_k_q_t_plotter_param_scatter_image.html',1,'exampleTutorialProjects']]],
  ['parametrized_20scatter_20graph_20with_20custom_20symbols_9',['Example (JKQTPlotter): Parametrized Scatter-graph with custom symbols',['../_j_k_q_t_plotterparamscatter_custom_symbol.html',1,'exampleTutorialProjects']]],
  ['parametrized_20symbols_20colors_10',['Example (JKQTPlotter): Scatter Graph with Parametrized Symbols/Colors',['../_j_k_q_t_plotter_param_scatter.html',1,'exampleTutorialProjects']]],
  ['parantheses_11',['Braces/Parantheses ...',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXBraces',1,'']]],
  ['parsed_20expressions_12',['parsed expressions',['../class_j_k_q_t_p_c_s_s_parser.html#jkqtpcss_ebnf',1,'EBNF definition of the parsed expressions'],['../class_j_k_q_t_p_math_parser.html#jkmp_ebnf',1,'EBNF definition of the parsed expressions']]],
  ['parsed_20mathematical_20functions_20as_20line_20graphs_13',['Example (JKQTPlotter): Plotting Parsed Mathematical Functions as Line Graphs',['../_j_k_q_t_plotter_parsed_function_plot.html',1,'exampleTutorialProjects']]],
  ['parsing_20and_20evaluation_3a_14',['result of parsing and evaluation:',['../class_j_k_q_t_p_math_parser.html#jkmp_resultsofparsing',1,'']]],
  ['parsing_20functions_15',['Parsing Functions',['../class_j_k_q_t_math_text.html#JKQTMathTextUsageParsing',1,'']]],
  ['party_20products_20contained_20in_20jkqtplotter_16',['Licenses of 3rd Party Products Contained in JKQTPlotter',['../licensepage.html#extlicense_sec',1,'']]],
  ['performance_20considerations_20when_20setting_20up_20plots_17',['Performance Considerations when Setting up Plots',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_PERFORMACEWHILESETUP',1,'']]],
  ['pledge_18',['Our Pledge',['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html#autotoc_md7',1,'']]],
  ['plot_19',['Plot',['../_j_k_q_t_plotter_contour_plot.html#autotoc_md13',1,'Drawing a Contour Plot'],['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md121',1,'Drawing a horizontal Violin Plot'],['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md120',1,'Drawing the (vertical) Violin Plot'],['../_j_k_q_t_plotter_r_g_b_image_plot.html',1,'Example (JKQTPlotter): Simple Math RGB/CMY Image Plot'],['../_j_k_q_t_plotter_contour_plot.html#autotoc_md15',1,'Gimmick: Animating a Contour Plot'],['../_j_k_q_t_plotter_contour_plot.html#autotoc_md14',1,'Styling a Contour Plot'],['../_j_k_q_t_plotter_user_interaction.html#autotoc_md102',1,'Toolbar at the top of the Plot'],['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md118',1,'Visualizing data as a Rug Plot']]],
  ['plot_20',['Example (JKQTPlotter): Simple math image plot',['../_j_k_q_t_plotter_image_plot.html',1,'exampleTutorialProjects']]],
  ['plot_20black_20transparent_20wiggle_20plot_20using_20jkqtpfilledcurveygraph_20in_20a_20seismographic_20style_21',['Plot black/transparent wiggle plot using &lt;span class=&quot;tt&quot;&gt;JKQTPFilledCurveYGraph&lt;/span&gt; in a &quot;seismographic style&quot;',['../_j_k_q_t_plotter_wiggle_plots.html#autotoc_md119',1,'']]],
  ['plot_20data_20styles_22',['Examples for Different Plot Data Styles',['../example_tutorial_projects.html#jkqtp_extut_plotstyles',1,'']]],
  ['plot_20example_23',['Plot Example',['../_j_k_q_t_p_parametrized_vector_field_graph_example.html',1,'Example (JKQTPlotter): Vector Field Plot Example'],['../_j_k_q_t_plotter_vector_field_example.html',1,'Example (JKQTPlotter): Vector Field Plot Example']]],
  ['plot_20function_20f_20x_24',['Plot Function f(x)',['../_j_k_q_t_plotter_parsed_function_plot.html#autotoc_md87',1,'']]],
  ['plot_20function_20f_20y_25',['Plot Function f(y)',['../_j_k_q_t_plotter_parsed_function_plot.html#autotoc_md89',1,'']]],
  ['plot_20functions_26',['C++ functors as plot functions',['../_j_k_q_t_plotter_function_plots.html#autotoc_md72',1,'']]],
  ['plot_20keys_20axes_27',['Examples for Styling the Plot, Keys, Axes, ...',['../example_tutorial_projects.html#jkqtp_extut_keyaxesstyles',1,'']]],
  ['plot_20red_20blue_20wiggle_20plot_20using_20jkqtpfilledcurvexgraph_28',['Plot red/blue wiggle plot using &lt;span class=&quot;tt&quot;&gt;JKQTPFilledCurveXGraph&lt;/span&gt;',['../_j_k_q_t_plotter_wiggle_plots.html#autotoc_md116',1,'']]],
  ['plot_20showin_20a_201_20channel_20cimg_20image_29',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel CImg image',['../_j_k_q_t_plotter_image_plot_c_img.html',1,'exampleTutorialProjects']]],
  ['plot_20showin_20a_201_20channel_20opencv_20cv_3a_3amat_30',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_open_c_v.html',1,'exampleTutorialProjects']]],
  ['plot_20showing_20a_203_20channel_20cimg_20image_31',['Example (JKQTPlotter): Simple math image plot, showing a 3-channel CImg image',['../_j_k_q_t_plotter_image_plot_r_g_b_c_img.html',1,'exampleTutorialProjects']]],
  ['plot_20showing_20a_203_20channel_20opencv_20cv_3a_3amat_32',['Example (JKQTPlotter): Simple RGB image plot, showing a 3-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_r_g_b_open_c_v.html',1,'exampleTutorialProjects']]],
  ['plot_20sizes_20borders_33',['Plot Sizes &amp;amp; Borders',['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_plotsize',1,'']]],
  ['plot_20using_20jkqtpfilledcurvexgraph_34',['Plot red/blue wiggle plot using &lt;span class=&quot;tt&quot;&gt;JKQTPFilledCurveXGraph&lt;/span&gt;',['../_j_k_q_t_plotter_wiggle_plots.html#autotoc_md116',1,'']]],
  ['plot_20using_20jkqtpfilledcurveygraph_20in_20a_20seismographic_20style_35',['Plot black/transparent wiggle plot using &lt;span class=&quot;tt&quot;&gt;JKQTPFilledCurveYGraph&lt;/span&gt; in a &quot;seismographic style&quot;',['../_j_k_q_t_plotter_wiggle_plots.html#autotoc_md119',1,'']]],
  ['plot_20viewport_36',['Drag the Plot Viewport',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md104',1,'']]],
  ['plot_20widget_37',['Fast Resizing of a Plot Widget',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_FASTRESIZING',1,'']]],
  ['plot_20width_38',['Synchronizing Axis Range &amp;amp; Plot Width',['../class_j_k_q_t_base_plotter.html#JKQTBASEPLOTTER_SYNCMULTIPLOT_SYNC',1,'']]],
  ['plot_20with_20axes_20through_20origin_39',['Example (JKQTPlotter): Plot With Axes through Origin',['../_j_k_q_t_plotter_geometric_coordinate_axis0.html',1,'exampleTutorialProjects']]],
  ['plot_20with_20modifier_20datat_40',['Example (JKQTPlotter): Simple math image plot with modifier datat',['../_j_k_q_t_plotter_image_plot_modifier.html',1,'exampleTutorialProjects']]],
  ['plot_20without_20use_20of_20central_20jkqtdatastore_41',['Example (JKQTPlotter): Simple math image plot without use of central JKQTdatastore',['../_j_k_q_t_plotter_image_plot_no_datastore.html',1,'exampleTutorialProjects']]],
  ['plots_42',['Plots',['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md122',1,'Adapters as shortcuts to drawing Violin Plots'],['../_j_k_q_t_plotter_contour_plot.html',1,'Example (JKQTPlotter): Contour Plots'],['../_j_k_q_t_plotter_filled_graphs.html',1,'Example (JKQTPlotter): Filled Curve Plots'],['../_j_k_q_t_plotter_multi_plot_layout.html',1,'Example (JKQTPlotter): Laying out Several Plots'],['../_j_k_q_t_plotter_violinplot_graphs.html',1,'Example (JKQTPlotter): Violin Plots'],['../_j_k_q_t_plotter_wiggle_plots.html',1,'Example (JKQTPlotter): Wiggle Plots'],['../example_tutorial_projects.html#jkqtp_extut_plotimagedata',1,'Examples for Image data Plots'],['../class_j_k_q_t_base_plotter.html#JKQTBASEPLOTTER_SYNCMULTIPLOT_GRIDPRINT',1,'Grid Printing/Declaring Relations between Plots'],['../class_j_k_q_t_plotter.html#JKQTPLOTTER_PERFORMACEWHILESETUP',1,'Performance Considerations when Setting up Plots'],['../class_j_k_q_t_base_plotter.html#JKQTBASEPLOTTER_SYNCMULTIPLOT',1,'Synchronizing Several Plots'],['../class_j_k_q_t_plotter.html#JKQTPLOTTER_SYNCMULTIPLOT',1,'Synchronizing Several Plots']]],
  ['plots_43',['Example (JKQTPlotter): Simple impulse plots',['../_j_k_q_t_plotter_impulse_plots.html',1,'exampleTutorialProjects']]],
  ['plots_20in_20different_20styles_44',['Example (JKQTPlotter): Step Line Plots in Different Styles',['../_j_k_q_t_plotter_special_step_line_plot.html',1,'exampleTutorialProjects']]],
  ['plots_20of_20geometric_20objects_20for_20documentation_45',['Example (JKQTPlotter): Generating Demo-Plots of Geometric Objects for Documentation',['../_j_k_q_t_plotter_geometric_graphs_simple.html',1,'exampleTutorialProjects']]],
  ['plots_20with_20custom_20palettes_46',['Example (JKQTPlotter): Image Plots with Custom Palettes',['../_j_k_q_t_plotter_image_plot_user_palette.html',1,'exampleTutorialProjects']]],
  ['plotting_47',['Example (JKQTPlotter): Multi-Threaded (Parallel) Plotting',['../_j_k_q_t_plotter_multi_threaded.html',1,'exampleTutorialProjects']]],
  ['plotting_20a_20statistical_20distribution_20of_20data_48',['Example (JKQTPlotter): Plotting a Statistical Distribution of Data',['../_j_k_q_t_plotter_distribution_plot.html',1,'exampleTutorialProjects']]],
  ['plotting_20algorithm_49',['Properties of the Adaptive Plotting Algorithm',['../_j_k_q_t_plotter_parsed_function_plot.html#autotoc_md90',1,'']]],
  ['plotting_20arrows_50',['Example (JKQTPlotter): Plotting Arrows',['../_j_k_q_t_plotter_geometric_arrows.html',1,'exampleTutorialProjects']]],
  ['plotting_20bezier_20curves_51',['Example (JKQTPlotter): Plotting Bezier Curves',['../_j_k_q_t_plotter_geometric_bezier.html',1,'exampleTutorialProjects']]],
  ['plotting_20geometric_20objects_52',['Example (JKQTPlotter): Plotting Geometric Objects',['../_j_k_q_t_plotter_geometric_graphs.html',1,'exampleTutorialProjects']]],
  ['plotting_20library_53',['JKQTPlotter - A Qt Plotting Library',['../index.html',1,'']]],
  ['plotting_20mathematical_20functions_20as_20line_20graphs_54',['Example (JKQTPlotter): Plotting Mathematical Functions as Line Graphs',['../_j_k_q_t_plotter_function_plots.html',1,'exampleTutorialProjects']]],
  ['plotting_20parametric_20curves_55',['Example (JKQTPlotter): Plotting Parametric Curves',['../_j_k_q_t_plotter_parametric_curves.html',1,'exampleTutorialProjects']]],
  ['plotting_20parametric_20mathematical_20curves_20as_20line_20graphs_56',['Example (JKQTPlotter): Plotting Parametric Mathematical Curves as Line Graphs',['../_j_k_q_t_plotter_eval_curves.html',1,'exampleTutorialProjects']]],
  ['plotting_20parsed_20mathematical_20functions_20as_20line_20graphs_57',['Example (JKQTPlotter): Plotting Parsed Mathematical Functions as Line Graphs',['../_j_k_q_t_plotter_parsed_function_plot.html',1,'exampleTutorialProjects']]],
  ['plotting_20with_20parameters_58',['Plotting with parameters',['../_j_k_q_t_plotter_parsed_function_plot.html#autotoc_md88',1,'']]],
  ['policy_59',['Security Policy',['../md__s_e_c_u_r_i_t_y.html',1,'']]],
  ['polynom_20fitting_60',['Polynom Fitting',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html#autotoc_md46',1,'']]],
  ['position_20display_61',['Mouse Position Display',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md103',1,'']]],
  ['predefined_20special_20functions_62',['Predefined &quot;special&quot; functions',['../_j_k_q_t_plotter_function_plots.html#autotoc_md74',1,'']]],
  ['preinitialized_20columns_63',['Generating Columns Preinitialized Columns',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md25',1,'']]],
  ['printing_20declaring_20relations_20between_20plots_64',['Grid Printing/Declaring Relations between Plots',['../class_j_k_q_t_base_plotter.html#JKQTBASEPLOTTER_SYNCMULTIPLOT_GRIDPRINT',1,'']]],
  ['printing_20graphs_65',['Saving and Printing Graphs',['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_saveprint',1,'']]],
  ['printing_20saving_20exporting_66',['Printing, Saving &amp;amp; Exporting',['../class_j_k_q_t_base_plotter.html#jkqtbaseplotter_dataexport_print',1,'']]],
  ['process_67',['Pull Request Process',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md1',1,'']]],
  ['products_20contained_20in_20jkqtplotter_68',['Licenses of 3rd Party Products Contained in JKQTPlotter',['../licensepage.html#extlicense_sec',1,'']]],
  ['program_69',['Program',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md37',1,'Screenshot of the full Program'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html#autotoc_md47',1,'Screenshot of the full Program'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md56',1,'Screenshot of the full Program'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html#autotoc_md61',1,'Screenshot of the full Program']]],
  ['program_20of_20the_20example_20gui_70',['Main Program of the Example (GUI)',['../_j_k_q_t_plotter_image_plot_user_palette.html#autotoc_md82',1,'']]],
  ['programmatically_71',['Build Palettes Programmatically',['../_j_k_q_t_plotter_image_plot_user_palette.html#autotoc_md80',1,'']]],
  ['programs_72',['Tool Programs',['../example_tutorial_projects.html#jkqtp_extut_tools',1,'']]],
  ['project_73',['DEPRECATED: QMake Include Project',['../page_buildinstructions__q_m_a_k_e.html#page_buildinstructions_QMAKEINCLUDE',1,'']]],
  ['projects_74',['Projects',['../example_tutorial_projects.html',1,'Example &amp; Tutorial Projects'],['../class_j_k_q_t_math_text.html#JKQTMathTextExamples',1,'Example Projects']]],
  ['properties_75',['Properties',['../class_j_k_q_t_p_datastore.html#jkqtpdatastore_column_management_props',1,'Column Properties'],['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXFontPropsFontProps',1,'Font Properties'],['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_userprops',1,'User Properties']]],
  ['properties_20of_20the_20adaptive_20plotting_20algorithm_76',['Properties of the Adaptive Plotting Algorithm',['../_j_k_q_t_plotter_parsed_function_plot.html#autotoc_md90',1,'']]],
  ['properties_20of_20the_20jkqtpdatastore_20iterators_77',['Special Properties of the JKQTPDatastore-Iterators',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md41',1,'']]],
  ['pull_20request_20process_78',['Pull Request Process',['../md__c_o_n_t_r_i_b_u_t_i_n_g.html#autotoc_md1',1,'']]]
];
