var searchData=
[
  ['a_201_20channel_20cimg_20image_0',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel CImg image',['../_j_k_q_t_plotter_image_plot_c_img.html',1,'exampleTutorialProjects']]],
  ['a_201_20channel_20opencv_20cv_3a_3amat_1',['Example (JKQTPlotter): Simple math image plot, showin a 1-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_open_c_v.html',1,'exampleTutorialProjects']]],
  ['a_203_20channel_20cimg_20image_2',['Example (JKQTPlotter): Simple math image plot, showing a 3-channel CImg image',['../_j_k_q_t_plotter_image_plot_r_g_b_c_img.html',1,'exampleTutorialProjects']]],
  ['a_203_20channel_20opencv_20cv_3a_3amat_3',['Example (JKQTPlotter): Simple RGB image plot, showing a 3-channel OpenCV cv::Mat',['../_j_k_q_t_plotter_image_plot_r_g_b_open_c_v.html',1,'exampleTutorialProjects']]],
  ['a_20barchart_4',['Calculating Grouped Statistics for a Barchart',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md32',1,'']]],
  ['a_20boxplot_5',['Calculating Grouped Statistics for a Boxplot',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md33',1,'']]],
  ['a_20build_20with_20cmake_6',['a Build with CMake',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_CONFIG',1,'Configuring a Build with CMake'],['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_RUN',1,'Running a Build with CMake']]],
  ['a_20c_20array_20into_20a_20column_20of_20the_20jkqtpdatastore_7',['Copy Data from a C-array into a Column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md18',1,'']]],
  ['a_20cmake_20build_8',['Using a CMake Build',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_USAGE',1,'']]],
  ['a_20column_20of_20the_20jkqtpdatastore_9',['Copy Data from a C-array into a Column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md18',1,'']]],
  ['a_20column_20of_20the_20jkqtpdatastore_10',['a column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md17',1,'Copy Data from a Vector into a column of the JKQTPDatastore'],['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md20',1,'Reference External Data in a column of the JKQTPDatastore']]],
  ['a_20contour_20plot_11',['a Contour Plot',['../_j_k_q_t_plotter_contour_plot.html#autotoc_md13',1,'Drawing a Contour Plot'],['../_j_k_q_t_plotter_contour_plot.html#autotoc_md15',1,'Gimmick: Animating a Contour Plot'],['../_j_k_q_t_plotter_contour_plot.html#autotoc_md14',1,'Styling a Contour Plot']]],
  ['a_20dataset_20for_20grouped_20barcharts_12',['Generating a Dataset for Grouped Barcharts',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md31',1,'']]],
  ['a_20graph_13',['Example (JKQTPlotter): QImage as a Graph',['../_j_k_q_t_plotter_image_plot_q_image_r_g_b.html',1,'exampleTutorialProjects']]],
  ['a_20horizontal_20violin_20plot_14',['Drawing a horizontal Violin Plot',['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md121',1,'']]],
  ['a_20jkqtpdatastore_15',['Copy Data from a Map into a JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md19',1,'']]],
  ['a_20jkqtplotter_16',['QActions from a JKQTPlotter',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_ACTIONS',1,'']]],
  ['a_20jkqtplotter_17',['Tutorial (JKQTPlotter): Styling a JKQtPlotter',['../_j_k_q_t_plotter_styling.html',1,'exampleTutorialProjects']]],
  ['a_20jkqtplotter_20inside_20a_20qt_20user_20interface_20designer_20ui_20file_18',['Tutorial (JKQTPlotter): Using a JKQTPlotter inside a Qt User Interface Designer (UI) File',['../_j_k_q_t_plotter_qt_creator.html',1,'exampleTutorialProjects']]],
  ['a_20map_20into_20a_20jkqtpdatastore_19',['Copy Data from a Map into a JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md19',1,'']]],
  ['a_20mouse_20wheel_20event_20occurs_20',['Actions When a Mouse Wheel Event Occurs',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSEWHEEL',1,'']]],
  ['a_20new_20style_20to_20an_20existing_20jkqtplotter_21',['Apply a new Style to an Existing JKQTPlotter',['../_j_k_q_t_plotter_styling.html#autotoc_md96',1,'']]],
  ['a_20parametrized_20scatter_20graph_22',['Example (JKQTPlotter): Draw an Artistic Image with a Parametrized Scatter Graph',['../_j_k_q_t_plotter_param_scatter_image.html',1,'exampleTutorialProjects']]],
  ['a_20plot_20widget_23',['Fast Resizing of a Plot Widget',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_FASTRESIZING',1,'']]],
  ['a_20qlabel_20class_20jkqtmathtextlabel_24',['Usage within a QLabel class JKQTMathTextLabel',['../class_j_k_q_t_math_text.html#JKQTMathTextUsageQLabel',1,'']]],
  ['a_20qscrollbar_20together_20with_20jkqtplotter_25',['Example (JKQTPlotter): Using a QScrollbar together with JKQtPlotter',['../_j_k_q_t_plotter_u_i_scrollbar.html',1,'exampleTutorialProjects']]],
  ['a_20qt_20plotting_20library_26',['JKQTPlotter - A Qt Plotting Library',['../index.html',1,'']]],
  ['a_20qt_20user_20interface_20designer_20ui_20file_27',['Tutorial (JKQTPlotter): Using a JKQTPlotter inside a Qt User Interface Designer (UI) File',['../_j_k_q_t_plotter_qt_creator.html',1,'exampleTutorialProjects']]],
  ['a_20rug_20plot_28',['Visualizing data as a Rug Plot',['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md118',1,'']]],
  ['a_20seismographic_20style_29',['Plot black/transparent wiggle plot using &lt;span class=&quot;tt&quot;&gt;JKQTPFilledCurveYGraph&lt;/span&gt; in a &quot;seismographic style&quot;',['../_j_k_q_t_plotter_wiggle_plots.html#autotoc_md119',1,'']]],
  ['a_20simple_20usage_20example_30',['Example (JKQTMathText): A simple usage example',['../_j_k_q_t_math_text_simple_example.html',1,'exampleTutorialProjects']]],
  ['a_20statistical_20distribution_20of_20data_31',['Example (JKQTPlotter): Plotting a Statistical Distribution of Data',['../_j_k_q_t_plotter_distribution_plot.html',1,'exampleTutorialProjects']]],
  ['a_20test_20application_32',['Example (JKQTMathText): A test application',['../_j_k_q_t_math_text_test_app.html',1,'exampleTutorialProjects']]],
  ['a_20test_20dataset_33',['Generating a test Dataset',['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md117',1,'']]],
  ['a_20vector_20into_20a_20column_20of_20the_20jkqtpdatastore_34',['Copy Data from a Vector into a column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md17',1,'']]],
  ['a_20vulnerability_35',['Reporting a Vulnerability',['../md__s_e_c_u_r_i_t_y.html#autotoc_md125',1,'']]],
  ['access_20to_20existing_20rows_36',['Iterator-based Column Data Access To Existing Rows',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md38',1,'']]],
  ['actions_37',['Mouse Move Signaling and Actions',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSEMOVE',1,'']]],
  ['actions_20after_20double_20clicks_20on_20the_20mouse_20buttons_38',['Actions After (Double-)Clicks on the Mouse Buttons',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSECLICK',1,'']]],
  ['actions_20when_20a_20mouse_20wheel_20event_20occurs_39',['Actions When a Mouse Wheel Event Occurs',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSEWHEEL',1,'']]],
  ['actions_20when_20dragging_20the_20mouse_40',['Actions When Dragging the Mouse',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSEDRAG',1,'']]],
  ['adapters_20as_20shortcuts_20to_20drawing_20violin_20plots_41',['Adapters as shortcuts to drawing Violin Plots',['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md122',1,'']]],
  ['adaptive_20plotting_20algorithm_42',['Properties of the Adaptive Plotting Algorithm',['../_j_k_q_t_plotter_parsed_function_plot.html#autotoc_md90',1,'']]],
  ['advanced_201_20dimensional_20statistics_20with_20jkqtpdatastore_43',['Tutorial (JKQTPDatastore): Advanced 1-Dimensional Statistics with JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html',1,'exampleTutorialProjects']]],
  ['advanced_202_20dimensional_20statistics_20with_20jkqtpdatastore_44',['Tutorial (JKQTPDatastore): Advanced 2-Dimensional Statistics with JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics2_d.html',1,'exampleTutorialProjects']]],
  ['advanced_20line_20and_20fill_20styling_45',['Example (JKQTPlotter): Advanced Line and Fill Styling',['../_j_k_q_t_plotter_advanced_line_and_fill_styling.html',1,'exampleTutorialProjects']]],
  ['after_20double_20clicks_20on_20the_20mouse_20buttons_46',['Actions After (Double-)Clicks on the Mouse Buttons',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSECLICK',1,'']]],
  ['algorithm_47',['Properties of the Adaptive Plotting Algorithm',['../_j_k_q_t_plotter_parsed_function_plot.html#autotoc_md90',1,'']]],
  ['algorithms_48',['Using C++ STL algorithms',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html#autotoc_md40',1,'']]],
  ['altering_20the_20default_20style_49',['Altering the Default Style',['../_j_k_q_t_plotter_styling.html#autotoc_md94',1,'']]],
  ['an_20artistic_20image_20with_20a_20parametrized_20scatter_20graph_50',['Example (JKQTPlotter): Draw an Artistic Image with a Parametrized Scatter Graph',['../_j_k_q_t_plotter_param_scatter_image.html',1,'exampleTutorialProjects']]],
  ['an_20equation_51',['Determining the size of an equation',['../class_j_k_q_t_math_text.html#JKQTMathTextSizing',1,'']]],
  ['an_20existing_20jkqtplotter_52',['Apply a new Style to an Existing JKQTPlotter',['../_j_k_q_t_plotter_styling.html#autotoc_md96',1,'']]],
  ['analysis_20with_20the_20statistics_20library_53',['Tutorial (JKQTPDatastore): Regression Analysis (with the Statistics Library)',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_regression.html',1,'exampleTutorialProjects']]],
  ['and_20actions_54',['Mouse Move Signaling and Actions',['../class_j_k_q_t_plotter.html#JKQTPLOTTER_USERMOUSEINTERACTION_MOUSEMOVE',1,'']]],
  ['and_20blocks_55',['Linebreaks and Blocks',['../group__jkqtmathtext__renderingmodel.html#jkqtmathtext_renderingmodel_linebreaks',1,'']]],
  ['and_20evaluation_3a_56',['result of parsing and evaluation:',['../class_j_k_q_t_p_math_parser.html#jkmp_resultsofparsing',1,'']]],
  ['and_20fill_20styling_57',['Example (JKQTPlotter): Advanced Line and Fill Styling',['../_j_k_q_t_plotter_advanced_line_and_fill_styling.html',1,'exampleTutorialProjects']]],
  ['and_20filling_20them_58',['Generating Non-Initialized Columns and Filling Them',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md24',1,'']]],
  ['and_20grids_59',['and Grids',['../class_j_k_q_t_p_coordinate_axis.html#jkqtplotter_base_grids_baseelemenets',1,'Axis Ticks and Grids'],['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_grids_baseplotter',1,'Axis Ticks and Grids']]],
  ['and_20images_60',['2D-Datasets and Images',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md28',1,'']]],
  ['and_20kdes_61',['Cummulative Histograms and KDEs',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics.html#autotoc_md55',1,'']]],
  ['and_20line_20styles_62',['Example (JKQTPlotter): Line Graph with Different Symbols and Line Styles',['../_j_k_q_t_plotter_symbols_and_styles.html',1,'exampleTutorialProjects']]],
  ['and_20printing_20graphs_63',['Saving and Printing Graphs',['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_saveprint',1,'']]],
  ['and_20special_20characters_64',['Symbols and special characters',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXSymbols',1,'']]],
  ['and_20superscript_65',['Sub- and Superscript',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXSubSuper',1,'']]],
  ['and_20text_20mode_66',['Switch between Math- and Text-Mode',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXMathTextMode',1,'']]],
  ['and_20transformations_67',['and Transformations',['../class_j_k_q_t_p_coordinate_axis.html#jkqtplotter_base_systems_baseelements',1,'Coordinate Systems and Transformations'],['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_systems_baseplotter',1,'Coordinate Systems and Transformations']]],
  ['and_20usage_68',['Introduction and Usage',['../_j_k_q_t_plotter_mandelbrot.html#autotoc_md83',1,'']]],
  ['and_20variables_3a_69',['constants and variables:',['../class_j_k_q_t_p_math_parser.html#jkmp_constantsAndVars',1,'']]],
  ['and_20y_20errors_20from_20categorized_20data_70',['Calculating x- and y-Errors from Categorized Data',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_statistics_grouped_stat.html#autotoc_md36',1,'']]],
  ['animating_20a_20contour_20plot_71',['Gimmick: Animating a Contour Plot',['../_j_k_q_t_plotter_contour_plot.html#autotoc_md15',1,'']]],
  ['annotaions_72',['Examples for Geometric Forms, Arrows, Annotaions ...',['../example_tutorial_projects.html#jkqtp_extut_geometric',1,'']]],
  ['another_73',['Using Data from one Column to Calculate Another',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md27',1,'']]],
  ['api_74',['Using JKQTPlotter with CMake&apos;s FetchContent-API',['../page_buildinstructions__c_m_a_k_e.html#page_buildinstructions_CMAKE_FETCHCONTENT',1,'']]],
  ['appearance_20styling_20of_20the_20graph_75',['Appearance &amp;amp; Styling of the Graph',['../class_j_k_q_t_base_plotter.html#jkqtbaseplotter_appearance_and_style',1,'']]],
  ['appending_20to_20columns_76',['Appending to Columns',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md26',1,'']]],
  ['application_77',['Example (JKQTMathText): A test application',['../_j_k_q_t_math_text_test_app.html',1,'exampleTutorialProjects']]],
  ['apply_20a_20new_20style_20to_20an_20existing_20jkqtplotter_78',['Apply a new Style to an Existing JKQTPlotter',['../_j_k_q_t_plotter_styling.html#autotoc_md96',1,'']]],
  ['array_20into_20a_20column_20of_20the_20jkqtpdatastore_79',['Copy Data from a C-array into a Column of the JKQTPDatastore',['../_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html#autotoc_md18',1,'']]],
  ['array_20type_20instructions_80',['Matrix/Array Type Instructions',['../group__jkqtmathtext__supportedlatex.html#JKQTMathTextSuppoertedLaTeXMatrix',1,'']]],
  ['arrows_81',['Arrows',['../group__jkqtmathtext__supportedlatexsymbols.html#jkqtmathtext_supportedlatexsymbols_arrows',1,'Arrows'],['../_j_k_q_t_plotter_geometric_arrows.html',1,'Example (JKQTPlotter): Plotting Arrows']]],
  ['arrows_82',['arrows',['../_j_k_q_t_plotter_geometric_arrows.html#autotoc_md78',1,'Classes with support for arrows'],['../_j_k_q_t_plotter_geometric_arrows.html#autotoc_md77',1,'Different types of arrows']]],
  ['arrows_20annotaions_83',['Examples for Geometric Forms, Arrows, Annotaions ...',['../example_tutorial_projects.html#jkqtp_extut_geometric',1,'']]],
  ['artistic_20image_20with_20a_20parametrized_20scatter_20graph_84',['Example (JKQTPlotter): Draw an Artistic Image with a Parametrized Scatter Graph',['../_j_k_q_t_plotter_param_scatter_image.html',1,'exampleTutorialProjects']]],
  ['as_20a_20graph_85',['Example (JKQTPlotter): QImage as a Graph',['../_j_k_q_t_plotter_image_plot_q_image_r_g_b.html',1,'exampleTutorialProjects']]],
  ['as_20a_20rug_20plot_86',['Visualizing data as a Rug Plot',['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md118',1,'']]],
  ['as_20basis_20for_20jkqtplotter_87',['JKQTBasePlotter as Basis for JKQTPlotter',['../class_j_k_q_t_base_plotter.html#jkqtplotter_usage_baseplotter_in_widget',1,'']]],
  ['as_20line_20graphs_88',['as Line Graphs',['../_j_k_q_t_plotter_function_plots.html',1,'Example (JKQTPlotter): Plotting Mathematical Functions as Line Graphs'],['../_j_k_q_t_plotter_eval_curves.html',1,'Example (JKQTPlotter): Plotting Parametric Mathematical Curves as Line Graphs'],['../_j_k_q_t_plotter_parsed_function_plot.html',1,'Example (JKQTPlotter): Plotting Parsed Mathematical Functions as Line Graphs']]],
  ['as_20plot_20functions_89',['C++ functors as plot functions',['../_j_k_q_t_plotter_function_plots.html#autotoc_md72',1,'']]],
  ['as_20shortcuts_20to_20drawing_20violin_20plots_90',['Adapters as shortcuts to drawing Violin Plots',['../_j_k_q_t_plotter_violinplot_graphs.html#autotoc_md122',1,'']]],
  ['aspect_20ratios_91',['Aspect Ratios',['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_aspectratios',1,'']]],
  ['aspects_20of_20boxplots_92',['Example (JKQTPlotter): Styling different aspects of boxplots',['../_j_k_q_t_plotter_boxplot_styling.html',1,'exampleTutorialProjects']]],
  ['at_20the_20top_20of_20the_20plot_93',['Toolbar at the top of the Plot',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md102',1,'']]],
  ['attribution_94',['Attribution',['../md__c_o_d_e___o_f___c_o_n_d_u_c_t.html#autotoc_md12',1,'']]],
  ['available_20user_20interactions_95',['Available User-Interactions',['../_j_k_q_t_plotter_user_interaction.html#autotoc_md100',1,'']]],
  ['axes_96',['Axes',['../_j_k_q_t_plotter_date_time_axes.html',1,'Example (JKQTPlotter): Date/Time Axes'],['../_j_k_q_t_plotter_secondary_axes.html',1,'Example (JKQTPlotter): Secondary Axes'],['../example_tutorial_projects.html#jkqtp_extut_keyaxesstyles',1,'Examples for Styling the Plot, Keys, Axes, ...'],['../class_j_k_q_t_p_coordinate_axis.html#jkqtplotter_coordinateaxes_inverted',1,'Inverted Coordinate Axes'],['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_grids_baseplotter_majoraxes',1,'Major Coordinate Axes'],['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_grids_baseplotter_secondaryaxes',1,'Secondary Coordinate Axes']]],
  ['axes_20through_20origin_97',['Example (JKQTPlotter): Plot With Axes through Origin',['../_j_k_q_t_plotter_geometric_coordinate_axis0.html',1,'exampleTutorialProjects']]],
  ['axis_98',['Axis',['../_j_k_q_t_plotter_date_time_axes.html#autotoc_md62',1,'Date Axis'],['../_j_k_q_t_plotter_date_time_axes.html#autotoc_md63',1,'Time Axis']]],
  ['axis_99',['Example (JKQTPlotter): Line Graph with Logarithmic y-axis',['../_j_k_q_t_plotter_log_axes.html',1,'exampleTutorialProjects']]],
  ['axis_20range_20plot_20width_100',['Synchronizing Axis Range &amp;amp; Plot Width',['../class_j_k_q_t_base_plotter.html#JKQTBASEPLOTTER_SYNCMULTIPLOT_SYNC',1,'']]],
  ['axis_20tick_20units_20scaling_101',['Axis Tick Units/Scaling',['../class_j_k_q_t_p_coordinate_axis.html#jkqtplotter_coordinateaxes_tickscaling',1,'']]],
  ['axis_20ticks_20and_20grids_102',['Axis Ticks and Grids',['../class_j_k_q_t_p_coordinate_axis.html#jkqtplotter_base_grids_baseelemenets',1,'Axis Ticks and Grids'],['../class_j_k_q_t_base_plotter.html#jkqtplotter_base_grids_baseplotter',1,'Axis Ticks and Grids']]]
];
