
# Instruct CMake to run moc+rcc+uic automatically when needed.
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)

find_package(QT NAMES Qt6 Qt5 COMPONENTS Core REQUIRED)
find_package(Qt${QT_VERSION_MAJOR} COMPONENTS Core Gui Widgets Svg Xml OpenGL REQUIRED)
if(${QT_VERSION_MAJOR} VERSION_GREATER_EQUAL "6")
    find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS OpenGLWidgets)
endif()
if(NOT ${JKQtPlotter_BUILD_FORCE_NO_PRINTER_SUPPORT})
  find_package(Qt${QT_VERSION_MAJOR} OPTIONAL_COMPONENTS PrintSupport)
else()
  message(STATUS "WARNING: not searching for Qt${QT_VERSION_MAJOR}::PrintSupport, because JKQtPlotter_BUILD_FORCE_NO_PRINTER_SUPPORT=${JKQtPlotter_BUILD_FORCE_NO_PRINTER_SUPPORT}")
endif()


set(JKQtPlotter_HAS_NO_PRINTER_SUPPORT FALSE)
if(JKQtPlotter_BUILD_FORCE_NO_PRINTER_SUPPORT)
  set(JKQtPlotter_HAS_NO_PRINTER_SUPPORT TRUE)
else()
  if(TARGET Qt${QT_VERSION_MAJOR}::PrintSupport)
  else()
    set(JKQtPlotter_HAS_NO_PRINTER_SUPPORT TRUE)
  endif()
  if(${QT_VERSION_MAJOR} VERSION_LESS "5" )
    set(JKQtPlotter_HAS_NO_PRINTER_SUPPORT FALSE)
  endif()
endif()
